### ISSUE TITLE
Adding Thunderbird icon?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [snwh/paper-icon-theme#10]
I've noticed that out of all applications that I have currently installed, Thunderbird is the most popular one without an icon as a part of this pack.

Since it is probably the most popular email client for Linux-based operating system, I really think that a special icon needs to be added to this pack.

**Comment by snwh** [comment]
Eventually. Adding application icons is not a main concern at the moment –it's still early days for the theme.
