### ISSUE TITLE
Launcher Icons pixel distorted

### ISSUE THREAD

**Issue by shubhodeep9** [snwh/paper-icon-theme#100]
The icons on launcher are distorted.

![launcher](https://cloud.githubusercontent.com/assets/9017518/14379077/dff86182-fd95-11e5-995d-58e47dea8a59.png)

**Comment by ashwini0529** [comment]
It happens @shubhodeep9

**Comment by varlesh** [comment]
You can change this on /usr/share/icons/Paper/index.theme:
```
[32x32/apps]
Context=Applications
Size=32
Type=Scalable

[48x48/apps]
Context=Applications
Size=48
Type=Scalable
```

**Comment by snwh** [comment]
No.

**Comment by snwh** [comment]
The Paper icons are not scalable in that way. If you set the Unity launcher to a size that does not match the dimensions of Paper icons there will be distortion. This happens with every icon theme, but the distortion is more noticeable in themes with PNG assets, such as Paper.

**Comment by shubhodeep9** [comment]
Ok
