### ISSUE TITLE
Trackpad enable/disable icon is incorrect

### ISSUE THREAD

**Issue by anowlcalledjosh** [snwh/paper-icon-theme#101]
What Paper looks like:

![image](https://cloud.githubusercontent.com/assets/9433472/14379542/5754f2c8-fd72-11e5-8000-fd5695b9aac3.png)

What Ubuntu-mono-dark looks like:

![image](https://cloud.githubusercontent.com/assets/9433472/14379583/96a06692-fd72-11e5-8ba4-15e62107002e.png)

Paper used to have correct icons, but now they're gone.

**Comment by snwh** [comment]
That's very strange. I've probably misnamed an icon somewhere.

**Comment by snwh** [comment]
I think I've fixed this

**Comment by anowlcalledjosh** [comment]
Yep, it's fixed now. Thanks!
