### ISSUE TITLE
Cursor is inconsistent across different windows

### ISSUE THREAD

**Issue by anowlcalledjosh** [snwh/paper-icon-theme#102]
In places like Chrome and the desktop, the default white cursor is displayed. However, in gnome-terminal and gedit, the (Paper) black pointer/black text icons are displayed. To add to the confusion, in Nautilus, the Paper loading cursor is used, but the default triangular cursor is white, like the default Ubuntu one.

Of course, Paper may be dynamically setting the cursor colour depending on the type of window it's in, and this may all be intentional, but I thought I may as well check.

**Comment by snwh** [comment]
It's definitely not intentional. I've seen this in other themes as well. I'm not sure of the cause.

**Comment by Alanaktion** [comment]
Some applications get cursor settings from different places, I've found running something like this usually sets the default globally:
```bash
sudo update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/Paper/cursor.theme 20
sudo update-alternatives --set x-cursor-theme /usr/share/icons/Paper/cursor.theme
```
This requires the theme to be installed globally (in `usr/share/icons/`). I don't know of a reliable way to set the cursor globally from a user installation.

**Comment by snwh** [comment]
Correct, and installing the icon+cursor theme from the PPA package will do the `update-alternatives` for you.

**Comment by anowlcalledjosh** [comment]
Ah, running those worked! Thank you :)
