### ISSUE TITLE
Gimp & Gthumb Icon needs rework

### ISSUE THREAD

**Issue by bigshotjeev** [snwh/paper-icon-theme#103]
I really do LOVE your Icon theme but I do have couple of suggestions to make.
I think the Gimp icon needs rework. Its not worthy of a boring colour pallet icon that you have made for it. My suggestion is to create an icon based on its original mascot, wilbert (the fox or wolf). Also gthumb icon has a round webcam in it. Who use webcam to take photos? The camera should be rectangular.

Also I do love your bluish grey folder theme. Its a fresh concept. At first even I found it odd but now I am not just use to looking at it but I am really loving it.

I know its a hard work and I could only hope to see these changes made.

Thanks & best regards.

**Comment by snwh** [comment]
I may rework the gimp/gthumb icon in the future, but the GIMP logo doesn't transfer well to the Paper style.

**Comment by dnlbaines** [comment]
Not sure if related but since I upgraded to Ubuntu 16.04 the Gimp icon has reverted back to the default one. Hoping it can be changed back to the Paper icon soon.

**Comment by snwh** [comment]
@dnlbaines it's kind of related. I removed the placeholder gimp icon. My intention was to make a new one, but the gimp logo (in my view) is terrible.

**Comment by dnlbaines** [comment]
Ah fair enough, well good luck finding a way to make it fit in!
