### ISSUE TITLE
weather icon on panel problem

### ISSUE THREAD

**Issue by alim0x** [snwh/paper-icon-theme#104]
DE: Ubuntu Unity

This icon theme is beautiful, but there is a little problem.

When weather is fine, the yellow sun icon is good, but when it rains, this is the default no transparency panel:

![screenshot from 2016-04-16 13-02-51](https://cloud.githubusercontent.com/assets/4954007/14579238/2bc6d816-03d4-11e6-98d9-28ec51c08d54.png)

And this is transparent panel:

![screenshot from 2016-04-16 13-03-15](https://cloud.githubusercontent.com/assets/4954007/14579241/47bb0006-03d4-11e6-8c0e-ba9eb2f81e7f.png)

**Comment by Narrat** [comment]
similar case with volume icon

![1460801748](https://cloud.githubusercontent.com/assets/2787518/14580452/a832a6c0-03cd-11e6-8d54-fac7c6f2f5e5.png)

Just to mention it. It doesn't really bother me, that I cannot see it clearly :D

**Comment by snwh** [comment]
@Narrat what is that?

**Comment by snwh** [comment]
@alim0x I don't think I've included panel weather icons, which is why it's black there

**Comment by alim0x** [comment]
@snwh Got it. Waiting for a better paper theme ;)

**Comment by Narrat** [comment]
Somewhere in the picture is the panel icon for volume status ;)
Like this https://github.com/snwh/paper-icon-theme/blob/master/Paper/16x16/panel/audio-volume-high.svg

If looking close enough you cann actually see the outlines

**Comment by snwh** [comment]
@Narrat your panel is using 16px icons?

**Comment by snwh** [comment]
@alim0x I've added weather panel icons in the latest round of commits. They should be in the next update.

**Comment by Narrat** [comment]
@snwh Yes. And now I see, that the ones from 24x24 are visually brighter?
Kinda a placeholder?

**Comment by snwh** [comment]
@Narrat the 24x24 are the optimal size for panel icons.

**Comment by Narrat** [comment]
I meant with placeholder the 16x16 ones.
As I would expect, there should be no visual difference between the sizes?

**Comment by alim0x** [comment]
@snwh Thanks for your work :+1:
