### ISSUE TITLE
Terminix changed icon file name

### ISSUE THREAD

**Issue by elvisd** [snwh/paper-icon-theme#109]
New name is = com.gexperts.Terminix

**Comment by golimpio** [comment]
As far as I could see, `com.gexperts.Terminix` it's just the name for the `.desktop` file (the one installed at `/usr/share/applications`).

The icon itself, which before was `terminix`, is now `utilities-terminal`:

```
Icon[de]=utilities-terminal
Icon[en]=utilities-terminal
Icon[fr]=utilities-terminal
Icon[ko]=utilities-terminal
Icon[pl]=utilities-terminal
Icon[pt_BR]=utilities-terminal
Icon[zh_CN]=utilities-terminal
Icon[zh_TW]=utilities-terminal
Icon=utilities-terminal
```

**Comment by snwh** [comment]
I've added a quick terminix icon

**Comment by snwh** [comment]
`com.gexperts.Terminix.png` is the new icon name.

**Comment by golimpio** [comment]
@elvisd @snwh sorry, my comment was wrong...although they use the default `utilities-terminal` probably for compatibility with old gtk, I missed the whole xdg-app prefixing rules.

btw, @snwh thanks by the icon theme, it looks very professional and refined.
