### ISSUE TITLE
Icon request: Meld

### ISSUE THREAD

**Issue by elvisd** [snwh/paper-icon-theme#111]
Meld is a gui file diff viewer

Icon=meld

Actual icon
![meld](https://cloud.githubusercontent.com/assets/307127/14676137/68119b72-070c-11e6-9bb0-215dd624012f.png)

**Comment by hex007** [comment]
@elvisd How about this?

![meld_noshadow](https://cloud.githubusercontent.com/assets/1689246/14937609/b1489f18-0ec1-11e6-8df2-22de8d07ae46.png)

**Comment by snwh** [comment]
That's too flat and the geometry is not simple enough to be a Paper icon.

**Comment by hex007** [comment]
I didn't know which color comes on top. My initial attempts didnt look that good.

![test](https://cloud.githubusercontent.com/assets/1689246/14937743/d2112c34-0ec5-11e6-9d6a-4e4f6c190c29.png)

**Comment by snwh** [comment]
Don't worry, I've added a meld icon.
