### ISSUE TITLE
Icon request: Anki

### ISSUE THREAD

**Issue by Kogoro** [snwh/paper-icon-theme#112]
Anki is one of the most famous learning card applications.

Actual icon of the android app: https://play.google.com/store/apps/details?id=com.ichi2.anki
Similar Icon on Desktop: ![Anki](http://xiaomi.eu/community/data/attachments/2/2066-5bc3dbe1d9739508ac8469ae1f0fcac2.jpg)

**Comment by snwh** [comment]
Boy is that a bad default icon.
