### ISSUE TITLE
Python Icons incomplete [easy fix]

### ISSUE THREAD

**Issue by robobenklein** [snwh/paper-icon-theme#113]
The text-x-python images are there, but when the python file is marked executable it now looks for application-x-python as the mimetype image.

Could we symlink the application-x mimetypes to the other python images so they show correctly?

**Comment by snwh** [comment]
I did one better.

**Comment by robobenklein** [comment]
https://github.com/snwh/paper-icon-theme/commit/7f257ba16902861ce882ba4f9fd189d413b221e3 :D great work, thx
