### ISSUE TITLE
[Pidgin][Corebird] Lost icon surface structures in smaller sizes

### ISSUE THREAD

**Issue by tista500** [snwh/paper-icon-theme#116]
Dear developer,

Thanks for your hard work!
I am an author of Adapta.
And I now have some issues with 'Pidgin' and 'Corebird' icons...

[Platform]
* Paper icon theme from git latest pulling: 0a2878a1de849f6dee45b1d79a9884a5216a7069
* Ubuntu GNOME 16.04 LTS
* Gtk+ 3.20.3, Gnome-Shell 3.20.1, Budgie-Desktop 10.2.5, Gnome-Flashback 3.20.0

[Related commits]
 https://github.com/snwh/paper-icon-theme/commit/2265774eaf307cbe77fff44954f1bdbcd348430d and https://github.com/snwh/paper-icon-theme/commit/bcc667abc12eae6647998688c172eb9ffeaf5c0c
(Now those were moved to 'third-party' directory already?)

[Issue I have]
In some smaller sizes, like 16x16px, 24x24px, and 32x32px, those 2 apps icons showed only background purple-square (Pidgin) or slate-blue-circle (Corebird) without any foreground structures. On the other hand, 48x48px or higher, seems normal (means icon design works properly)...

[Wishlist]
* I really hope those 2 icons could have implementation in smaller sizes (lower than 32x32px), too.

Keep up great work.
Best Regards.

**Comment by snwh** [comment]
@tista500 in those cases, when there are "missing" icons, it usually means I've not completed an icon's source plate, so it renders a blank or incomplete asset.

**Comment by snwh** [comment]
For example: 
![screenshot from 2016-04-25 20-30-15](https://cloud.githubusercontent.com/assets/1217306/14803090/8ab31d56-0b24-11e6-9049-6dd5b12752f1.png)

**Comment by tista500** [comment]
@snwh,

Ah, thanks... ;)

Regards.

**Comment by tista500** [comment]
Confirmed this issue was fixed. Thanks again! :)

Best Regards.
