### ISSUE TITLE
(Ubuntu 16.04) 'Ubuntu Software' icon is missing

### ISSUE THREAD

**Issue by jkim-code** [snwh/paper-icon-theme#117]
After upgrading to Ubuntu 16.04, 'Ubuntu Software Centre' is now updated to 'Ubuntu Software'. But Paper icon for this new Ubuntu Software is missing. Previous Paper icon for Ubuntu Software Centre needs to be linked to new Ubuntu Software.

**Comment by Feichtmeier** [comment]
No I think this is because in the /usr/share/applications/org.gnome.Software.desktop the icon is named org.gnome.Software instead of software

**Comment by snwh** [comment]
Okay, what is the actual value for the `Icon=` field in Ubuntu Software's .desktop file.?
