### ISSUE TITLE
Teamviewer

### ISSUE THREAD

**Issue by ricwtk** [snwh/paper-icon-theme#121]
#### Icon Request

- application name
teamviewer
- description
teamviewer icon for teamviewer application
- `icon-file-name`
teamviewer.svg

![teamviewer](https://cloud.githubusercontent.com/assets/3527220/14899778/898ff512-0d85-11e6-9d93-93ffe997b903.png)

**Comment by snwh** [comment]
@ricwtk you should check the latest commit (which was before you filed this bug) 😉
