### ISSUE TITLE
Icon Request: Category Icons

### ISSUE THREAD

**Issue by w9** [snwh/paper-icon-theme#124]
These standard icons commonly seen in an application launcher are missing:

- [x] applications-accessories.png
![image](https://cloud.githubusercontent.com/assets/4512709/14902270/a12583ae-0d35-11e6-8d6e-3e638dde4d42.png)
- [x] applications-engineering.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902275/a78e5702-0d35-11e6-8fb3-61be07dd2f2e.png)
- [x] applications-graphics.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902281/aceae47c-0d35-11e6-870a-362f702a18a6.png)

- [x] applications-internet.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902282/b280f156-0d35-11e6-8358-afff5efb1c64.png)
- [x] applications-multimedia.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902284/b6fed900-0d35-11e6-99d2-7c2ee2a58a35.png)
- [x] applications-office.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902285/bba22db8-0d35-11e6-8acc-e4a698c8b57a.png)

- [ ] applications-other.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902286/bfbef0ac-0d35-11e6-85fa-5da9b1463eb0.png)
- [x] applications-utilities.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902292/c5d3f01e-0d35-11e6-87af-981a32d12787.png)

- [ ] preferences-desktop-personal.png ![image](https://cloud.githubusercontent.com/assets/4512709/14902296/caa748ac-0d35-11e6-9bc2-c2a53b86637e.png)

**Comment by snwh** [comment]
Part of #243
