### ISSUE TITLE
Icon Request: Device

### ISSUE THREAD

**Issue by w9** [snwh/paper-icon-theme#126]
- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902547/6ecf0ebe-0d37-11e6-9d72-fdf42fcdb6d5.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902548/727f78d2-0d37-11e6-8431-cbb95be87061.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902551/76bf0f98-0d37-11e6-9c01-09ab89a53d0c.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902554/7a52318a-0d37-11e6-8f30-e29657f2ced4.png)

- [x] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902558/7e5b58d8-0d37-11e6-87ed-d70add8568a8.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902562/8296020e-0d37-11e6-95bf-5940c6c6b492.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902567/8814a55a-0d37-11e6-9708-be3a5fe03cec.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902569/8e29a18e-0d37-11e6-9179-ad0e140b1571.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902578/9fc53d0e-0d37-11e6-9718-6eefc7c7e347.png)

- [x] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902580/a29f2e54-0d37-11e6-9a48-c5fd6d40a2ae.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902584/a623fef6-0d37-11e6-9fc9-6ce1f4bed5ea.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902587/ac83bd5e-0d37-11e6-9fc6-01c1b80c91a0.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902589/afb4d968-0d37-11e6-8d36-377c17249ced.png)

- [x] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902595/bce7de8c-0d37-11e6-802b-15d29b43cf90.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902600/c1248a4a-0d37-11e6-8322-3d7f84727420.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902610/c72405a6-0d37-11e6-9db9-7d85af04c554.png)

**Comment by snwh** [comment]
Update this as a checklist please.

**Comment by snwh** [comment]
Superceded by of #244
