### ISSUE TITLE
Icon Request: Emblems

### ISSUE THREAD

**Issue by w9** [snwh/paper-icon-theme#127]
- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902859/2cee00e8-0d39-11e6-8fc0-0d9fbce8b76f.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902869/34c3625e-0d39-11e6-8c9b-8f12f8a28d0a.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902875/384d3328-0d39-11e6-90ea-8e806fe84e00.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902879/3e07e11e-0d39-11e6-8f57-7faf5cc6da66.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902884/430ff53e-0d39-11e6-93d5-856bcbb6df25.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902888/4644c6bc-0d39-11e6-9e19-0a18bc9615f8.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902891/4d551ee8-0d39-11e6-9d88-67e9474635d9.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902895/50239726-0d39-11e6-9b46-95c82b0b0f33.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902900/575ea1de-0d39-11e6-959d-53d8f1dd4829.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902907/5a1b0d5e-0d39-11e6-8c01-133edc098342.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902909/5d47451a-0d39-11e6-8224-bb607b657733.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902913/61548ba4-0d39-11e6-8230-88b9ccb3b571.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902915/64c7bc3e-0d39-11e6-899b-e413e83045ad.png)

- [ ] 

![image](https://cloud.githubusercontent.com/assets/4512709/14902917/68cde77c-0d39-11e6-82bf-9c5b024b148e.png)

**Comment by snwh** [comment]
Are these even used by any apps any more?

**Comment by w9** [comment]
They are "emblems", meaning that they show up as badges on other icons, like this:

![image](https://cloud.githubusercontent.com/assets/4512709/14908226/3bdb8ee0-0d70-11e6-96a2-6093b7d7fc3e.png)

**Comment by snwh** [comment]
@w9 yes, this I know. But fewer file managers use these specific emblems any more.

**Comment by w9** [comment]
Hmm. I didn't realize that Nautils and Nemo no longer support emblems. But I guess Thunar still supports it (although I don't use it).

Looks like its not that important anymore. You can close this issue if you want. :)

**Comment by snwh** [comment]
Not saying it's not important, it'll just be of a low priority.

**Comment by snwh** [comment]
This has been replaced by #245
