### ISSUE TITLE
Icon Request: QtCreator

### ISSUE THREAD

**Issue by tim-sueberkrueb** [snwh/paper-icon-theme#129]
**QtCreator** is the IDE for all things Qt (https://www.qt.io/).
The icon filename is:
- `QtProject-qtcreator.png`

Current icon:
![qtproject-qtcreator](https://cloud.githubusercontent.com/assets/11774614/14919023/151fbe2c-0e27-11e6-8894-dd266301dda3.png)
Though, please note that Qt [recently changed it's logo](http://blog.qt.io/blog/2016/04/13/making-the-qt-brand-remarkable/):
https://s3-eu-west-1.amazonaws.com/qt-brand/uploads/2015/04/qt_logo_primary.jpg
So the next official Qt Creator icon will probably be based on this.

**Comment by snwh** [comment]
So Paper's icon will be based on that then

**Comment by tim-sueberkrueb** [comment]
Yay, thanks Sam. Looks great next to the SDK icon.
