### ISSUE TITLE
Weird back and forward icons on Chrome

### ISSUE THREAD

**Issue by jyeramirez** [snwh/paper-icon-theme#13]
It's been like that for a couple of weeks now.
Here's the screenshot:
![screenshot from 2015-03-17 03 30 21](https://cloud.githubusercontent.com/assets/11145791/6674672/666fcc68-cc56-11e4-93d4-d726f606d9c6.png)

**Comment by snwh** [comment]
Perhaps if it had been reported a few weeks ago I could have fixed it then. ;)

**Comment by jyeramirez** [comment]
Been too busy. Though it has been brought to your attention already.
Thanks! This theme and icon pack are awesome!

**Comment by nahtnam** [comment]
Also want to report that when you the stop icon (when you are loading a page) is messed up. http://i.imgur.com/scWfz3x.png

**Comment by michel-slm** [comment]
I'm encountering this on my work laptop (Ubuntu 14.04) but not on my home laptop (Fedora 22 alpha). @jyeramirez what distribution and version are you seeing this on?

**Comment by jyeramirez** [comment]
@michel-slm I'm on Ubuntu 14.04 too.

**Comment by ELadner** [comment]
I'm seeing the exact same problem.  Tried researching briefly but to no avail.

**Comment by ashantyk** [comment]
I have the same bug. Ubuntu 14.04 LTS & Gnome 3.10

**Comment by snwh** [comment]
@ashantyk have you updated?

**Comment by ashantyk** [comment]
I do updates every morning for the last 1.5 years :D

**Comment by ashantyk** [comment]
"dpkg -l | grep paper"
..
ii  paper-gtk-theme                                       1.0-0~148~ubuntu14.04.1                             all          Paper GTK Theme
ii  paper-icon-theme                                      1.0-0~129~ubuntu14.04.1                             all          Paper Icon Theme
..

**Comment by jyeramirez** [comment]
Fixed! Thanks @snwh

**Comment by michel-slm** [comment]
Kudos @snwh -- it's been fixed since the previous update for me too

**Comment by ashantyk** [comment]
what version of ubuntu & gnome are you using ?

**Comment by nahtnam** [comment]
Not fixed for me. I am running most updated version.

**Comment by nahtnam** [comment]
Nvm. Just updated again and it works!

Thanks for the fix!

**Comment by ashantyk** [comment]
fixed for me also after recent updates. thx!
