### ISSUE TITLE
Problem with Nylas N1 icon

### ISSUE THREAD

**Issue by edshevsky** [snwh/paper-icon-theme#132]
There are the problem with Nylas N1 icon on the GNOME Dash-to-Dock extension. Then I set size 33 px or higher - icon looks good. But then icon's size is 32 px or smaller - there are only blue ring.

Nylas N1 icon 32 px:

![nylas n1 icon 32 px](https://cloud.githubusercontent.com/assets/12774629/14922172/bb5f282e-0e3e-11e6-80d7-d99f43054d18.png)
----------------------------------------------------------------------------------------------------------------------------------------
Nylas N1 icon 33 px:

![nylas n1 icon 33 px](https://cloud.githubusercontent.com/assets/12774629/14922194/d6fd3666-0e3e-11e6-9050-0e13ea114edd.png)

**Comment by snwh** [comment]
The Nylas icon is incomplete
