### ISSUE TITLE
Elementary "Photos" missing icons.

### ISSUE THREAD

**Issue by DroWnThePoor** [snwh/paper-icon-theme#134]
![photosissue](https://cloud.githubusercontent.com/assets/16339020/14928342/3f49bf9c-0e25-11e6-94e5-1dd6326dbb1c.png)

The missing buttons are: Adjust photo's color and tone. & Automatically improve photo's appearance.
I hope I'm not the only one experiencing this issue.

**Comment by renearts** [comment]
Check, I'm missing these as well :)

**Comment by bil-elmoussaoui** [comment]
The icon names are 
`image-adjust`
`image-auto-adjust`
Default icons look like those
![568a7b0a-277c-11e5-889c-6da3aab42506](https://cloud.githubusercontent.com/assets/7660997/15413056/26009a70-1e2d-11e6-915b-65dd98f4db85.png)
