### ISSUE TITLE
Icon request: Double Commander

### ISSUE THREAD

**Issue by elmodos** [snwh/paper-icon-theme#135]
Double Commander is awesome dual-panel file manager. Can you make an icon for it in Paper style?
Project site: http://doublecmd.sourceforge.net/
Icon used in .desktop file: "doublecmd"

![128px-dcfinal](https://cloud.githubusercontent.com/assets/1112612/14932454/f6a62690-0e7e-11e6-813b-85c0bae2f625.png)

**Comment by snwh** [comment]
No, I can't it's red.

**Comment by elmodos** [comment]
Is it a problem? It can be gray with symbolc "DC" like on original

**Comment by snwh** [comment]
@elmodos that was a joke. :P

**Comment by elmodos** [comment]
:laughing:

**Comment by snwh** [comment]
@elmodos it should be in your next update

**Comment by elmodos** [comment]
Looks awesome. Thanks
