### ISSUE TITLE
Icon request: Android Studio

### ISSUE THREAD

**Issue by gabrielelucci** [snwh/paper-icon-theme#139]
**Application name:** Android Studio
**Description:** _The official IDE for Android app development_
**Icon name:** `android-studio`
**.desktop file:**
```
$ cat /usr/share/applications/android-studio.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Exec=android-studio %f
Icon=android-studio
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupNotify=true
StartupWMClass=jetbrains-studio
MimeType=application/x-extension-iml;

```
**Additional notes:** Actually, an Android Studio icon is already present in the theme, but it is called `android-sdk` while the most popular [AUR package](https://aur.archlinux.org/packages/android-studio/) use `android-studio` instead.
I think that a symlink to `android-studio` will be enough.

**Comment by gabrielelucci** [comment]
We can consider this closed, right? Keep up the good work!

**Comment by snwh** [comment]
@gabrielelucci you get to close it when you get the icon :)
