### ISSUE TITLE
Too dark battery icon, hard to see

### ISSUE THREAD

**Issue by tthanh** [snwh/paper-icon-theme#14]
![screenshot from 2015-03-21 08 44 26](https://cloud.githubusercontent.com/assets/8962973/6763235/af4c456c-cfa6-11e4-852b-ba0c4e6f0164.png)

Ubuntu 15.04 install via ppa

**Comment by snwh** [comment]
This is a bug with the power menu: it uses the symbolic icon in the theme but doesn't allow for theming it.

**Comment by snwh** [comment]
https://bugs.launchpad.net/ubuntu/+source/indicator-power/+bug/1256060
