### ISSUE TITLE
Cinnamon Compatibility

### ISSUE THREAD

**Issue by gitgud-software** [snwh/paper-icon-theme#141]
Things are mostly good on my end, but there's a few improperly selected icons when using Cinnamon. In particular, the "Lock Screen" icon is replaced with the Brightness icon as shown here. The "logout" shortcut is also incredibly light and hard to see in this theme. The folder icon displayed when in the file manager works, but it also seems out of place when most GTK+ panels are a dark color. It looks like the applets in the right side of the panel blend in fine though.

![screenshot from 2016-05-03 23-41-44](https://cloud.githubusercontent.com/assets/10673048/15004776/3c684390-1189-11e6-8480-c9fcab74a914.png)

![screenshot from 2016-05-03 23-45-39](https://cloud.githubusercontent.com/assets/10673048/15004802/81ce008c-1189-11e6-93c6-d227caf476b6.png)

**Comment by snwh** [comment]
Some of those issues are due to Cinnamon's generally poor use of icons. For instance, the lock button (incorrectly) uses the `preferences-system-brightness-lock` icon

**Comment by gitgud-software** [comment]
Any way to get some hacky solutions to these problems? I can't imagine the situation is entirely hopeless.

**Comment by snwh** [comment]
The right solution is to file bugs against Cinnamon, and wait. A user-end solution is to change the icon in a theme.
