### ISSUE TITLE
Codeblocks IDE missing icon

### ISSUE THREAD

**Issue by xeloni** [snwh/paper-icon-theme#144]
- Codeblocks
- The open source, cross platform, free C, C++ and Fortran IDE.
- Icon name : `codeblocks`

[Logo](https://upload.wikimedia.org/wikipedia/fr/0/01/Codeblocks_logo1.png)

.desktop file

cat /usr/share/applications/codeblocks.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Code::Blocks IDE
GenericName=Integrated development environment
Comment=Configurable and extensible IDE
Exec=codeblocks %F
Icon=codeblocks
Terminal=false
X-MultipleArgs=false
Categories=Development;IDE;GTK;
StartupNotify=true
MimeType=application/x-codeblocks;application/x-codeblocks-workspace;

**Comment by xeloni** [comment]
![capture du 2016-05-14 07-32-33](https://cloud.githubusercontent.com/assets/8897998/15266471/24deaaaa-19a6-11e6-9491-3597bbb6839d.png)
Thanks for your commit :)

**Comment by Takucht** [comment]
Hey bro! What theme you uses for your ubuntu? Thank you very much !
