### ISSUE TITLE
Wrong Icon color: ubuntu 16.04 unity sound notification

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/paper-icon-theme#145]
![bildschirmfoto vom 2016-05-06 22-20-04](https://cloud.githubusercontent.com/assets/15329494/15085149/cac646ae-13d8-11e6-8127-cee4e1275cad.png)

As you can see and prbly know the notifications in unity are dark and transparent. That's why a light icon for the sound/brightness indicators would be better. I don't know if this is possible but it would be awesome. Otherwise extremly cool icon set! Thank you for that!

**Comment by xeloni** [comment]
I confirm this issue.

**Comment by anowlcalledjosh** [comment]
Not just 16.04, has been an issue on 14.04 too. (Given that the background of the volume notification changes based on desktop background, would light icons look bad with a light wallpaper? OTOH, text on the desktop is exclusively white, so light backgrounds can't be that common.)
