### ISSUE TITLE
Icon request: Variety

### ISSUE THREAD

**Issue by anowlcalledjosh** [snwh/paper-icon-theme#148]
Application: Variety and Variety Slideshow

Description: a wallpaper changer app (i.e. to cycle through a set of images, to fetch them from online, etc.)

http://peterlevi.com/variety/

- [x] `variety`

  ![image](https://cloud.githubusercontent.com/assets/9433472/15125499/0f63c7c0-1625-11e6-8b78-11eaecd62961.png)

- [x] `variety-indicator` (looks OK already, mostly listing for completeness)

  ![image](https://cloud.githubusercontent.com/assets/9433472/15125504/1edc58de-1625-11e6-845a-e8412da295e7.png)

- [x] `variety-slideshow`

  ![image](https://cloud.githubusercontent.com/assets/9433472/15125514/30c7c330-1625-11e6-803b-80cd7832c82a.png)

I really appreciate the work you put into this icon set; it looks incredibly good (I'm loving the new GIMP icon!)

**Comment by snwh** [comment]
I am not that enthusiastic about the GIMP icon, but it's in there due to popular demand.

**Comment by dernalis** [comment]
I just saw this gallery http://twistedsifter.com/2016/06/animal-illustrations-made-from-circles-by-dorota-pankowska/ and recall @snwh was not hapy with GIMP icon. I hope it could be inspirational.
