### ISSUE TITLE
Icon request : f.lux

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-icon-theme#149]
### Icon Request

- f.lux
- "it makes the color of your computer's display adapt to the time of day, warm at night and like sunlight during the day."
- icon name `fluxgui`

![fluxgui](https://cloud.githubusercontent.com/assets/7660997/15186118/17438296-179c-11e6-9f23-c10bdeaad695.png)

f.lux has an indicator icon too, the icon 
![capture du 2016-05-11 17-12-59](https://cloud.githubusercontent.com/assets/7660997/15186018/a0c1d8a2-179b-11e6-99c0-44321f4513ce.png)
icon name `fluxgui-panel.svg`

**Comment by snwh** [comment]
FYI, I do provide a google chrome panel icon.

**Comment by bil-elmoussaoui** [comment]
I the icon i asked for was f.Lux panel :p

**Comment by bil-elmoussaoui** [comment]
Thanks!!
