### ISSUE TITLE
Rhythmbox menu

### ISSUE THREAD

**Issue by GeoZac** [snwh/paper-icon-theme#15]
the icons in rhythmbox music menu are not visible
![screenshot from 2015-03-14 11 58 38](https://cloud.githubusercontent.com/assets/11597134/6769317/79562268-d0bc-11e4-82c2-e46998ff774d.png)

Hatsoff for this material theme

**Comment by snwh** [comment]
It's not "material".

**Comment by GeoZac** [comment]
"Material Inspired",i thought :-P

**Comment by snwh** [comment]
The icon theme is. ;-)

**Comment by nahtnam** [comment]
@snwh Any update on this? I cant control my music!!! :p

**Comment by fitojb** [comment]
That would be a bug in indicator-sound. I can’t think of any correlation with the icon theme.

**Comment by nahtnam** [comment]
@fitojb The button are still there, but they are hard to see because the arrows arent showing up. This bug only showed up after I installed the Paper theme.

**Comment by snwh** [comment]
This was a theme issue.
