### ISSUE TITLE
Icon request: dropbox FOLDER

### ISSUE THREAD

**Issue by maxkoryukov** [snwh/paper-icon-theme#151]
### Icon Request

- Dropbox, icon for folders
- Icon for dropbox root folder
- `folder-dropbox-symbolic.svg` or smth like this

_Image made from existing Dropbox icon_

![selection_001](https://cloud.githubusercontent.com/assets/8887971/15198013/29c50848-17ee-11e6-95bf-d29833d03180.png)

**Comment by maxkoryukov** [comment]
Here is original icon (taken from this repo)

[folder-dropbox-symbolic.svg.zip](https://github.com/snwh/paper-icon-theme/files/260313/folder-dropbox-symbolic.svg.zip)

**Comment by snwh** [comment]
Added as dropbox-folder.

**Comment by maxkoryukov** [comment]
@snwh , thanks!!!
