### ISSUE TITLE
Icon Request: Gnome-nettool, gnome-mplayer

### ISSUE THREAD

**Issue by JLCCI** [snwh/paper-icon-theme#152]
Thanks for by far the best icon pack for Linux. Hope you could add those three icons below.

New:
- [x] `gnome-nettool`
Network Management Tool for Gnome
Current Icon:
https://apps.ubuntu.com/site_media/icons/2013/06/gnome-nettool_2.png

- [x] `gnome-mplayer`
Frontend for MPlayer, Possible a link to MPlayer icon would be enough
Current Icon:
https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/GNOME_MPlayer_logo.svg/120px-GNOME_MPlayer_logo.svg.png

Update:
The only icon from the ones that I use that does not look very 'material'. Would be great if you could update.

file-roller
file-roller.png
Icon=file-roller.png
Archive Manager
Current Icon:
Paper One

Thank you!

**Comment by snwh** [comment]
Regarding the file roller icon, that's what it will be until I think of a better solution.

**Comment by JLCCI** [comment]
Big thanks for adding the icons so fast, much appreciated.

For the file-roller, seems tricky to find something that will look good and hmm material-like. ;) The best thing I can think are variation of the boxes or the original icon.

Keep up the great work!
