### ISSUE TITLE
Guake Icons

### ISSUE THREAD

**Issue by dernalis** [snwh/paper-icon-theme#154]
Guake icon:
- application name: guake
- short description: dropdown terminal
- icon-file-name: guake
- original:
![guake_original](https://cloud.githubusercontent.com/assets/3215655/15265147/11ffd3a0-197e-11e6-8ce6-32758be97af6.png)
- sugestion:
![guake](https://cloud.githubusercontent.com/assets/3215655/15265149/1d056a80-197e-11e6-92d8-9aed27b888a5.png)

Guake preferences:
- icon-file-name: guake-prefs
- alternative theme original:
![guake-prefs-alt](https://cloud.githubusercontent.com/assets/3215655/15265167/72e399e0-197e-11e6-83ae-eb53bbc5fb9e.png)
- sugestion:
![guake-prefs](https://cloud.githubusercontent.com/assets/3215655/15265169/8031e11a-197e-11e6-84e9-a75b5c5fe433.png)

Sugestions just as brainstorming.
guake icon could also be a link to utilities-x-terminal as stock alternative.

**Comment by snwh** [comment]
I've come up with something else.

**Comment by dernalis** [comment]
Nice. Thanks.
