### ISSUE TITLE
Clementine chaos

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [snwh/paper-icon-theme#155]
Hi there!

First of all, congratz on this amazing icon theme!

But I got scared when I run Clementine for the first time after installing this theme... lots of icons have wrong sizes, messing the application all around, look:

![screenshot from 2016-05-14 01-51-24](https://cloud.githubusercontent.com/assets/12160864/15266296/f0409a62-1976-11e6-8ee2-183d9b054905.png)

I tried a lot of other music players, but I always come back to Clementine...

Is this a bug related with this icon theme?

Best regards,
Rafael Pacheco.

**Comment by snwh** [comment]
My guess is it's a bug in clementine. It appears to be using the HiDPI versions of icons for some reason.

**Comment by rafael-renan-pacheco** [comment]
Somebody wrote a solution about replacing the app icon theme: https://github.com/clementine-player/Clementine/issues/5258

I'll try that later, thanks :smile:
