### ISSUE TITLE
Terminal icon is too plain.

### ISSUE THREAD

**Issue by user501254** [snwh/paper-icon-theme#157]
Terminal icon is indistinguishable on certain dark gnome-shell themes because its so plain (and dark :p).

I was thinking of a light border or a larger inset prompt or both.
Something like these (novice editing):
![utilities-terminal-1](https://cloud.githubusercontent.com/assets/6129517/15270617/695e0778-1a43-11e6-9e5c-e4edfb998e6a.png)
![utilities-terminal-2](https://cloud.githubusercontent.com/assets/6129517/15270616/695daf9e-1a43-11e6-8a57-a352ebf954de.png)

Related:
- https://github.com/snwh/paper-icon-theme/issues/82
- https://github.com/tista500/Adapta/issues/12#issuecomment-191800671

**Comment by snwh** [comment]
But, I like the single shape Terminal icon. It'd only be indistinguishable on backgrounds that are very close to its color.

The $_ perhaps could be larger.

**Comment by user501254** [comment]
The single shape Terminal icon is indeed aesthetically pleasing.
The thing is there are just a few nice GTK+ themes that have a similar shade of color (either for Dock or app preview folders), causing the issue.

I seriously wouldn't have cared if it had been any other icon but this is the terminal we are talking about :p .

**Comment by maxkoryukov** [comment]
if the internal black terminal's rectangle will be rounded a bit, then it will be very cool solution. At least, I could find terminal on black panel))

**Comment by user501254** [comment]
@maxkoryukov 
I wanted to do that but had no clue how to do it. :see_no_evil:

**Comment by snwh** [comment]
Just for you lot, I've added an [alternate icon](https://raw.githubusercontent.com/snwh/paper-icon-theme/master/Paper/512x512/apps/utilities-terminal-alt.png) just edit your .desktop file to point to `utilities-terminal-alt`.

**Comment by user501254** [comment]
@snwh 
Thank you so much! 
Tried the alternate version, looks perfect.
