### ISSUE TITLE
Wrong icons dimensions

### ISSUE THREAD

**Issue by lexeii** [snwh/paper-icon-theme#158]
Hi Sam,
Thank you so much for the wonderful icon theme!

I found wrong icons dimensions inside the svg files in the `Paper/16x16/actions/` folder.
It might look like `height="16.251362"`, or even like `height="17.003361"` where I think `height` and `width` both should be exact `"16"` for the pixel-prefect icons.

Sorry, I did not looking through other files and folders, there may be more png and svg files affected.

**Comment by snwh** [comment]
Hmm, that shouldn't be the case. Do you know which specifically?

**Comment by lexeii** [comment]
A lot of them. OK, I will correct the numbers myself for a couple of days.
Unfortunately, I am new to git (I'm Mercurial user), but then I'll try to make a pull request.

**Comment by snwh** [comment]
Unfortunately, simply correcting the numbers will distort the icons. I'll have to find edit them.

**Comment by lexeii** [comment]
Sorry about that.

But IMHO nothing to do more. Not a knowledge, only my experience: when I
changed height and width to 48, only icon canvas changed to 48x48, while
the icon image itself stay untouched. IMHO the only possible problem is
clipping original 17x16 icon (for example) into 17x16.

**Comment by snwh** [comment]
I pushed a commit that should fix those that were 17 px high

**Comment by lexeii** [comment]
Well, you the author :)
