### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by cybre** [snwh/paper-icon-theme#16]
There are some major problems with the rendering of symbolic icons.
Here's Scratch for example:

![screenshot from 2015-04-04 03 20 35](https://cloud.githubusercontent.com/assets/3101505/6990938/21e9cd46-da7a-11e4-8bc9-edc856334a2c.png)

Here's a screenshot of the problematic icons from the previous screenshot as rendered in Files.
![screenshot from 2015-04-04 03 26 21](https://cloud.githubusercontent.com/assets/3101505/6990948/7e864688-da7a-11e4-9579-63e0373c2b38.png)

The weird thing is, the icons look fine on GitHub or opened in a web browser, but not on the system.

Edit: There are much more broken icons.

**Comment by snwh** [comment]
I think the SVG clean may have messed them up.
