### ISSUE TITLE
Icon Request : uGet

### ISSUE THREAD

**Issue by mcjoeng** [snwh/paper-icon-theme#162]
### Icon Request

- uGet
- easy-to-use download manager written in GTK+
- uget-icon , uget-tray-default, uget-tray-downloading, uget-tray-error 

 - [x] uget-icon
![uget-icon](https://cloud.githubusercontent.com/assets/10485304/15274810/56f4c04e-1aee-11e6-8579-875e74fcdc6f.png)
 - [x] uget-tray-default
![uget-tray-default](https://cloud.githubusercontent.com/assets/10485304/15274822/8b571058-1aee-11e6-8bab-a5ab5e26a208.png)
 - [x] uget-tray-downloading
![uget-tray-downloading](https://cloud.githubusercontent.com/assets/10485304/15274823/8b592aa0-1aee-11e6-850a-2d2c7506aaf6.png)
 - [x] uget-tray-error 
![uget-tray-error](https://cloud.githubusercontent.com/assets/10485304/15274824/8b81e558-1aee-11e6-9fa9-25403c2ddfba.png)

===

**Comment by snwh** [comment]
uGet a request, iGet to make it.
