### ISSUE TITLE
Printer icon is barely visible in panel

### ISSUE THREAD

**Issue by anowlcalledjosh** [snwh/paper-icon-theme#165]
The printer icon used in the applet panel (?) is barely visible against the dark background on Ubuntu 14.04:

![image](https://cloud.githubusercontent.com/assets/9433472/15296345/e59a3a9c-1b8c-11e6-983b-a34afc4d9c8f.png)

I'm not sure what the icon name is, sorry! It's presumably one of `fileprint`, `gtk-print`, `stock_print` or `document-print` from looking in `Paper/16x16/` – unfortunately they all look the same, ~~and I don't know how to find out which one gets used by `system-config-printer-applet`.~~ I had a look through the source, and it [looks like](https://github.com/twaugh/system-config-printer/blob/1bd2d0f618d10acbd26f12d08c8ac25a703f5449/troubleshoot/Welcome.py#L43) it uses `stock_print`, although I'm not sure; that appears to be part of a setup screen, but it's the only icon mentioned from the ones that look the same.

**Comment by snwh** [comment]
Hmm. It's probably `document-print`.

**Comment by snwh** [comment]
This applet is not the printer indicator?

**Comment by anowlcalledjosh** [comment]
Sorry, I'm not sure what you mean; it appears whenever I print anything, which fits the behaviour described in the `system-config-printer-applet` man page:

> To save memory, the applet waits first of all until the user has printed a job before putting the icon in the notification area.

**Comment by snwh** [comment]
Related to #197
