### ISSUE TITLE
Paper icons not listed in Gnome Tweak Tool after installation 

### ISSUE THREAD

**Issue by mckennajones** [snwh/paper-icon-theme#166]
After running the command `sudo ./install-icon-theme.sh` icons are correctly installed to /usr/share/icons/Paper.

However, the option to select them is not visible in gnome tweak tool. Maybe an issue with the installation script?

**Comment by SShrike** [comment]
Have you run `gtk-update-icon-cache`?

**Comment by mckennajones** [comment]
@SShrike Yes I have tried this, still no luck

**Comment by anaknaga** [comment]
I can confirm the installation script doesn't work on openSUSE Tumbleweed (Gnome 3.20.2). Icons are reset to adwaita whether I install to local user, root user, or build it myself.

**Comment by SShrike** [comment]
Works for me with the following commands:
```sh
./autogen.sh --prefix='/usr'
make
sudo make install
sudo rm -f "/usr/share/icons/gnome/icon-theme.cache"
sudo gtk-update-icon-cache
```

**Comment by anaknaga** [comment]
Tried your commands, same result. Does not work, icons don't show up in gnome-tweak-tool. Thanks for your suggestion though. Open for ideas. Perhaps it has to do something with gtk3.20?

**Comment by SShrike** [comment]
That's strange, I'm running GNOME Shell 3.20.2 on Arch Linux and it's working fine. What distribution are you all running?

**Comment by anaknaga** [comment]
I decided to clone the repo instead of downloading the zip. Strangely now the installation works (with the exception of the icon theme). I've no idea what went wrong, but all good now! Thanks

**Comment by snwh** [comment]
FWIW I've created repos of Paper so you can get packages for most systems now so you needn't install from source: https://snwh.org/paper/download

**Comment by anaknaga** [comment]
Brilliant, working like a charm on openSUSE Tumbleweed. Thanks a lot @snwh!
