### ISSUE TITLE
Icon Request: Zotero

### ISSUE THREAD

**Issue by zhaofengli** [snwh/paper-icon-theme#170]
- Zotero Standalone (https://www.zotero.org)
- FOSS reference management tool
- `zotero.png` ![zotero](https://cloud.githubusercontent.com/assets/2189609/15325780/1b70eb10-1c7e-11e6-893a-1bb6d3d5d8e0.png)

I've been using the browser extension for some time, and find the icon of the standalone version alien on my desktop among all the awesome icons you've made. Thank you! :smile:

**Comment by bil-elmoussaoui** [comment]
Thanks for the icon, looks really beautiful! :D

**Comment by zhaofengli** [comment]
Wow, that looks really nice :+1: Many thanks!
