### ISSUE TITLE
WPS Office

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-icon-theme#171]
Hey! Thanks for the awesome work
There's a 3 office icons missing on my desktop

- [x] WPS Writer
**Icon name :**  `wps-office-wpsmain`
**Default icon:** 
![wps-office-wpsmain](https://cloud.githubusercontent.com/assets/7660997/15343222/50d90b26-1c9b-11e6-8a12-2f5591bbabaa.png)

- [x] WPS Presentation
**Icon name :** `wps-office-wppmain`
**Default icon:** 
![wps-office-wppmain](https://cloud.githubusercontent.com/assets/7660997/15343221/4ed60fae-1c9b-11e6-98d9-b1c42432bf8f.png)

- [x] WPS Spreadsheets
**Icon name :** `wps-office-etmain`
**Default icon:** 
![wps-office-etmain](https://cloud.githubusercontent.com/assets/7660997/15343220/4ca822f8-1c9b-11e6-959d-f52c74385ccc.png)

**Comment by snwh** [comment]
These should be straightforward.

**Comment by bil-elmoussaoui** [comment]
Btw, do/will you accept Steam icons requests? :P

**Comment by snwh** [comment]
I accept them, but it doesn't mean I'll do them ;)

**Comment by bil-elmoussaoui** [comment]
Thanks for the answer! One last question, can you consider having a bountysource linked to the repo?

**Comment by snwh** [comment]
@bil-elmoussaoui what for?

**Comment by bil-elmoussaoui** [comment]
To be able to donate from time to time! if there's an other way to do that, je suis preneur :)

**Comment by snwh** [comment]
Well, that's what this page is for: https://snwh.org/paper/donate :)

**Comment by bil-elmoussaoui** [comment]
Thanks for adding the icons, but the icon names are not the same :p

**Comment by snwh** [comment]
fixed that

**Comment by bil-elmoussaoui** [comment]
That was faster than light! Many thanks

**Comment by snwh** [comment]
Well, I'm continually working on Paper –since I've currently nothing better to do.
