### ISSUE TITLE
Icon Request : Zotero

### ISSUE THREAD

**Issue by JLCCI** [snwh/paper-icon-theme#175]
Would be great if you can add the icon for this open source reference manager. Many thanks!

"Zotero Standalone. Is a free, easy-to-use tool to help you collect, organize, cite, and share your research sources."
Icon=zotero
zotero.png
Current icon:
https://www.zotero.org/support/_media/logo/zotero_512x512x32.png

**Comment by bil-elmoussaoui** [comment]
Already fixed here #170
