### ISSUE TITLE
Icon Request: Rust Source Code

### ISSUE THREAD

**Issue by SShrike** [snwh/paper-icon-theme#176]
I noticed that there aren't any file-type icons for Rust, was wondering if you could add them when you have time please :)

- The extension for Rust source code is `.rs`.
- The MIME type for Rust source code is `text/x-rust`.

You can find official downloads of the Rust logo here: https://github.com/rust-lang/rust/issues/11562.

**Comment by snwh** [comment]
I'd imagine the filename is `text-x-rust`

**Comment by SShrike** [comment]
Sorry for forgetting to include the filename, but yes I'd imagine the icon's filename is `text-x-rust`.

I confirm once I'm home.

**Comment by SShrike** [comment]
Thanks! :tada:
