### ISSUE TITLE
Icon Request: LinSSID

### ISSUE THREAD

**Issue by ghost** [snwh/paper-icon-theme#178]
- LinSSID
- Find local wireless attach points

- [ ] `linssid.png` ![linssid](https://cloud.githubusercontent.com/assets/6396954/15368766/05fee01c-1cdc-11e6-89f5-8584ebd554bb.png)
- [ ] `linssid48.png` ![linssid48](https://cloud.githubusercontent.com/assets/6396954/15368794/23103d18-1cdc-11e6-8ed0-a4a82f77f09e.png)

- [ ] `linssid32.xpm`

**Comment by snwh** [comment]
Shall I give it a more exciting icon?

**Comment by BLDTG** [comment]
I say so.

**Comment by snwh** [comment]
Took awhile, but it's in now :)
