### ISSUE TITLE
paper-icon-theme deb depends on paper-cursor-theme deb, but that is not provided

### ISSUE THREAD

**Issue by cholmcc** [snwh/paper-icon-theme#180]
The current daily snapshot of paper-icon-theme depends on the package paper-cursor-theme, but that package isn't available for download for your site, nor from the launchpad page.  Please provide a (dummy) package.  

Yours, 

Christain

**Comment by snwh** [comment]
I forgot about that one.

**Comment by snwh** [comment]
I'll remove the dependency.
