### ISSUE TITLE
Whatsapp Icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-icon-theme#184]
There's a lot of Electron/NodeJS applications out there for Whatsapp + Chrome applications
**Icon name :** `whatsie`
**Default icon :** 
 
![whatsapp_icon](https://cloud.githubusercontent.com/assets/7660997/15400836/5367942c-1ded-11e6-8512-84b614453a56.png)

This can be symlinked to 
- `web-whatsapp`
- `whatsappfordesktop`
- `chrome-bgkodfmeijboinjdegggmkbkjfiagaan-Default`

**Comment by snwh** [comment]
Nothing uses `web-whatsapp`; the `web-[service]` is a naming scheme I decided to use in Moka and to symlink back to and everyone has copied it. :wink:

**Comment by bil-elmoussaoui** [comment]
I didn't knew that, just copied the symlinks from Numix theme :) Thanks for info!
