### ISSUE TITLE
Icon Request: Seafile

### ISSUE THREAD

**Issue by anaknaga** [snwh/paper-icon-theme#186]
- application name: seafile (seafile-client, seafile-client-qt5)
- Seafile is a popular cloud storage application, open source with ability to do client side encryption.
- seafile.png (non-scalable), seafile.svg (scalable)

![seafile](https://cloud.githubusercontent.com/assets/14137855/15441064/7518ed88-1ee1-11e6-898d-b6864bbe3489.jpg) (scalable icon)
![seafile](https://cloud.githubusercontent.com/assets/14137855/15441068/7af19282-1ee1-11e6-8d9f-5f6b2432203c.png) (non-scalable versions)

Seafile also has a different icon in the tray, but I haven't been able to find it. Perhaps hard coded. This is the icon when servers are online, the "V" is a "!" when they are offline.
![icon tray ok](https://cloud.githubusercontent.com/assets/14137855/15446316/85c641be-1f25-11e6-86ee-584918567ef3.jpg)

**Comment by snwh** [comment]
I think the "V" is a checkmark ;) If you find the filenames for the tray icon I'll include those too.

**Comment by bil-elmoussaoui** [comment]
@snwh Seafile is an other qt application that uses hardcoded tray icons..i've been trying to fix all of them, and here is a list of the icon names 
- [ ] seafile-status-paused
- [ ] seafile-status-syncing-1
- [ ] seafile-status-syncing-2
- [ ] seafile-status-error
- [ ] seafile-status-notification
- [ ] seafile-status-offline
- [ ] seafile-status-ok

**Comment by snwh** [comment]
If hardcoded, I'll leave it then.

**Comment by bil-elmoussaoui** [comment]
I don't use the application, but It's the same case as with Skype tray icons and they're in the icon theme. Is there any reason for that? :)
