### ISSUE TITLE
Tomahawk and Plulseaudio-Equalizer

### ISSUE THREAD

**Issue by DroWnThePoor** [snwh/paper-icon-theme#189]
- [x] Tomahawk `tomahawk.png/tomahawk.svg` [![tomahawk](https://cloud.githubusercontent.com/assets/16339020/15442687/b806512a-1eb0-11e6-987e-e7ee44d81c04.png)
] <br>
Note: Also gets a system tray icon:<br> [
![tomahawktray](https://cloud.githubusercontent.com/assets/16339020/15442750/04d5c1de-1eb1-11e6-956d-49f701cb5748.png) ]
- [x] Pulseaudio-Equalizer `preferences-desktop-sound (.svg)` [ 
![preferences-desktop-sound](https://cloud.githubusercontent.com/assets/16339020/15443721/8c8c6e8c-1eb8-11e6-8dd5-229e1715c705.png)]

===

**Comment by snwh** [comment]
Is the tray icon just the app icon?

**Comment by bil-elmoussaoui** [comment]
@snwh yes, but the icon is hardcoded (qt tray icons..) can you use `tomahawk-indicator` as an icon name for it? :)

**Comment by snwh** [comment]
`preferences-desktop-sound` is in the theme.
