### ISSUE TITLE
Battery symbolic icons are green

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-icon-theme#193]
After the latest update the battery symbolic icons on Gnome are now green
![capture d ecran de 2016-05-21 16-03-10](https://cloud.githubusercontent.com/assets/7660997/15448855/a111e638-1f6d-11e6-94f5-b9ca8fd58883.png)

**Comment by bil-elmoussaoui** [comment]
Edit : it's only the charging icon that have this issue

**Comment by snwh** [comment]
@bil-elmoussaoui yep, it's the full-charge state.

**Comment by bil-elmoussaoui** [comment]
So, it's by design and not a bug? :p

**Comment by snwh** [comment]
Correct. You can unplug your laptop now :P

**Comment by bil-elmoussaoui** [comment]
Alright, closing this then :+1:
