### ISSUE TITLE
Steam-Icon

### ISSUE THREAD

**Issue by DrCesar** [snwh/paper-icon-theme#194]
Request for Steam Icon

- Steam
- It's a gaming plataform developed by valve.
- `steam-icon.png`
![steam-icon](https://cloud.githubusercontent.com/assets/15188770/15449194/6943801c-1f3c-11e6-8423-14345e1e0a6d.png)

**Please attach an image of or the original icon file for reference.**

The paper theme and paper icons are freaking awesome.

**Comment by snwh** [comment]
There is a steam icon already in the theme, I'll just make a link to that one.
