### ISSUE TITLE
Icon request: Slack

### ISSUE THREAD

**Issue by mberneaud** [snwh/paper-icon-theme#195]
### Icon Request

- Slack
- Team communication software which aims to reduce the need for exchanging emails in small and medium-sized enterprises
- slack.png

*Note* : The icon for slack is stored in /usr/share/pixmaps by default
![slack](https://cloud.githubusercontent.com/assets/15064942/15449544/ef7881b6-1f80-11e6-8de5-7c07d899e6af.png)

**Comment by snwh** [comment]
I noticed Slack stopped using the paper icon.

**Comment by mberneaud** [comment]
Did you remove the slack icon from the respective `apps` folders? I can't find them among my items. I'm using the *Paper* version which you packaged around two days ago, by the way.

**Comment by snwh** [comment]
`web` is another apps folder

**Comment by snwh** [comment]
I use Slack as well, and a few updates ago it stopped placing the icon in `/usr/share/icons/` and points to a pixmaps version, which makes it exempt from icon themes.

**Comment by mberneaud** [comment]
Thanks. I'll just theme the icon myself then. Keep up the good work with the Paper icons and the cursors! Loving them!

**Comment by snwh** [comment]
You need only make it `Icon=slack` in it's desktop file. :)

**Comment by mberneaud** [comment]
Thanks for the tip! That sure beats using Nautilus to change the icons.
