### ISSUE TITLE
Icon Request: Blam

### ISSUE THREAD

**Issue by andwk** [snwh/paper-icon-theme#196]
### Icon Request
- Blam Feed Reader
- Simple RSS feed reader for Gnome.
- blam.png
![screenshot from 2016-05-21 11-30-49](https://cloud.githubusercontent.com/assets/17226294/15449625/63542cf4-1f48-11e6-9052-8b350d8d2aeb.png)

**Comment by snwh** [comment]
Would you be happy with a symlink to `internet-news-reader`?

**Comment by andwk** [comment]
Sure!

On May 31, 2016 6:54 PM, Sam Hewitt <notifications@github.com> wrote:Would you be happy with a symlink to internet-news-reader?
