### ISSUE TITLE
16x16 panel symbolic icons are dark whereas higher resolutions are light

### ISSUE THREAD

**Issue by helkaluin** [snwh/paper-icon-theme#197]
As titled.  This makes a thin panel (Xfce4-panel in my case) unusable as the icons are dark against a panel that is also dark (as per themed by the Paper GTK theme).

**Comment by snwh** [comment]
The 16x16 panel icons are meant for use in panel menus which are usually have white/light backgrounds, such as those of the Unity desktop, and are not intended for icons directly on the panel.

**Comment by snwh** [comment]
Does the XFCE panel not use the 22x22 or 24x24 icons for the panel?

**Comment by helkaluin** [comment]
Xfce-panel does use the 22x22 ones if you set the panel height to be at least 25px.

Of note is how only certain applets would use the 16x16 icons.  In my experience it's both Xfpm and ibus that would happily pick the 16x16 dark ones if I set my panel to below 25px height.

**Comment by snwh** [comment]
I can't really "fix" this as it would break the intended style for menus.
