### ISSUE TITLE
Incorrect dog-ear

### ISSUE THREAD

**Issue by adueppen** [snwh/paper-icon-theme#2]
In [preferences-desktop-wallpaper](https://github.com/snwh/paper-icon-theme/blob/master/src/bitmaps/apps/preferences-desktop-wallpaper.svg), the dog-ear page fold is not allowed to be on the upper-left of the icon. See [the guidelines](http://www.google.com/design/spec/style/icons.html) at the dog-ear section for details.

**Comment by snwh** [comment]
I have my own guidelines.

**Comment by snwh** [comment]
This theme is inspired by material it doesn't have nor is it possible to adhere 100% to the guidelines.

**Comment by adueppen** [comment]
OK, I guess.
