### ISSUE TITLE
full charge battery icon indication 

### ISSUE THREAD

**Issue by edwardally** [snwh/paper-icon-theme#204]
Hi,

After full charged the battery should be in white or dark grey?
![screenshot from 2016-05-23 10-26-55](https://cloud.githubusercontent.com/assets/1024003/15458831/5035f992-20d1-11e6-8eb2-d28f849ed01e.png)

**Comment by snwh** [comment]
Should be grey-white like the others. But it would depend on the the desktop/theme you're using.

**Comment by edwardally** [comment]
I'm using Paper theme and paper icon in Ubuntu 16.04

It looks ok in dash and login screen but not in desktop
![screenshot from 2016-05-27 10-22-08](https://cloud.githubusercontent.com/assets/1024003/15595844/fe8e66d4-23f4-11e6-96c1-50559b25ffa5.png)

**Comment by snwh** [comment]
this bug is a duplicate of #74

**Comment by edwardally** [comment]
Recent update the battery become big green battery icon... LOL  :)

![screenshot from 2016-06-01 09-19-24](https://cloud.githubusercontent.com/assets/1024003/15695496/561b29e4-27da-11e6-9e4c-a3d16877a6e4.png)

**Comment by snwh** [comment]
The green battery has been in there for awhile. ;)

I think it's because that indicator is the only one to use the `*-symbolic` battery icons which are 16x16 pixels so they get stretched.
