### ISSUE TITLE
Icon request : Gitter

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-icon-theme#206]
One of the missing icons on my desktop is Gitter
**Application name :**  Gitter
**Icon name :** `/opt/Gitter/linux64/logo.png`  maybe using `web-gitter`?
**Desktop file nam :**  `gitter.desktop`
**Default icon :** 
![logo](https://cloud.githubusercontent.com/assets/7660997/15487674/9e3ba46a-214f-11e6-9ee2-0c4018cc5134.png)

**Comment by azat-io** [comment]
So?
