### ISSUE TITLE
Lots of icon sizes are broken.

### ISSUE THREAD

**Issue by superscript18** [snwh/paper-icon-theme#21]
For example, https://github.com/snwh/paper-icon-theme/blob/master/Paper/96x96/apps/cheese.png, the Cheese icon is just a purple rectangle.  This seems like some bug in your building/rendering process.  All of the icons have at least one size that works and some look good on all resolutions, but many don't.

**Comment by snwh** [comment]
![screenshot from 2015-04-22 12 55 21](https://cloud.githubusercontent.com/assets/1217306/7280129/d9099c54-e8ee-11e4-84da-107058475260.png)

**Comment by meshy** [comment]
Is there something we can do to help?

**Comment by snwh** [comment]
Not particularly. I'm working on the theme, but the bloggers and such started writing about it way before it is finished. I had not much choice in "releasing" it after that.

**Comment by meshy** [comment]
Fair enough `:)` For what it's worth, it's working really well for me, and I'm really enjoying using it as it is. I managed to get the broken icon back to default just by deleting the one that wasn't as I wanted it.

There's no hurry. Take your time, and try not to feel the pressure. Sorry if I added to it. You've already done a great job. Thank you `:)`

**Comment by snwh** [comment]
No pressure at all, I'm going to continue to work on it at my own pace.

**Comment by meshy** [comment]
:+1:

**Comment by inifaisal** [comment]
please fix sublimetext icon..

**Comment by snwh** [comment]
Please have patience.
