### ISSUE TITLE
Place Icons

### ISSUE THREAD

**Issue by jmauss** [snwh/paper-icon-theme#210]
Currently, icons such as my home folder and my recent places folder have dark icons on my arc-dark theme in cinnamon. I know this was changed within the last week to gray, but has since gone back to black. Is there a way to revert back to the gray icons (as this affects the icon in the window bar as well)?

![clip](https://cloud.githubusercontent.com/assets/11668753/15540555/aedb9bb4-224d-11e6-9000-50ef0f7e7dfc.png)

**Comment by snwh** [comment]
I've been trying different 16px folder styles. I have to find a design that works on both light and dark themes.

**Comment by snwh** [comment]
I'm liable to change them again.
