### ISSUE TITLE
clementine and keepassx2 (maybe qt in general) action icon "search" not scaled right

### ISSUE THREAD

**Issue by johnnydvc** [snwh/paper-icon-theme#211]
- keepassx 2.0 
- search icon too big
- `search.png ???`

![bildschirmfoto vom 2016-05-25 17-44-39](https://cloud.githubusercontent.com/assets/4787052/15546475/61e3fe8e-22a0-11e6-9808-e9fa224cf03d.png)

- clementine 1.3.1 
- search icon and cloud-services icon too big
- `search.png ???`

![bildschirmfoto vom 2016-05-25 17-39-48](https://cloud.githubusercontent.com/assets/4787052/15546456/4d492ac6-22a0-11e6-9385-187c6b5521ac.png)

**Comment by snwh** [comment]
This is a problem that was reported below, for some reason, some (qt) apps are using the scaled (HiDPI @2x) version of icons instead of the normal ones, which are of course too large.
