### ISSUE TITLE
Numix Circle as base theme?

### ISSUE THREAD

**Issue by mank319** [snwh/paper-icon-theme#214]
I have added `Numix-Circle` to the list of inherited icon sets in the `index.theme` file. This works fairly well to "fill the gaps", since *Numix Circle* fits the overall look of *Paper* a lot better than the default Gnome icon theme *Adwaita*. The attached screenshot should demonstrate this.

If users do not have it installed it should not make a difference, as the theme will fall back to Adwaita (if I understood correctly how icon lookup works). In case you agree I would be happy to create a pull request :wink:

![paper-numix](https://cloud.githubusercontent.com/assets/3366745/15588804/eb40b088-238f-11e6-9d95-22b74e85418f.png)

**Comment by snwh** [comment]
Thanks, but I don't want to "fill the gaps" with unnecessary inheritances. I'd rather folks file issues about missing icons so that I can add them to Paper.  

Case in point, instead of telling me which icons are missing from Paper you're just using Numix –this doesn't help Paper grow. 

(and frankly, I don't much like Numix' design and I don't want the association)

**Comment by mank319** [comment]
I see your point and I respect your opinion. You are the author after all!

However, just to explain my "motivation", I would like to point out that coming up with this idea in the first place made Paper "usable" for me without having about 30% of my app icons look out of place (I am concerned about a consistent overall look and feel and Adwaita icons simply do not match Paper at all).

Don't take this personally, but I think Numix is so much older and maintained by multiple people which makes it very, very hard to match its level of completeness. I consider adding Numix Circle as potential base theme more like an "optional dependency" than an "unnecessary inheritance" (if people have it installed, it enhances their experience, but it is not required). I would not declare it as an actual dependency in the PPA, so users can choose whether they want to "fill the gaps" with Numix or not.

As a final suggestion, I would like to point out that you could add a single line in Paper's readme file about inserting the inheritance manually, so people know about the possibility of doing so and can decide for themselves.

I love the Paper theme and I am convinced it will grow and evolve, regardless of your decision on this matter - keep up the great work :+1:

**Comment by snwh** [comment]
Right, it takes quite some time to make a "complete" icon theme as I know from doing the thousands of Moka icons (which I started around the same time as Numix) and Paper is no different.

But I digress, my main point regarding my need for Paper users to *make requests* for missing icons still stands. So tell me what that missing 30% is :stuck_out_tongue:
