### ISSUE TITLE
Icon Request: Authy

### ISSUE THREAD

**Issue by ootaharuki99** [snwh/paper-icon-theme#218]
### Icon Request

- Authy
- Two-Factor Authentication from your PC
- `chrome-gaedmjdfmmahhbjefcbgaolhhanlaolb-Default`

![screenshot from 2016-05-28 00-32-04](https://cloud.githubusercontent.com/assets/18254610/15612947/e30acdae-246b-11e6-809b-f5183f6ed1b6.png)

**Comment by snwh** [comment]
this should be a quick one.
