### ISSUE TITLE
Switch buttons

### ISSUE THREAD

**Issue by 183amir** [snwh/paper-icon-theme#22]
The difference of color between on and off states of switch buttons are very low. I may be color blind :D but I can hardly distinguish between the two!
![paper](https://cloud.githubusercontent.com/assets/5738695/7277384/ad4a0d68-e94a-11e4-9937-3110095bb947.png)

**Comment by snwh** [comment]
Is a GTK theme issue not an icon theme issue and it has been resolved.

**Comment by 183amir** [comment]
I realized I posted it in a wrong place a bit later. Thank you for resolving it.
