### ISSUE TITLE
Icon Request: TeamViewer

### ISSUE THREAD

**Issue by gargullia** [snwh/paper-icon-theme#223]
### Icon Request

- TeamViewer
- Software remote support
- `teamviewer-teamviewer11.desktop`

![teamviewer-icon200x200](https://cloud.githubusercontent.com/assets/19420334/15637480/7d6834f8-2620-11e6-9e4e-f9171455ff6e.png)

**Comment by Narrat** [comment]
At least a svg is already there 
https://github.com/snwh/paper-icon-theme/blob/9283962bd441bef96fb2599936274b35f3adf98d/src/bitmaps/apps/teamviewer.svg

**Comment by snwh** [comment]
There is an icon in the theme: https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/teamviewer.png but it may be the case that Teamviewer uses a hardcoded icon.

@gargullia is `teamviewer-teamviewer11` the icon name used by the .desktop file?

**Comment by gargullia** [comment]
@snwh Yes
`[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=TeamViewer 11
Comment=TeamViewer Remote Control Application
Exec=/opt/teamviewer/tv_bin/script/teamviewer
Icon=/opt/teamviewer/tv_bin/desktop/teamviewer.png
Type=Application
Categories=Network;
#Categories=Network;RemoteAccess;`

**Comment by snwh** [comment]
@gargullia um, no it isn't. `Icon=/opt/teamviewer/tv_bin/desktop/teamviewer.png` means it can't be themed. Change it to `Icon=teamviewer`.
