### ISSUE TITLE
Add file studio.png for Android Studio

### ISSUE THREAD

**Issue by gargullia** [snwh/paper-icon-theme#225]
### Icon Request

- Android Studio
- `android-studio.desktop` line in desktop `"Icon=/opt/android-studio/bin/studio.png"`

![2016-05-30 16-31-28](https://cloud.githubusercontent.com/assets/19420334/15650822/fc53e79a-2683-11e6-8e99-ea59265a841d.png)

**Comment by snwh** [comment]
Because it's `Icon=/opt/android-studio/bin/studio.png` and not `Icon=studio` it won't be themed, but I'll make a link nonetheless.
