### ISSUE TITLE
Icon Request: Ubuntu Dash Icon

### ISSUE THREAD

**Issue by GreenTurtwig** [snwh/paper-icon-theme#227]
### Icon Request

Personally what I find is missing from my sidebar is the Ubuntu icon, it just looks out of place against all the other (cool) icons. :-)

- "Ubuntu Dash Icon"
- The icon used for the Ubuntu Dash
- `ubuntudash`

![](http://puu.sh/pay7s.png)  
  
Possible icons could be a white Ubuntu logo or something similar to the app drawer icon from the Google Now Launcher:  
![](http://icons.iconarchive.com/icons/dtafalonso/android-lollipop/512/Drawer-icon.png)  
![](https://lh5.googleusercontent.com/-_8hN4-7fvgU/Vbdsm_C38jI/AAAAAAAAe2U/vS6yloddXOAqgSOyPE3ljtb1oAoabfkEgCL0B/w746-h448-no/app-drawer.png)  
  
Personally I like the design of the one from CandyCons, but a white Ubuntu icon is probably a much better fit. :-)

**Comment by GreenTurtwig** [comment]
:smile_cat:

**Comment by snwh** [comment]
@GreenTurtwig that's your cue to close the issue. ;)

**Comment by GreenTurtwig** [comment]
Ah. :-P  
I was busy at the time so only briefly saw it. :cat:
