### ISSUE TITLE
error Icon cache generation

### ISSUE THREAD

**Issue by felipem775** [snwh/paper-icon-theme#232]
Today I updated from repo and get this message:

Setting up paper-icon-theme (1.3+r511~daily~ubuntu14.04.1) ...
gtk-update-icon-cache-3.0: **
Gtk:ERROR:/tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/updateiconcache.c:1117:write_bucket: assertion failed: (*offset == ftell (cache))
Aborted
WARNING: icon cache generation failed for /usr/share/icons/Paper

**Comment by snwh** [comment]
Hmm, this doesn't happen with `(1.3+r511~daily~ubuntu16.04.1)` –the same version but for 16.04.

**Comment by felipem775** [comment]
I use Linux Mint 17.3

**Comment by snwh** [comment]
@felipem775 which is based on..?

**Comment by felipem775** [comment]
14.04, i only added more info for help.
