### ISSUE TITLE
Evolution: Folder icons looking ugly

### ISSUE THREAD

**Issue by HeikoAdams** [snwh/paper-icon-theme#234]
When using latest git master and opening Evolution there are black folder icons (I guess that should be folders) but if you click on a folder the folder icon changes to a dark grey expanded folder icon.

I personally would prefer to use only the dark grey icons because i.e. nautilus uses dark grey folder icons too. Otherwise it would be inconsistent to have two different folder icons.

**Comment by snwh** [comment]
Related to #210

**Comment by snwh** [comment]
Could you provide a screenshot of this issue?

**Comment by HeikoAdams** [comment]
![bildschirmfoto von 2016-06-03 07-56-03](https://cloud.githubusercontent.com/assets/1418818/15770010/a6a8b16a-2960-11e6-9b78-6636ce7ab6a6.png)
