### ISSUE TITLE
Brightness missing

### ISSUE THREAD

**Issue by hadig** [snwh/paper-icon-theme#236]
Brightness and Lock Icon is missing in the settings.

![bildschirmfoto vom 2016-06-02 13-16-11](https://cloud.githubusercontent.com/assets/4592275/15743257/70f1cddc-28c4-11e6-95ab-17d03f2636d0.png)

**Comment by snwh** [comment]
Weird, since it's right here: https://github.com/snwh/paper-icon-theme/blob/master/Paper/48x48/apps/preferences-system-brightness-lock.png

**Comment by Nuvole9** [comment]
I try to change preferences-system-brightness-lock.png into system-lock-screen.png,and then it works well.I use Ubuntu 16.04 LTS.
