### ISSUE TITLE
FreeDesktop Completeness - Mimetypes

### ISSUE THREAD

**Issue by snwh** [snwh/paper-icon-theme#247]
Complete all these icons at all sizes for fd.o completeness

 - [x] application-x-executable
 - [x] audio-x-generic
 - [x] font-x-generic
 - [x] image-x-generic
 - [x] package-x-generic
 - [x] text-html
 - [x] text-x-generic
 - [x] text-x-generic-template
 - [x] text-x-script
 - [x] video-x-generic
 - [x] x-office-address-book
 - [x] x-office-calendar
 - [x] x-office-document
 - [x] x-office-presentation
 - [x] x-office-spreadsheet

**Comment by lexeii** [comment]
- [ ] application-x-generic  
(`application/*` MIME types; icon for "unknown": `application/octet-stream`)
- [ ] inode-x-generic  
(`inode/*` MIME types; fail-safe icon for blockdevices, chardevices, sockets... found in /dev)

These icons are **not** described [here](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html) or [here](https://cgit.freedesktop.org/xdg/shared-mime-info/), but they work in the same way like for other `*-x-generic` icons.

**Comment by snwh** [comment]
The priority will be those in the standard documentation.

**Comment by lexeii** [comment]
I understand — it looks like the hack :)
Thank you for your work!

**Comment by snwh** [comment]
@lexeii so `inode-x-generic` would be a hard disk icon?

**Comment by lexeii** [comment]
Hmm... Maybe something like "binary file" (sheet with ones and zeros on it)?

"inode-*" is for special files: (broken) symlinks, sockets, FIFOs, character and block devices. And "inode-x-generic" is icon that should fit all of them.

**Comment by snwh** [comment]
@lexeii I've not found the icon `inode-x-generic` in other themes.

**Comment by lexeii** [comment]
... but it could be in your theme indicating special files.

**Comment by bil-elmoussaoui** [comment]
@snwh This might help https://github.com/numixproject/numix-icon-theme/issues/936

**Comment by snwh** [comment]
@bil-elmoussaoui not much clearer.

**Comment by snwh** [comment]
@lexeii if you could re-file this as a separate issue and list the exact file names that would be great. I'm going to close this issue when I finish the original list as part of the milestone.

**Comment by lexeii** [comment]
Well, I will try to make some icons in question in the Paper style.

**Comment by snwh** [comment]
@lexeii you may, but I extremely-rarely accept user-made icons.
