### ISSUE TITLE
Mouse cursor is not shown in Tweak Tool

### ISSUE THREAD

**Issue by EldonMcGuinness** [snwh/paper-icon-theme#251]
Just noticed that this theme is supposed to come with a mouse/cursor theme, but it does not show as an option in the tweak tool. I used the PPA method of installation on Ubuntu-Gnome 16.04.

**Comment by snwh** [comment]
Eldon did you install `paper-cursor-theme`?

**Comment by EldonMcGuinness** [comment]
Cheers, that is exactly what was missing.
