### ISSUE TITLE
Mimetypes: R Scripts

### ISSUE THREAD

**Issue by mberneaud** [snwh/paper-icon-theme#258]
### Icon Request

- R mimetypes for R scripts and related files
- mimetypes for R scripts are currently missing in Paper Icon theme, since they are not included in any standard icon themes, I included the one from the Numix Icon theme for reference here. 
- `text-x-r.svg`
![text-x-r](https://cloud.githubusercontent.com/assets/15064942/15896971/d295fb8a-2d92-11e6-8dbc-0cda2c18d900.png)

### Multiple Requests

Below is a list of the symlinks which are included in the Numix Theme and which in my experience cover most of R's source files. 

- [x] First icon request `text-r.svg`
- [x] Second icon request `text-x-r.svg`
- [x] Third icon request `text-x-R.svg`
- [x] Fourth icon request `text-x-r-source.svg`

**Comment by snwh** [comment]
R you sure you want these?

**Comment by mberneaud** [comment]
I'm suRe. Thanks for the lightning-fast inclusion.
