### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by WantedFish** [snwh/paper-icon-theme#259]
### Icon Request

Onboard
Onboard settings
Sudoku
Mines
Xdiagnose
ImageMagick (display Q16)
Photos lens for Unity

**Comment by feskyde** [comment]
From README:

> # Missing Icons & Requests
>
> When filing an icon request or reporting a missing icon, please take care in providing the following
> useful information:
>
> - A screenshot of your issue or an image of the original icon you are requesting to be themed
> - The file name for the missing icon or the requested icon, for example `gimp.png` or `system-shutdown.svg`
> - A short description of the application or software that you are requesting an icon for.
>
> Note: some software ships hardcoded icons, meaning when you install icons are not placed in the
> system-wide directory `/usr/share/icons` which makes them unthemeable.

You're missing something...

**Comment by umayanga1** [comment]
I'm sorry.
Please try this icon theme on Ubuntu Gnome. Then you'll find these softwares without paper icons.
Please check this.
Thanks.

**Comment by umayanga1** [comment]
These softwares are comes with Ubuntu 16.04
Not installed by my.

**Comment by snwh** [comment]
@WantedFish @feskyde is pointing out you didn't follow my instructions. ;-)

**Comment by snwh** [comment]
Closing this for lack of information.
