### ISSUE TITLE
Stock Google Icons

### ISSUE THREAD

**Issue by 183amir** [snwh/paper-icon-theme#26]
IMHO, Empathy and Evolution's icons look very similar to Android icons and it just makes things confusing.

**Comment by snwh** [comment]
And? You're not using these icons on Android.

**Comment by 183amir** [comment]
Just imagine how much confusing it would be if these icons were similar:
![screenshot from 2015-05-11 23-39-01](https://cloud.githubusercontent.com/assets/5738695/7567336/5efe21b6-f837-11e4-8055-b98164e9368d.png)
I have installed Android version of Maps using Chrome in my system.

**Comment by snwh** [comment]
Wait, we can install Android apps using chrome?

**Comment by snwh** [comment]
The use case of people happening to be running Android apps in Chrome on their Linux desktop and using my theme is so narrow that it doesn't justify an icon change.

**Comment by 183amir** [comment]
That's not my reasoning. I just don't like seeing the same icon for two
different apps. Anyways, thanks for the awesome artwork.
