### ISSUE TITLE
battery, bluetooth and sidebar issue in elementary os freya

### ISSUE THREAD

**Issue by maqboolkhan** [snwh/paper-icon-theme#263]
`Battery` and `bluetooth` icon are bit large and looks really odd in `wingpanel`
here is the screenshot 

![battery and bluetooth](https://cloud.githubusercontent.com/assets/5022287/16041327/22d3935e-324e-11e6-8d58-3ac5658dcc07.png)

and other thing is in latest version of `paper` we have black icon for `Elementary's File` which does not look good as much as previous gray icon do 

![sidebar balck icon](https://cloud.githubusercontent.com/assets/5022287/16041401/872bec84-324e-11e6-8070-4da0d05bbcb1.png)
 
please put some option to change these icons to gray again 

thanks :)

**Comment by sdbcmh** [comment]
Also affects me

![paper_icons_bug](https://cloud.githubusercontent.com/assets/6020173/16270739/f76e67ec-385c-11e6-9ece-fcc4240e5992.png)

elementary OS 0.3.2 Freya (64-bit)

**Comment by maqboolkhan** [comment]
thanks for fixing @snwh  u r awesome :+1:

**Comment by maqboolkhan** [comment]
@snwh do we have gray sidebar icons option now?
