### ISSUE TITLE
Make Request

### ISSUE THREAD

**Issue by seventrust** [snwh/paper-icon-theme#266]
### Icon Request

If you are making an icon request please edit this template accordingly. If you have another issue, delete all this and carry on.

- application name
- short description
- `icon-file-name`

**Please attach an image of or the original icon file for reference.**

### Multiple Requests

If you are filing a request for many icons simulatenously please submit them in a checklist form.

- [ ] First icon request `filename` [Image of original]
- [ ] Second icon request `filename` [Image of original]
- [ ] and so on...

===

The details for the following can be found in an app's `.desktop` file found in `/usr/share/applications/` if you're unsure.

**Comment by snwh** [comment]
You've not actually filed any request here.
