### ISSUE TITLE
Icon not work

### ISSUE THREAD

**Issue by Roknauta** [snwh/paper-icon-theme#268]
I select the theme and it works but when I select the icon does not apply . What is happening?

**Comment by snwh** [comment]
You're going to have to be more specific.

**Comment by Roknauta** [comment]
When I click to apply Paper icons in my system, you are not applying. I'm using the Unity-TWEAT-tool.

**Comment by snwh** [comment]
Does running the following in a Terminal set the icon theme?

    gsettings set org.gnome.desktop.interface icon-theme "Paper"
