### ISSUE TITLE
Icon Request: gnome-terminal and sublime text 3

### ISSUE THREAD

**Issue by jyotishp** [snwh/paper-icon-theme#270]
There are icons already available in the package. But the icon names in `/usr/share/applications/*.desktop` have been changed as follows:

GNOME Terminal 3.18.3:
`ICON=utilities-terminal`

Sublime Text 3 Build 3114:
`ICON=sublime-text`

It would be great if you add aliases for the above icons.

**Comment by snwh** [comment]
Icons for both [`utilities-terminal`](https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/utilities-terminal.png) and [`sublime-text`](https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/sublime-text.png) have long been in theme. Which version of Paper are you using?

**Comment by jyotishp** [comment]
Oops sorry. Updated icons pack.

**Comment by snwh** [comment]
I don't know which version you had, both those icon have long been in Paper. :)

**Comment by jyotishp** [comment]
I manually compiled them from an old copy I had. Probably, would have lost some files while copying.
