### ISSUE TITLE
Bug with icon-cache

### ISSUE THREAD

**Issue by maxkoryukov** [snwh/paper-icon-theme#275]
I use Mint Cinnamon + Paper 1.3+r519

and I have a problem with creating `icon-cache` (it is a cheat with memory mapping: http://askubuntu.com/a/279794/400409): the `cache-generator` fails through caching process:

```shell
user@host /usr/share/icons/Paper $ sudo gtk-update-icon-cache --force /usr/share/icons/Paper
gtk-update-icon-cache: **
Gtk:ERROR:/build/gtk+2.0-KsZSEA/gtk+2.0-2.24.23/gtk/updateiconcache.c:1120:write_bucket: assertion failed: (*offset == ftell (cache))
```

System monitor shows, that `gtk-update-icon-cache` eats all available memory and then dies.

Could it be related to a large number of files in the Paper theme (comparing with X-Mint, or Adwaita for example)?

**Comment by snwh** [comment]
Related to #254

**Comment by snwh** [comment]
I'm guessing 14.04

**Comment by DroWnThePoor** [comment]
This is still affecting me on 14.04 LTS and eOs Freya. We have no workarounds? It literally makes me dread updating the Paper-Icon-Theme, because I know that my system will become unusable for a good 5 minutes.

**Comment by snwh** [comment]
@DroWnThePoor to be fair, this is the daily-builds PPA and it's prefaced with a warning. You can just download the theme as a deb and install it once. Often the updates are minor and won't be noticed by all users. When the icon theme is "stable" there will be a stable PPA that is updated less frequently.
