### ISSUE TITLE
Support for folder-color?

### ISSUE THREAD

**Issue by THPubs** [snwh/paper-icon-theme#277]
Any plans to support folder-color? (http://foldercolor.tuxfamily.org/)

**Comment by snwh** [comment]
No.

**Comment by snwh** [comment]
This isn't actually possible in Paper since it's a PNG icon theme. Folder Color can change icons that are SVG by editing the colour values within the SVG XML syntax.

**Comment by THPubs** [comment]
May i please know why? On Wed, Jun 22, 2016 at 10:50 PM, Sam Hewitt < notifications@github.com [notifications@github.com] > wrote:
No.

**Comment by THPubs** [comment]
Oh I got it thanks. Lets see whether they are willing to support png files. Have already asked them. On Wed, Jun 22, 2016 at 10:51 PM, Sam Hewitt < notifications@github.com [notifications@github.com] > wrote:
This isn't actually possible in Paper since it's a PNG icon theme. Folder Color can change icons that are SVG by editing the colour values within the SVG XML syntax.

**Comment by snwh** [comment]
Well, the PNG format doesn't have the same level of "editability" as SVG.

**Comment by bil-elmoussaoui** [comment]
Folder-color has some pre-defined colors. Must of those colors already
exists, just missing symlinks. But i dont know if the extension detects if
the custom colors can be used or not :)

**Comment by marksev1** [comment]
So how is it with the multiple colors are they available or not? Since I dislike the grey one you guys use, would like that light browner one that Faenza uses.

**Comment by snwh** [comment]
@marksev1 then you are free to use Faenza. I've made Paper the blue-grey colour since it is more neutral and fits into the rest of the Paper colour palette.

**Comment by marksev1** [comment]
I like the other icons better from your theme :). I'd just like various
folder color options to choose from.

2016-07-27 16:23 GMT+02:00 Sam Hewitt <notifications@github.com>:

**Comment by snwh** [comment]
@marksev1 you mean before the colour palette update? No matter which colour I choose there are always folks who will be dissatisfied with my choice. 😉

**Comment by marksev1** [comment]
Thats why it would be nice to have multiple options :) - see here folks
want the brown one https://forums.bunsenlabs.org/viewtopic.php?id=1200

2016-07-27 16:26 GMT+02:00 Sam Hewitt <notifications@github.com>:

**Comment by snwh** [comment]
@marksev1 I did that before in a previous theme and it was a mistake. It's simpler, for me, to be dictatorial.

**Comment by marksev1** [comment]
Could you maybe by any chance guide me how to do it :)?

2016-07-27 16:30 GMT+02:00 Sam Hewitt <notifications@github.com>:
