### ISSUE TITLE
[NOT AN ISSUE] Hope this is OK, but I have made an icon for you because I couldn't donate

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-icon-theme#28]
Since you have made this awesome theme and helped me with it earlier; I wanted to do something in return. I can't donate (don't have the money for it). So I made this deluge icon for you and for the theme. Hope it isn't to bad. and **if I posted this in the wrong place or whatever just remove this.**
![deluge](https://cloud.githubusercontent.com/assets/10121762/7668283/bf653c00-fc2f-11e4-84eb-b9f5302f4aad.png)

I also have a .xcf (GIMP) file for it but i don't know how to upload it  here.
EDIT:
here: https://drive.google.com/file/d/0BznJxbGXHt5GQ3RVRE0zZHJMUms/view?usp=sharing
This is now your's to keep, burn, trash, use, redesign, take elements from. or whatever you want to do with it.

P.S. You might want to tidy it up.

**Comment by axeopa** [comment]
)))))))))))))))))) kimamb is very talanted person !

**Comment by snwh** [comment]
Sorry, but this is definitely not on par with the quality of Paper's icons.

**Comment by Philip-Scott** [comment]
@kimamb If you want to start into theming icons, i recommend you look at Inkscape. Gimp is great at editing images, but for something like icons i recommend you use a vector imaging program so the edges will be crisp and clear no matter which resolution you use

**Comment by snwh** [comment]
It is possible to create icons with the GIMP, many icon themes from a few years ago were made in GIMP. But yes, learning Inkscape and vector graphics probably a better route.

**Comment by kimamb** [comment]
Thanks for all the answers (except axeopa if he is serius if he is sercastic than thanks to him to)

@snwh I'l try vector graphics.

Remember I did this for free. Nobody paid me, I just happened to need an icon myself so I shared it.

**Comment by aleksandar-todorovic** [comment]
> Remember I did this for free. Nobody paid me, I just happened to need an icon myself so I shared it.

Neither did @snwh for any of his works on the Paper Icon Theme and Gtk Theme as far as I know, but you won't see him emphasizing that. If you do something, you share it. If users love it, they will donate something to you as a sign of appreciation. That's just how open source works. Just don't get discouraged and continue improving. :wink:

**Comment by kimamb** [comment]
@aleksandar-todorovic I'm sorry, I did not mean to emphasize like that.

But if i make another one should I post it / post it here?
