### ISSUE TITLE
Dark icons don't go well with dark theme.

### ISSUE THREAD

**Issue by tristan957** [snwh/paper-icon-theme#280]
When using this theme in conjunction with a theme that uses dark colors, symbolic icons (Desktop, Documents, Home...) do not contrast well because they are dark. This also happens in the text editor. Is there a way to apply a light icon theme?
![screenshot from 2016-06-24 04-12-03](https://cloud.githubusercontent.com/assets/11936772/16348075/04829150-3a16-11e6-803e-bf7c5b639b5e.png)
![screenshot from 2016-06-24 04-13-44](https://cloud.githubusercontent.com/assets/11936772/16348082/0a1b15f6-3a16-11e6-9701-7ee2b3d8132a.png)

File Manager shown is Nemo. 
Text Editor shown is xed.

**Comment by lexeii** [comment]
@snwh 
Looks like symbolic icons must be colored the right way (`fill="#bebebe"` for the main color).
Then symbolic icons can be correctly auto-recolored for the light/dark themes.
This piece of info I've found in the [blog post](https://jonbrettdev.wordpress.com/2013/08/24/gtk-symbolic-icon-woes/).

Sorry, I can't test it now—looks like my custom GTK+3 installation (v. 3.14.8) is semi-broken, it not supported svg symbolic icons at all at the moment.

**Comment by snwh** [comment]
@lexeii the icons in question in this bug are not symbolic icons. (OP means symbolic in style).

**Comment by snwh** [comment]
@tristan957 yeah, they are not designed for use with a dark theme. This is a problem yet to be solved. FWIW, the toolbar icons are in the process of being made non-symbolic.

**Comment by bil-elmoussaoui** [comment]
@snwh why not providing a light & dark style of icons?

**Comment by snwh** [comment]
@bil-elmoussaoui because I don't want to.

**Comment by tristan957** [comment]
Damn. Ok thanks for the definition of symbolic. I'll be happily awaiting your solution in the meantime :)

**Comment by snwh** [comment]
There is a set of icons within the theme suffixed `-symbolic` (which are those @lexeii is describing) and there are others that are symbolic in style but don't have the adaptive properties of the `-symbolic` icons.

**Comment by lexeii** [comment]
@snwh 
I new to GTK+3, and I started to learn it mainly because Firefox switch to it.

BTW, reading sources, looks like info about `fill="#bebebe"` for symbolic icons is **wrong**. Keep using your `#555555`. From `gtk/encodesymbolic.c`:

- any `rect` or `path` is colored to `fg` color;
- classes `.warning`, `.error`, `.success` are colored to matching colors.

**Comment by snwh** [comment]
@lexeii correct. It doesn't matter what the primary fill of the SVG is. As you say, it just takes the foreground colour from a GTK theme and/or the colours of any class designations.
