### ISSUE TITLE
Rust MIME-Type icon isn't working

### ISSUE THREAD

**Issue by SShrike** [snwh/paper-icon-theme#281]
I believe this is because it's under `text-x-rust`, instead of just `text-rust`.

**Comment by palob** [comment]
What's your distro and what's your installed version of ``shared-mime-info``?

**Comment by SShrike** [comment]
Arch Linux, Gnome 3.20 w/ Rust filetypes shown as `text/rust`.

Note that the 'x' prefix is also deprecated: https://tools.ietf.org/html/rfc6648

**Comment by snwh** [comment]
That's the kind of thing that's easy to fix.

**Comment by SShrike** [comment]
It's working now, should I close this issue?

**Comment by snwh** [comment]
@SShrike usually how it goes ;)

**Comment by SShrike** [comment]
Sweet, thanks for the fix :+1:
