### ISSUE TITLE
Icon Request: GPaste (edit-paste)

### ISSUE THREAD

**Issue by postblue** [snwh/paper-icon-theme#287]
- GPaste
- GPaste is a clipboard management system ; it has a two `.desktop` files: one for the applet and one for the UI. The icon seems to be a scaled up tray icon.
- `edit-paste`, the icon is already provided but isn't well displayed in the application menu

![capture d ecran de 2016-06-28 16-10-31](https://cloud.githubusercontent.com/assets/696539/16419030/85ff92ee-3d4c-11e6-8394-a0720bba2628.png)

**Comment by snwh** [comment]
Related to #241

**Comment by snwh** [comment]
`edit-paste` is now in Paper

**Comment by postblue** [comment]
Nice, thank you!
