### ISSUE TITLE
Archive icon might be more obvious

### ISSUE THREAD

**Issue by tpimh** [snwh/paper-icon-theme#29]
The image that is used now does not really have anything about archive:
![package-x-generic](https://cloud.githubusercontent.com/assets/1071872/7769900/194bf820-0091-11e5-9d98-99566edb84e3.png)
Maybe it would better be like one of these?
![2015-05-22 14 42 50](https://cloud.githubusercontent.com/assets/1071872/7769927/448ad218-0091-11e5-8699-425e5b1ae28a.png)

**Comment by snwh** [comment]
That's one of the placeholder icons seen in an incomplete icon.

Here's the icon for archive at a smaller size: https://github.com/snwh/paper-icon-theme/blob/master/Paper/48x48/mimetypes/package-x-generic.png
