### ISSUE TITLE
Icon Request: MusicBrainz Picard

### ISSUE THREAD

**Issue by ootaharuki99** [snwh/paper-icon-theme#298]
### Icon Request

- MusicBrainz Picard
- Picard is a cross-platform music tagger written in Python.
- `picard`

![picard](http://picard.musicbrainz.org/static/img/picard-icon-large.svg)

**Comment by MichaelTiebesl** [comment]
Duplicate of #253

**Comment by ootaharuki99** [comment]
Sorry. I'll close this issue.
