### ISSUE TITLE
Icons unreadable in Google Chrome

### ISSUE THREAD

**Issue by marcogiannini** [snwh/paper-icon-theme#3]
Icons unreadable in Google Chrome

![schermata del 2015-01-29 15 46 03](https://cloud.githubusercontent.com/assets/4943897/5959460/c63f2e38-a7ce-11e4-8a09-ac382a530d3b.png)

**Comment by snwh** [comment]
Fixed, more or less.

**Comment by michel-slm** [comment]
@snwh the new iteration yields back and forward icons that look like the screenshot in #9 -- tested with the latest tarball available for download (SHA1 sum 9d4512b034ec38affee74e54b2f8901ae51065ed). back and forward button appears fine in otehr apps (e.g. Nautilus).

Using Ubuntu 14.04 and Chrome 41.0.2272.89

**Comment by michel-slm** [comment]
correction - SHA1 sum 6aa0a52bf0f353122a74a7fd4ff23744ca3f5560 . Should I open a separate bug?
![screenshot from 2015-03-11 17 32 38](https://cloud.githubusercontent.com/assets/85603/6594525/ab4f8a8a-c814-11e4-8ef8-dfb186f08265.png)
