### ISSUE TITLE
window button layout in "nautilus" only....

### ISSUE THREAD

**Issue by narutowindy** [snwh/paper-icon-theme#301]
![screenshot from 2016-07-05 10-26-03](https://cloud.githubusercontent.com/assets/18193527/16574298/11dee99c-429b-11e6-9fc6-97e4e061a0b8.png)

**Comment by snwh** [comment]
What's your issue here?

**Comment by lexeii** [comment]
Hmm, looks like some missing overlay icon above the third (green) button.

**Comment by snwh** [comment]
@lexeii which is? This theme may use a custom icon.

**Comment by lexeii** [comment]
Dunno... I just noticed. Sorry.
I newer used Nautilus and such RTL Apple-styled button layout (is third button for "close"?).
Maybe, the OP will make a screenshot with the standard theme to see the difference?

**Comment by snwh** [comment]
Right, it's likely to be an Apple-styled symbolic icon that's specific to this GTK theme. I'm not likely going to provide that in Paper.
