### ISSUE TITLE
Charles Proxy, Parcellite, Telegram

### ISSUE THREAD

**Issue by s-chizhik** [snwh/paper-icon-theme#302]
### Icon Request `Charles proxy`, `Parcellite`, `Telegram`
- [ ] Charles proxy (web debugging proxy), Icon=/usr/share/charles-proxy/icon/charles_icon128.png

![charles_icon128](https://cloud.githubusercontent.com/assets/5587936/16582441/9137f6cc-42b7-11e6-94e5-ff2975a66b75.png)
- [ ] Parcellite (Clipboard Manager), Icon=parcellite

![parcellite_comp](https://cloud.githubusercontent.com/assets/5587936/16582463/c5cb501e-42b7-11e6-95a2-f699d4fe23f5.jpg)
- [x] ~~Telegram (messaging app), Icon=telegram~~

![telegram](https://cloud.githubusercontent.com/assets/5587936/16582829/2e317dfc-42ba-11e6-9961-80a9fdd7798f.png)
# 

Also, programs has svg icons: [icons.tar.gz](https://github.com/snwh/paper-icon-theme/files/347613/icons.tar.gz)

**Comment by snwh** [comment]
Telegram is in the theme already.

**Comment by snwh** [comment]
Why (the hell) does that app have a picture of a jug for its icon.

**Comment by feskyde** [comment]
Charles Proxy and Parcellite icons are swapped

**Comment by s-chizhik** [comment]
@feskyde, fixed :)
@snwh, because of https://twitter.com/charlesproxy/status/5027481379

**Comment by snwh** [comment]
@s-chizhik haha, oh my.

**Comment by AlexWayfer** [comment]
I don't want create new issue, so write here because it's open :)

What about monochrome icon for Telegram in tray? As for Redshift (#60)

How it's now:
![image](https://cloud.githubusercontent.com/assets/6510020/18047679/c89fdeae-6de6-11e6-953c-288db74c8ba2.png)

Thank you.

**Comment by snwh** [comment]
@AlexWayfer that all depends on that extension using a symbolic icon.

**Comment by AlexWayfer** [comment]
@snwh But for Redshift it does.

And ok, there is without extension:
![image](https://cloud.githubusercontent.com/assets/6510020/18052063/f214237a-6e00-11e6-9dae-a371b71e102c.png)

**Comment by snwh** [comment]
@AlexWayfer but the redshift app has a different icon for the tray than it does for its app icon.

**Comment by AlexWayfer** [comment]
@snwh Okay, and you can not add monochrome icon for Telegram app in tray, yes?

**Comment by ElvisPresly** [comment]
Hidpi Ubuntu 16.04
![2017-08-23 19-11-40](https://user-images.githubusercontent.com/18265958/29626517-9cd2f07e-8837-11e7-887e-59a814f50256.png)
![2017-08-23 19-12-43](https://user-images.githubusercontent.com/18265958/29626518-9cea87fc-8837-11e7-8624-f9156d74ad39.png)
