### ISSUE TITLE
Brightness and Lock Icon Missing in System Settings - Ubuntu 16.04 

### ISSUE THREAD

**Issue by ethanmlinux** [snwh/paper-icon-theme#308]
When I open System Settings in Ubuntu 16.04 (Paper theme up to date as of Jul 8 2016 2:26 PM CDT), the icon for Brightness and Lock is missing. Here's a photo of the Settings window:

![screenshot from 2016-07-08 14-09-16](https://cloud.githubusercontent.com/assets/20361523/16699191/47bfb06c-4518-11e6-8be9-9d41fa7ff2e0.png)

My PC has the 64-bit edition of Ubuntu 16.04, which is up to date along with the Paper theme, and I am using using the Paper GTK, icon, and cursor themes.

Here's a photo of the .desktop file for Brightness and Lock. (The file name for the icon is system-lock-screen).

![image](https://cloud.githubusercontent.com/assets/20361523/16699911/9f7c7318-451c-11e6-81cd-ed74a681134b.png)

**Comment by snwh** [comment]
I'm not sure why this would be missing since there is a `system-lock-screen`icon in Paper

**Comment by ethanmlinux** [comment]
Maybe I'll try reinstalling Paper; I installed it through the repository.

**Comment by ethanmlinux** [comment]
I reinstalled Paper and it didn't affect the missing icon problem. I tried out my other icon packs and they showed that icon; I don't think there is anything I can do.

With Paper
![image](https://cloud.githubusercontent.com/assets/20361523/16744645/9cfb7f82-4777-11e6-8a36-eee134ae90a1.png)

With Papirus-gtk
![image](https://cloud.githubusercontent.com/assets/20361523/16744691/d57b7df8-4777-11e6-85c4-e26f7251f181.png)

**Comment by snwh** [comment]
It pains me to see Papirus.

**Comment by snwh** [comment]
Huh, seems I removed the icon awhile ago.

**Comment by ethanmlinux** [comment]
Oh, I'm sorry! I remember that article about it on OMG Ubuntu and how it uses some of your icons. Thanks for looking into it.

**Comment by snwh** [comment]
@ethanmlinux it's based on a version Paper back when it was incomplete, most of them are not Paper icons. :unamused:

**Comment by ethanmlinux** [comment]
I'm sorry about that.

**Comment by snwh** [comment]
It's mildly annoying.

**Comment by ethanmlinux** [comment]
Fixed now, thanks a lot!

**Comment by ethanmlinux** [comment]
Updating Paper right now. Maybe that will fix it.

**Comment by ethanmlinux** [comment]
Please tell me if anything happens. Thank you!

**Comment by jamesscholeyweb** [comment]
Any update to this? I am also having the same issue on 16.04.1LTS. I originally renamed /usr/share/icons/Paper/48x48/apps/preferences-sytem-brightness-lock.png to system-lock-screen.png as suggested in #236 and this work, but I just did a reinstall of my machine and this method is now not working and icon is missing again.

**Comment by ethanmlinux** [comment]
@jamesscholeyweb Thanks, I think I'll try that.

**Comment by jamesscholeyweb** [comment]
Ok here is the only way I can get the icon to show now

cd /usr/share/icons/Paper/48x48/apps
sudo cp preferences-system-brightness-lock.png system-lock-screen.png
sudo apt remove paper-icon-theme
sudo apt install paper-icon-theme

I am using the ppa for installation.

Apt remove leaves behind my system-lock-screen.png copy so I don't know if something is happening with that upon reinstall of icon theme. Does it build an icon cache or something including my file or something along those lines?

Anyway it seems like adding a copy of the icon named as system-lock-screen.png would fix this issue on 16.04.1 LTS

**Comment by EngineerGauravSharma** [comment]
goto      /usr/share/icons/Paper/scalable/apps/
download this attached zip 

[system-lock-screen.svg.zip](https://github.com/snwh/paper-icon-theme/files/424441/system-lock-screen.svg.zip)
and extract this zip you will get system-lock-screen.svg
put this svg file in  /usr/share/icons/Paper/scalable/apps/
then you are done now open system settings and check the brightness & lock icon

**Comment by PaulMarco** [comment]
I try **EngineerGauravSharma** suggest, but the file was corrupted. So I converted the icon _preferences-system-brightness-lock.png_ to svg and change the name to _system-lock-screen.svg_ and I put the svg file in /usr/share/icons/Paper/scalable/apps/, but the icon didn't appear on system settings. But after update the system with "Software Updater" (I don remember exactly, but to update were Numix and Adapta theme), the icon was on system settings.

So the solution is this: do that **EngineerGauravSharma** suggest and after update the system.

I attach again the file I used:
[system-lock-screen.svg.zip](https://github.com/snwh/paper-icon-theme/files/485300/system-lock-screen.svg.zip)

**Comment by EngineerGauravSharma** [comment]
Well this is working for me on Ubuntu 16.04.1.Even without updating anything.
________________________________

**Comment by snwh** [comment]
I've finally committed an icon for you all.

**Comment by jamesscholeyweb** [comment]
@snwh thanks Sam. Although I moved back to Arch since my initial issue where everything is working perfectly  :)

**Comment by snwh** [comment]
Yeah, we're dealing with patched things in Ubuntu.
