### ISSUE TITLE
[Icon Request] Vivaldi

### ISSUE THREAD

**Issue by mplemay** [snwh/paper-icon-theme#310]
- Program: Vivaldi
- Description: An new effecient and effective internet browser.
- Filename: vivaldi

![image](https://cloud.githubusercontent.com/assets/4324379/16720317/afa57a7a-46fa-11e6-88a1-3318cbffe0e3.png)

**Comment by snwh** [comment]
Vivaldi has a Paper icon.

**Comment by snwh** [comment]
https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/vivaldi.png
