### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Kukaikukai** [snwh/paper-icon-theme#311]
### Icon Request

- fcitx
- a replacement for ibus
- `fcitx`

![fcitx](https://cloud.githubusercontent.com/assets/19621292/16750715/4d301550-4806-11e6-9896-a896a8ac0f6f.png)

Thx a lot! Love your theme!

**Comment by Narrat** [comment]
There is already #161 and #119 asking for this

**Comment by snwh** [comment]
Yep, it's a dupe ;)
