### ISSUE TITLE
Many icons now broke after recent update

### ISSUE THREAD

**Issue by jmauss** [snwh/paper-icon-theme#313]
I recently updated the paper icon theme from the AUR and now, many of my icons that worked are now broken. This includes:

- Screen Lock (menu)
- Recent Files (menu)
- Extensions (settings)
- Applets (settings)
- Screensaver (settings)
- Window Tiling (settings)
- System Info (settings)
- Users and Groups (settings)

I am running Cinnamon on Arch Linux.

**Comment by snwh** [comment]
How recently? I've not made any major changes to Paper in awhile, and are you certain this isn't an update to Cinnamon that has broken this? Such as a change to icon names.

**Comment by jmauss** [comment]
Hm... that could have been it, I will have to look through Cinnamon commits. I was away from my computer on vacation, and after updating a batch of software it had changed. I cannot remember off the top of my head if Cinnamon was in there or not (although the arch packages page says it was last updated 6/1/16)

**Comment by snwh** [comment]
Cinnamon is historically unfriendly to icon themes, using non-standard icons and changing icon names randomly.

**Comment by Narrat** [comment]
@jmauss: Therefor exists /var/log/pacman.log ;)

**Comment by jmauss** [comment]
Regardless, I guess I am reporting that cinnamon had some changes that require some symlinks to be fixed.

**Comment by snwh** [comment]
@jmauss I would need a list of those new icon names to make said symlinks. You can simply update the issue accordingly.

**Comment by jmauss** [comment]
I am new to all of this, honestly, so I will begin looking through their commits(?) to see what I can find.

**Comment by jmauss** [comment]
Just an update, seems as though Cinnamon fixed their bugs and everything works again.

/Closed
