### ISSUE TITLE
Icon for Atom editor

### ISSUE THREAD

**Issue by nlaplante** [snwh/paper-icon-theme#32]
I think an icon for the [atom editor](http://atom.io) would be nice in this theme!

**Comment by voor** [comment]
There's an Atom package for a Material UI, at the site they provide the icon in various sizes:

https://atom.io/themes/atom-material-ui

Direct link to dropbox file: https://dl.dropboxusercontent.com/u/115930/Atom-MD-Icon.zip

**Comment by snwh** [comment]
Except Paper is not Material.

**Comment by nlaplante** [comment]
I don't think this should be closed solely based on the recommendation by @voor. This issue has been opened a while ago.

**Comment by snwh** [comment]
Habit.

**Comment by voor** [comment]
Apologies, I figured since it was inspired the icons would provide a good starting point. I don't think they provide a svg though.

**Comment by bil-elmoussaoui** [comment]
There's already an icon in Paper theme @snwh.

**Comment by snwh** [comment]
It was recently added, yes.
