### ISSUE TITLE
Icons don't follow guidelines and are inconsistent

### ISSUE THREAD

**Issue by jahirfiquitiva** [snwh/paper-icon-theme#320]
Hi

First of all, I want to say thank you for this set, because is the closest approach to having material design in Ubuntu, and I really like it.

Anyways, after seeing the icons [here](https://snwh.org/paper/icons), I can notice that they are not properly done, in terms of material design, and many of them differ in details like the tinted and shaded edges, which make them inconsistent.

I highly recommend reading [this guide](https://stories.uplabs.com/what-google-missed-in-their-guidelines-for-material-design-iconography-daf9f88000ec?gi=714fbe636050) which has all details about making proper material design icons.

(Really disappointed if you think "material design" are just guidelines not rules. I'm not saying they are rules but consistency and properly done icons, will make this theme completely material design, and the best one.)

I would really like to see the icons fixed in the future.

Thanks again for the theme and thanks for reading. Best of luck with the project.

**Comment by leskuore** [comment]
Paper != Material Design

**Comment by snwh** [comment]
@jahirfiquitiva this is not a Material design icon set
