### ISSUE TITLE
Gnome settings icons - sound, tablet

### ISSUE THREAD

**Issue by zeten30** [snwh/paper-icon-theme#33]
Hi, I think it will be nice to add sound and tablet icons, so GNOME control center will have a consistent look.
![gnome-control-center-papericons](https://cloud.githubusercontent.com/assets/1825873/8395805/d0971af6-1d87-11e5-8431-68142f45501a.png)
Regards
Milan Zink

**Comment by snwh** [comment]
No, I plan to leave it like this.

**Comment by snwh** [comment]
Of course it would "be nice" it takes time to make the icons that I don't always have. It's why the theme is called "alpha".

**Comment by bil-elmoussaoui** [comment]
this can be closed i guess @snwh 
![capture du 2015-11-29 20-47-07](https://cloud.githubusercontent.com/assets/7660997/11459600/646fa8da-96da-11e5-895d-11f2cacab728.png)

**Comment by snwh** [comment]
Bien sur.
