### ISSUE TITLE
Request to change notification icon in settings (Global Dark) 

### ISSUE THREAD

**Issue by Udara-U3** [snwh/paper-icon-theme#330]
With the Global Dark mood only can barely see **Notification icon in Settings**, Please update this icon.

![notification](https://cloud.githubusercontent.com/assets/12265797/17286240/59dd43f8-57d9-11e6-8348-8b66dd1e1637.jpg)

**Comment by El-Zipo** [comment]
What's this gtk+ theme?

**Comment by El-Zipo** [comment]
Is it Adapta?

**Comment by Udara-U3** [comment]
@El-Zipo Yeah it's Adapta

**Comment by El-Zipo** [comment]
@Udara-U3 
Hey, Are you a Sri Lankan?

**Comment by Udara-U3** [comment]
@El-Zipo Yes originally Sri Lankan :)

**Comment by snwh** [comment]
Um, no. Adapta is not my theme so I don't care if it's invisible on that.

**Comment by El-Zipo** [comment]
This is common for all dark themes.

**Comment by El-Zipo** [comment]
Having the same also in Paper gtk+ theme. (in dark variant)
![screenshot from 2016-08-02 17-08-44](https://cloud.githubusercontent.com/assets/19838220/17331595/3230db1a-58e9-11e6-9953-024c1c2b5f53.png)
Look at that **Notifications icon**
