### ISSUE TITLE
Icon for kodi

### ISSUE THREAD

**Issue by csteinforth** [snwh/paper-icon-theme#332]
### Icon Request

If you are making an icon request please edit this template accordingly. If you have another issue, delete all this and carry on.

- kodi
- Kodi is a media center formerly known as XBMC
- Kodi media center
![kodi](https://cloud.githubusercontent.com/assets/7705281/17376431/d35f062a-59b5-11e6-9cf6-c43db88d1457.png)

**Please attach an image of or the original icon file for reference.**

### Multiple Requests

If you are filing a request for many icons simulatenously please submit them in a checklist form.

- [ ] First icon request `filename` [Image of original]
- [ ] Second icon request `filename` [Image of original]
- [ ] and so on...

===

The details for the following can be found in an app's `.desktop` file found in `/usr/share/applications/` if you're unsure.

**Comment by feskyde** [comment]
It is the Paper icon

**Comment by csteinforth** [comment]
Arg....sorry!
