### ISSUE TITLE
Yellow Battery Icon

### ISSUE THREAD

**Issue by joerosato** [snwh/paper-icon-theme#335]
There appears to be no change to the yellow battery icon when I plugin my computer to charge the battery. What I think is occurring is that a plus sigh is appearing (I think) on top of the yellow icon but it is not visible. It would be nice to have a visible change so that I know my battery is still not draining.

**Comment by snwh** [comment]
A plus sign?

**Comment by joerosato** [comment]
![plugged](https://cloud.githubusercontent.com/assets/4511693/17639384/a05c0f82-60bf-11e6-9731-6715b3d26c20.png)
![unplugged](https://cloud.githubusercontent.com/assets/4511693/17639385/a05d4afa-60bf-11e6-9755-c28333602da6.png)

The top one is plugged in, the bottom not plugged in. Difficult to tell if I'm safe and not about to lose battery. Would be nice for something more visible.

**Comment by joerosato** [comment]
oh.. it is a lightning bolt not plus sign .. but still not too visible.

**Comment by snwh** [comment]
This in on Unity? The panel icons should be white, however your point about the lightening bolt is still valid.

**Comment by joerosato** [comment]
Yes Unity. Paper theme/icons/cursor.
