### ISSUE TITLE
[request] Evernote (Nixnote 2)

### ISSUE THREAD

**Issue by jhoward321** [snwh/paper-icon-theme#338]
### Icon Request

- NixNote2
- Linux client for evernote
- `/usr/share/nixnote2/images/windowIcon.png`

*Original icon*
![windowicon](https://cloud.githubusercontent.com/assets/5036794/17531606/aa0817a0-5e4a-11e6-8333-5462bb869fab.png)
*Evernote icon*
![evernote](https://cloud.githubusercontent.com/assets/5036794/17531660/dfdc0896-5e4a-11e6-8d84-3dfa3df1d769.png)

I think a version for the original evernote icon would be nice

**Comment by snwh** [comment]
Well considering how NixNote's icon is hardcoded, it wouldn't be themeable. A Paper version of an Evernote icon is within the realm of possibility

**Comment by jhoward321** [comment]
That'd be fantastic if there was a paper evernote icon. I have no problem manually changing my .desktop file
