### ISSUE TITLE
[request] qBittorrent

### ISSUE THREAD

**Issue by knight-corvi** [snwh/paper-icon-theme#339]
### Icon Request

- qBittorrent
- A client to download and share files over BitTorrent
- `qbittorrent`
- http://www.qbittorrent.org

![qbittorrent](https://cloud.githubusercontent.com/assets/3454040/17539701/290becf6-5e65-11e6-8019-a20c2adde204.png)

**Comment by snwh** [comment]
There is already a qbittorrent icon include in Paper: https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/qbittorrent.png
