### ISSUE TITLE
 Gdk-WARNING **: gdk_window_set_icon_list: icons too large

### ISSUE THREAD

**Issue by slackista** [snwh/paper-icon-theme#340]
When lunching geany editor I always have lot of warnings :

`Gdk-WARNING **: gdk_window_set_icon_list: icons too large`

EDIT:
same when lunching libreoffice

**Comment by snwh** [comment]
Seeing this in a Terminal?

**Comment by slackista** [comment]
Yes. Running Arch with Xfce.

**Comment by snwh** [comment]
Well this doesn't say anything about it being the fault of Paper. Would you do the same with another icon theme to check?

That being said, this is only a WARNING and not an ERROR, so it should be harmless.

**Comment by slackista** [comment]
Quick test icons from Arch Community repo:

faenza-icon-theme - no warnings
mate-icon-theme - no warnings
faenza-icon-theme - no warnings
elementary-icon-theme - no warnings
adwaita-icon-theme - no warnings

Is only quite annoying forking apps while working on terminal. Also .xsession-errors spawning unnecessary lines.

**Comment by snwh** [comment]
Well, there's not much I can do. `icons too large` is not a helpful error message. Paper has the same size icons as other themes.

**Comment by slackista** [comment]
Here is  GTK debug output after starting geany with Paper and with Gnome icon theme:
`$ GTK_DEBUG=icontheme geany`
[debug.tar.gz](https://github.com/snwh/paper-icon-theme/files/416746/debug.tar.gz)

Workaround:
In index.theme I removed all icons 512x512 .png and all *x*@2x and warnings.

**Comment by slackista** [comment]
Is there deliberate logic in your index.theme marking some svg icons as 'Fixed' and png as 'Scalable' ?

**Comment by snwh** [comment]
There is a logic. The 512x512 icons scale down to some sizes and some SVG icons are not meant to scale beyond the size they are at.

**Comment by snwh** [comment]
Since the "fix" would be removing all 512x512 icons this is a "Won't Fix".

**Comment by tristan957** [comment]
@snwh could this possibly related #398?

**Comment by hhhorb** [comment]
Removing all 512 icons WFM with Thunar in Debian stretch.

True that it's just a benign warning, but when the hell does a 512x512px icon get called by a theme or app?
