### ISSUE TITLE
Battery notification area Xfce - missing icon ac-adapter.png 

### ISSUE THREAD

**Issue by slackista** [snwh/paper-icon-theme#342]
On disconnected battery with AC plugged:
"Maximum icon size (px)" > 23
![yellow](https://cloud.githubusercontent.com/assets/20584264/17646007/bf4039b6-61b7-11e6-97da-f1c801ed0265.png)

On disconnected battery with AC plugged:
"Maximum icon size (px)" < 24
![good](https://cloud.githubusercontent.com/assets/20584264/17646008/c61599ac-61b7-11e6-8d0c-a64171ea66dd.png)

**Comment by snwh** [comment]
What is the name of this missing icon?

**Comment by slackista** [comment]
Sorry, isn't missing. Just need to remove  24x24/categories/xfpm-ac-adapter.png and now svg loads fine.

**Comment by snwh** [comment]
Hmm
