### ISSUE TITLE
Icon on spreading windows.  

### ISSUE THREAD

**Issue by vivekjib** [snwh/paper-icon-theme#347]
Whenever I spread all the windows, I see big icons that covers almost full app. You can see in image. I spotted this for terminal and gedit for now.

![screenshot from 2016-08-24 23-49-25](https://cloud.githubusercontent.com/assets/11706579/17944349/0604a38e-6a5d-11e6-833d-8ed83d267b86.png)

**Comment by snwh** [comment]
duplicate of #59

**Comment by vivekjib** [comment]
Is there anything I can do about it by myself ? Please let me know.

**Comment by snwh** [comment]
@vivekjib not sure.
