### ISSUE TITLE
[request] Zeal

### ISSUE THREAD

**Issue by wangxa** [snwh/paper-icon-theme#356]
- Application name: Zeal 
- Short description: Simple API documentation browser
- Home page: https://zealdocs.org/
- `Icon-file-name`:  
![zeal](https://cloud.githubusercontent.com/assets/1250269/18229563/c3a6f57a-7275-11e6-95bb-771a15535610.png)

**Comment by snwh** [comment]
I'm going to guess this icon is `zeal.png`

**Comment by wangxa** [comment]
Yes. It's zeal.png. Sorry I forgot to input the name.
