### ISSUE TITLE
Icons don't look right in clementine music player

### ISSUE THREAD

**Issue by gizzmoguy** [snwh/paper-icon-theme#357]
![screenshot from 2016-09-06 20-27-05](https://cloud.githubusercontent.com/assets/17055240/18295617/575d796c-744f-11e6-9b74-a843d9d2f198.png)

**Comment by esarandon** [comment]
Same issue here!

**Comment by snwh** [comment]
And same as #155 ;)

**Comment by esarandon** [comment]
you closed this issue and #155 without giving a solution!

**Comment by snwh** [comment]
This issue is a duplicate of #155

**Comment by snwh** [comment]
Seeing as I have no control over how the icons are displayed in a app, I can only make the assumption that the app is displaying something incorrectly.
