### ISSUE TITLE
Elementary OS Loki

### ISSUE THREAD

**Issue by ZSandyGhost** [snwh/paper-icon-theme#369]
Could you please update Paper icon pack for the elementary OS Loki? Including icons in new Mail app and other system icons. Thank you!

**Comment by snwh** [comment]
More specifically?

**Comment by ZSandyGhost** [comment]
For example volume icon is too big in Paper icon pack.
This is how it looks with default icons:

![screenshot](https://cloud.githubusercontent.com/assets/20601509/18504145/70765b5a-7a7e-11e6-93e5-a0ad0acc1cf5.jpeg)

and with Paper icons:

![screenshot1](https://cloud.githubusercontent.com/assets/20601509/18504229/dab83bdc-7a7e-11e6-9b8e-b704b8d97489.jpeg)

And the new notification indicator icon that's not available in Paper icon pack
![screenshot from 2016-09-14 13 25 01](https://cloud.githubusercontent.com/assets/20601509/18504481/11e0288a-7a80-11e6-99b3-3d9dfeab95e9.jpeg)

And here are the missing icons from default Mail app (pantheon-mail): [Not sure if this is too much to ask]
![screenshot from 2016-09-14 13 31 18](https://cloud.githubusercontent.com/assets/20601509/18504408/c246042a-7a7f-11e6-8f87-9702d6c120ef.jpeg)
![screenshot from 2016-09-14 13 31 46](https://cloud.githubusercontent.com/assets/20601509/18504409/c29eca06-7a7f-11e6-8db9-149b9e6439ca.jpeg)

**Comment by snwh** [comment]
Right, Mail has all those icons specific to it.

**Comment by snwh** [comment]
All but the Mail icons have been committed.
