### ISSUE TITLE
VirtualBox and VmWare icons

### ISSUE THREAD

**Issue by demas** [snwh/paper-icon-theme#37]
It will be good to add new icons for VirtualBox and VmWare as a current does not look pretty good. Thank you!

**Comment by snwh** [comment]
Please make your requests using this form: http://samuelhewitt.com/paper/icons/requests Thanks :)

**Comment by hex007** [comment]
404 on that requests urls

**Comment by snwh** [comment]
@hex007 oops wrong domain
