### ISSUE TITLE
Inaccurate Battery Icon

### ISSUE THREAD

**Issue by ipwnmice** [snwh/paper-icon-theme#377]
The battery icon is very inaccurate, especially at low levels

About 25% Battery
![pic](https://cloud.githubusercontent.com/assets/14303970/18697646/ceb1821c-7f88-11e6-970c-86e4bda0d7a8.png)

Same battery level with Adwaita
![pic](https://cloud.githubusercontent.com/assets/14303970/18697680/2365511c-7f89-11e6-9895-92cfc51781b7.png)

**Comment by snwh** [comment]
Well there are only 5 battery level icons –full, good, low, caution & empty– which don't show much nuance for the level of the battery and I only have so many pixels to express the levels.

**Comment by ipwnmice** [comment]
Even with battery down to 15%, the icon still shows 50%. The same icon is used from ~70% to ~15%.

**Comment by snwh** [comment]
Maybe something else is going on.

**Comment by snwh** [comment]
Found that the wrong icons had the wrong name in the theme.
