### ISSUE TITLE
Firefox icon

### ISSUE THREAD

**Issue by akabhirav** [snwh/paper-icon-theme#38]
Firefox icon looks unfinished.
![screenshot from 2015-08-11 17 21 50](https://cloud.githubusercontent.com/assets/5869630/9196937/c6821bc2-404d-11e5-8edc-9ebeb11ed87b.png)
As you can see the icon is not perfectly circular, feels like the edges are wavy.

Is this supposed to be right or is it just unfinished??

**Comment by snwh** [comment]
That appears to be Firefox using a differently sized icon than is being displayed. The Firefox icon is 'finished'.
