### ISSUE TITLE
Elementary OS Loki

### ISSUE THREAD

**Issue by ZSandyGhost** [snwh/paper-icon-theme#380]
Audio mute button missing 

with audio on

![screenshot from 2016-09-24 12 47 29](https://cloud.githubusercontent.com/assets/20601509/18806816/2b5718aa-8255-11e6-8d37-dbcf9a7bf98d.jpeg)

with audio muted

![screenshot from 2016-09-24 12 47 08](https://cloud.githubusercontent.com/assets/20601509/18806814/1e21f092-8255-11e6-82b7-402329f7eabf.jpeg)

**Comment by snwh** [comment]
I am also on Loki and said icon is present.

**Comment by lamebird** [comment]
its also happens on me whenever the audio is muted and rhythmbox is playing.
![screenshot from 2016-10-03 11 32 44](https://cloud.githubusercontent.com/assets/19585925/19027702/3183dca4-895d-11e6-8e10-254296dcfa62.png)

**Comment by snwh** [comment]
Which version of the theme do you guys have?

**Comment by snwh** [comment]
@knight-corvi it's not, there's just the mute icon.

**Comment by lamebird** [comment]
The volume muted icon it's supposed to changes when some application is playing audio while volume is muted. Maybe this will help you https://bugs.launchpad.net/wingpanel-indicator-sound/+bug/1462125

**Comment by snwh** [comment]
Ah, added it.
