### ISSUE TITLE
Many icons missing*

### ISSUE THREAD

**Issue by akabhirav** [snwh/paper-icon-theme#39]
List of some apps whose icons are missing.
Deluge
Synapse
Gimp Image editor
Libre Office apps
All or many web apps
Mime icons, i.e file type icons
Thanks

**Comment by snwh** [comment]
Yes, I've tried to as clear as possible that this theme is still under development and many icons are missing.

**Comment by sbaconnais** [comment]
Missing icons for gnome-contacts, gnome maps and california calendar.

Suggestions : 
https://commons.wikimedia.org/wiki/File:Flat_UI_-_calendar.png
https://commons.wikimedia.org/wiki/File:Flat_UI_-_map.png?uselang=fr

**Comment by snwh** [comment]
Those suggestions aren't up to Paper's (my) standards.

**Comment by akabhirav** [comment]
Was paper was made with a materialistic look in mind?

**Comment by ajthemacboy** [comment]
I hear what you're saying, it's still in beta, but here's a list of some missing icons on my system. Some of them are mainly 3rd party, but some like Rhythmbox are default in Ubuntu, etc.

Some more: 
qBitTorrent
Archive Manager
CompizConfig
WINE
Backups
Darkroom
GParted
Disk Usage Analyzer
Handbrake
Libre Office (suite)
Rhythmbox
Shotwell
Synaptic

**Comment by snwh** [comment]
Once I've completed the "core" icon set, I'll be moving on to all these third-party application icons.

**Comment by user501254** [comment]
@snwh has the development completely stalled? Or is it because of lack of time? I am asking since there have been no updates in the last few weeks, neither to the theme nor to the icon set.

**Comment by snwh** [comment]
Development is on hiatus or slow because I'm busy with life/work.

**Comment by user501254** [comment]
It's great to see some development, BTW I think that the download link within the `README.md` file is broken. Have a look at https://github.com/snwh/paper-icon-theme/pull/48.

**Comment by levdavid** [comment]
https://i.imgur.com/1RaviCs.png
popcorn time?

**Comment by snwh** [comment]
Closing this for lack of clarity
