### ISSUE TITLE
Make the Paper Icon theme Linux Mint 18 Cinnamon ready

### ISSUE THREAD

**Issue by erikdubois** [snwh/paper-icon-theme#391]
It would be a lot of work to type in all the missing icons and their names and all the info you require.

 Just install linux mint 18 cinnamon and you will see it for yourself.

I count 10 obvious icons missing but I have the feeling there are more icons that are shown but are not from paper but from the Mint system.

I hope you will make the time to help out the linux mint users. Most of this work WILL also help the mate, xcfe and kde Linux Mint users.

![paper](https://cloud.githubusercontent.com/assets/10594806/18942400/07b56f7e-8619-11e6-8766-897137638e01.gif)

**Comment by snwh** [comment]
Correct, it would be a lot of work but it's less work for someone whose using the system (where the icons are missing) presently I can't reasonably install all the apps or distros just to figure out all the icons that are missing.

FWIW, it's also a lot of work to make the icons, so I ask folks making requests to at least give me some minimal information to help me out.

**Comment by erikdubois** [comment]
Each and everyone works differently. I took the time to install 42 distro's, make the icons for the standard applications and moved on from there. Thank your for the reply. I hope some else will give you the information for these icons.
Thank you for your hard work and the beautiful icon theme.

**Comment by snwh** [comment]
Thanks, it also doesn't help me that Mint changes their icons' names each cycle.

**Comment by snwh** [comment]
Also, I looked into a few that you highlighted and they should have icons under Paper –like Gdebi and the Input app.

**Comment by erikdubois** [comment]
some of them can be easily fixed with a ln -s
but it will always be time-consuming
you decide what priorities you have
take care

**Comment by snwh** [comment]
@erikdubois alright, just for you I spun up Mint in a virtual machine to find these problem icons. ;)

**Comment by snwh** [comment]
That being said, some of the Mint app icons are unthemeable it seems, such as the Backup Tool.

**Comment by erikdubois** [comment]
Thanks the great linux nothing is unthemeable...
I use a script from foggalong
https://github.com/erikdubois/Ultimate-Linux-Mint-18-Cinnamon/blob/master/hardcodefixer-latest.sh
I provide him with all the hardcoded icons. I also posted a request from them to change the last two fixed path icons. Hoping next release will be super.

**Comment by snwh** [comment]
True, but hardcoded icons are of lower priority on my end since not everyone is aware of this problem.
