### ISSUE TITLE
[request] Gnome MultiWriter

### ISSUE THREAD

**Issue by chriptik** [snwh/paper-icon-theme#392]
Icon Request

Application name: MultiWriter
Short description: Write an ISO file to multiple USB devices at once
Icon-file-name: MultiWriter
![multiwriter](https://cloud.githubusercontent.com/assets/5763562/18968525/9b120e8a-8646-11e6-861d-3d3c9d15203a.png)

**Comment by bil-elmoussaoui** [comment]
duplicate of #159
