### ISSUE TITLE
Paper icon theme not showing up in Ubuntu Tweak

### ISSUE THREAD

**Issue by p-v-d-Veeken** [snwh/paper-icon-theme#394]
Hi, 

as I mentioned in the title, the Paper icon theme won't show up in Ubuntu Tweak for me. I've followed the installation instructions on: https://snwh.org/paper which didn't produce any errors. However when I open Ubuntu tweak, I can select 'Paper' for the Gtk, cursor and window theme, but not for the icon theme. 

I checked usr/share/icons and there is indeed a Paper folder. Furthermore, I stumbled upon this issue: https://github.com/snwh/paper-icon-theme/issues/71 but none of the solutions posted there work for me. 

I've purged and reinstalled the entire theme multiple times to no effect. 

My setup:
```
OS: Ubuntu 16.04 x86_64
Kernel: 4.4.0-38-generic
Uptime: 0:47
Window Manager: Compiz
Shell: Bash
Terminal: Xterm-256color
Packages: 1982
CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
```
Any help would be much appreciated!

**Comment by p-v-d-Veeken** [comment]
I have no idea what happened, but everything is working now.

**Comment by snwh** [comment]
:star2: magic
