### ISSUE TITLE
[Icon Request] GHex

### ISSUE THREAD

**Issue by MisteurTchaik** [snwh/paper-icon-theme#396]
### Icon Request

- [GHex](https://git.gnome.org/browse/ghex)
- Small binary/hexadecimal editor for the Gnome desktop
- `ghex.png`

![ghex](https://cloud.githubusercontent.com/assets/8634377/19021572/1234955c-88c5-11e6-95f7-4df99f249770.png)

**Comment by snwh** [comment]
Fun fact, I made the Ghex icon.

**Comment by MisteurTchaik** [comment]
Thanks!
