### ISSUE TITLE
Missing folder icon  in places folders

### ISSUE THREAD

**Issue by erikdubois** [snwh/paper-icon-theme#397]
### Icon Request

- application name = part of nemo
- short description = is in the menu of linux mint 18 cinnamon
- `icon-file-name` = folder-recent.svg or png
Take a look at the menu and you will see a blue folder with the text recent files after it.
I changed the inherits to follow the surfn icons. That means you are missing an icon which can be easily fixed.
![paper-github](https://cloud.githubusercontent.com/assets/10594806/19032685/98ff2eda-895b-11e6-84e5-9e276221a840.jpg)

Option 1
create a svg with the name folder-recent.svg or png and put it in all the dimensions folders in places folder - more work

Option 2
make a links like "ln -s folder.png folder-recent.png"
![folder-recent](https://cloud.githubusercontent.com/assets/10594806/19032827/376462ac-895c-11e6-8d74-7fcca2305abf.jpg)

![fixpaper](https://cloud.githubusercontent.com/assets/10594806/19032862/5d5dc3e0-895c-11e6-8ca1-294ccad5b29c.jpg)

Glad to give more info if needed.

**Comment by snwh** [comment]
I think you'll find there is a folder recent icon: [folder-recent](https://github.com/snwh/paper-icon-theme/blob/master/Paper/48x48/places/folder-recent.png)
