### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by akabhirav** [snwh/paper-icon-theme#40]
Progress bars in some apps such as deluge don't look so material, rather they look retro
![screenshot from 2015-08-11 17 35 46](https://cloud.githubusercontent.com/assets/5869630/9197155/85778ade-404f-11e5-8960-5b4ee1151fd1.png)

**Comment by snwh** [comment]
I think you mean to file this against https://github.com/snwh/paper-gtk-theme. 

Deluge is a GTK2 application which may not look the greatest to begin with under Paper.

**Comment by akabhirav** [comment]
sorry about that
