### ISSUE TITLE
[request] Museeq

### ISSUE THREAD

**Issue by pavethem** [snwh/paper-icon-theme#404]
### Icon Request

- application name: Museeq
- short description: frontend for the museek (soulseek) daemon
- `icon-file-name`: museeq.png

![museeq](https://cloud.githubusercontent.com/assets/847563/19151671/3b5017fc-8bce-11e6-9ab2-d16b24c39b0b.png)

Bonus: this application also has theming support that governs the tray icons etc.
I've uploaded the default theme here:
[default.zip](https://github.com/snwh/paper-icon-theme/files/513654/default.zip)
there's a lot of elements which would have to be replaced, but there's also themes which only replace certain elements like this:
[raven.zip](https://github.com/snwh/paper-icon-theme/files/513664/raven.zip)
If you want to create a paper theme for museeq, they're saved under /usr/share/museek/museeq/themes

**Comment by snwh** [comment]
I'm likely just going to make the app icon.
