### ISSUE TITLE
Network icon in LXPanel

### ISSUE THREAD

**Issue by juanmacio** [snwh/paper-icon-theme#412]
Hi Sam, thank you very much for your work.

I'm pointing an issue I have in the notification area in LXPanel, more precisly with the network icon. It doesn't seem to respect the color of the other icons no matter the theme I try.

Here's a screenshot: 
![screenshot](https://cloud.githubusercontent.com/assets/7716153/19215236/d7e9d53e-8d6e-11e6-8c68-c6a4f4cc7b30.png)

Any ideas why this is happening?
Thanks alot.

**Comment by snwh** [comment]
I suspect that the network applet is not using a symbolic icon, so it doesn't change according to a GTK theme. Also, fallback icons that are less than 16px are grey in paper. If you up the panel icon size (if that's possible) you'll get grey-white icons.

**Comment by juanmacio** [comment]
Yeah, changing the size corrects that. So looks like a problem with the applet ( ⌣̀_⌣́)
Cheers.
