### ISSUE TITLE
Theme makes some parts of the OS and apps unreadable

### ISSUE THREAD

**Issue by hakarune** [snwh/paper-icon-theme#43]
After applying the them I noticed that a few of the elementary apps and some other apps/settings areas are unreadable; they are white backgrounds with very light grey text making it extremely difficult to read, and nearly impossible for someone who is colorblind.

P.S. Is it supposed to enlarge everything like it does (i.e. screenshots, the size of app windows and the messages are all larger.

![screenshot from 2015-08-20 12 35 04](https://cloud.githubusercontent.com/assets/2251942/9393935/0c96018a-473a-11e5-94a2-2b23d045779a.png)
![screenshot from 2015-08-20 12 35 32](https://cloud.githubusercontent.com/assets/2251942/9393940/13491eea-473a-11e5-9481-7335c087bd86.png)

**Comment by bil-elmoussaoui** [comment]
@snwh it's the gtk theme issue not the icon theme?

**Comment by sunilchahal** [comment]
my battery icon is not visible when both icon and theme are active

**Comment by snwh** [comment]
It's not an icon theme bug.

**Comment by snwh** [comment]
If this is still an issue please file it against the [paper-gtk-theme](https://github.com/snwh/paper-gtk-theme/issues)
