### ISSUE TITLE
Paper panel icons on dark gtk themes are dark on a dark background

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/paper-icon-theme#431]
![bildschirmfoto vom 2016-10-21 14-34-02](https://cloud.githubusercontent.com/assets/15329494/19598624/107ec90e-979c-11e6-814e-a0c4c9501630.png)

As you can see, the Wifi and volume symbols are dark on a dark gtk theme and really hard to see.
It is no that important but it would be great if you would be able to fix this anyhow.

**Comment by snwh** [comment]
I could make them light, but then folks using light themes will file issues saying that they can't see the icons. Either way someone is left out. I made them dark since menus in the Paper GTK theme are light.
