### ISSUE TITLE
Icon appearance not updating.

### ISSUE THREAD

**Issue by baconinthemorn** [snwh/paper-icon-theme#438]
Hey there,

Running 16.04 and attempting to use the Unity-Tweak-Tool... however when I attempt to select/change the icon theme to "Paper" I see no visible change from the standard "Ubuntu-mono-dark" icons in the launcher.

I searched in existing issues and attempted to use a command you recommended to another user:

`gsettings set org.gnome.desktop.interface icon-theme "Paper"`

Again, no luck with this approach either =(... even as SU. The icon theme was working for me just fine until recently - however for the life of me I cannot discern what has changed to break it so thoroughly. Very new to Linux, so any insight you might have to restore the Paper icon theme would be great - the work you've done is fantastic - thank you regardless!

**Comment by snwh** [comment]
I'm not sure what would be going on here, all I can suggest is removing all trace of Paper and try reinstalling it.

**Comment by baconinthemorn** [comment]
Appreciate the feedback mate - ended up purging everything away and reinstalling... it didn't seem to make a difference at the time but just turned on my laptop today and the Paper theme is in full glorious effect!

Thanks a bunch Sam!

**Comment by snwh** [comment]
Okay then :)
