### ISSUE TITLE
GNOME Files uses fallback icon

### ISSUE THREAD

**Issue by a118n** [snwh/paper-icon-theme#439]
It seems that as of 3.22 GNOME Files (aka Nautilus) references the icon as `Icon=org.gnome.Nautilus` in `.desktop` file. Would be great to update the theme so that icon is in fact applied.

![screenshot from 2016-10-27 10-24-37](https://cloud.githubusercontent.com/assets/12648348/19758472/dffceaa6-9c30-11e6-97a8-4f257da9fe49.png)

**Comment by snwh** [comment]
Well since that icon is included, I think something else is at play here. Perhaps the sandboxing of apps extends to icons.

**Comment by a118n** [comment]
Are you sure it is included? I don't see `org.gnome.Nautilus` in the apps folder. Creating a simple symlink with this name fixes the issue.

![screenshot from 2016-10-28 12-27-21](https://cloud.githubusercontent.com/assets/12648348/19801969/0955c312-9d0a-11e6-8fbf-57f590be7eca.png)

**Comment by snwh** [comment]
@a118n perhaps you don't have the latest version, it is in the repo: https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/org.gnome.Nautilus.png

**Comment by a118n** [comment]
Yeah, you're right. Thanks. Closing it now :)
