### ISSUE TITLE
FreeCAD Icon

### ISSUE THREAD

**Issue by FoxBob79** [snwh/paper-icon-theme#441]
### Icon Request for FreeCAD

If you are making an icon request please edit this template accordingly. If you have another issue, delete all this and carry on.

- application name: FreeCAD
- short description: Open Source CAD Programm
- `icon-file-name`: /user/share/freecad-daily/freecad-icon*.png

**Please attach an image of or the original icon file for reference.**

![freecad-icon-64](https://cloud.githubusercontent.com/assets/8070840/19782456/30766e0a-9c8e-11e6-90e0-91707961cff2.png)

**Comment by snwh** [comment]
There is already a FreeCAD icon in Paper: https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/freecad.png –this must be a hardcoded app

**Comment by FoxBob79** [comment]
Oh, sorry!! But Thanks for your work!! :-)
