### ISSUE TITLE
SSH AskPass & PIM Setting Exporter Icons

### ISSUE THREAD

**Issue by tabakisp** [snwh/paper-icon-theme#444]
### Icon Request

I made a fresh install on Kubuntu with KDE5 and after installing `paper-icon-theme` I noticed that the following icon is missing from the Applications Menu/Launcher. 

- [ ] SSH AskPass
- A ssh-add helper that uses kwallet and kpassworddialog.
- icon-file-name: `ssh-askpass-gnome`
- ![ksshaskpass_ssh-askpass-gnome](https://cloud.githubusercontent.com/assets/7551798/19910065/70b49c0e-a093-11e6-9839-fe4ab5584c01.png)

*Thank you from the bottom of my heart for `Moka` and now `Paper`. Loved `Moka` since day1, then I discovered `paper-icon-theme` and seeing that they where made by the same person, :boom: I was stunned. Whole Paper pack is amazing. Thanks for everything.*

**Comment by feskyde** [comment]
The "PIM Setting Exporter" icon you are showing is not the Paper one?

**Comment by tabakisp** [comment]
@feskyde hmm you are right. The maintainers should add an `Icon=` in their .desktop file. Will edit. Thanks. 

*I really must stay away from the pc when sleepy lol*
