### ISSUE TITLE
[Improvement] More saturated icons

### ISSUE THREAD

**Issue by ajthemacboy** [snwh/paper-icon-theme#45]
Hello, I'm not a developer and I'm not great with Git, but I have saturated all the icons in Paper slightly to make them stand out more. 

I felt like the unsaturated icons were too colourless and not bold enough, so I wrote a script to saturate all of them. To me, it's an improvement.

I'm not entirely sure how to do this, but I forked the repo and uploaded my changes. Here is a link: https://github.com/ajthemacboy/paper-icon-theme

If you like them, I think they'd make a nice second version of Paper.

**Comment by snwh** [comment]
That is your opinion. I don't use an oversaturated colour palette as it would make all the icons look too bright (which your changes do).

**Comment by sagarpanchal** [comment]
@ajthemacboy It doesn't look as good as original icons. Original icons has balanced saturation. Your changes makes them very necessarily bright.
