### ISSUE TITLE
Bluetooth & power icons are still grey square

### ISSUE THREAD

**Issue by Jucgshu** [snwh/paper-icon-theme#451]
Hi guys,

The grey squares problem is still happening on my archlinux box, exactly the way it was on #9 & #418 

I installed & updated the icon pack from aur which is github related : https://aur.archlinux.org/packages/paper-icon-theme-git/ , tried to clean my icon cache multiple times with no success.

I did try to reopen the issue I opened last month, but it seems I can't do it.

Anyway, thanks for your work !

**Comment by Jucgshu** [comment]
Hi,

Figured out the problem appears when fonts have a 1.35 scale factor or superior in Gnome Tweak Tool. With 1.34 scale factor, the icons are fine.

-j

**Comment by snwh** [comment]
I'm glad it resolved itself.
