### ISSUE TITLE
Icon Request: JetBrains CLion

### ISSUE THREAD

**Issue by lakiluki1** [snwh/paper-icon-theme#452]
### Icon Request

- JetBrains CLion
- Icon=`clion`
![clion](https://cloud.githubusercontent.com/assets/15184862/20034086/7ae7c86e-a3b2-11e6-9b37-b68f59a11b9d.png)

**Comment by bil-elmoussaoui** [comment]
Duplicate of https://github.com/snwh/paper-icon-theme/issues/262
