### ISSUE TITLE
Please use 3x3 box grid instead of 4x3

### ISSUE THREAD

**Issue by fastrizwaan** [snwh/paper-icon-theme#46]
I love paper icons, but the show-applications icons or view grid symbolic icon looks unbalanced 3x4, the default 3x3 looks symmetric and consistent with paper icon themes.
![view-grid-symbolic symbolic](https://cloud.githubusercontent.com/assets/1161682/9733466/222f33e0-5649-11e5-9543-67e0fc22be0b.png)

Please consider using 3x3 view-grid icon which looks better with rest of the theme, than 3x4 which doesn't look good.

Thanks.

**Comment by fastrizwaan** [comment]
The request is only meant for the dash/dock icon.

**Comment by snwh** [comment]
3x4 is more representative of most application grids –none of which present app icons in a square/symmetric fashion.
