### ISSUE TITLE
Icons for Jetbrains IDEs

### ISSUE THREAD

**Issue by btd1337** [snwh/paper-icon-theme#464]
Icons for Jetbrains IDE's are missing.

Example of .desktop
icon=clion

IDE's:
clion
phpstorm
pycharm
intellij
webstorm
rubymine
appcode
datagrip
resharper
resharper-c++

All icons are avaliable here: https://www.jetbrains.com/products.html?fromMenu

**Comment by sonal-keshav** [comment]
This is a duplicate of: https://github.com/snwh/paper-icon-theme/issues/262

**Comment by snwh** [comment]
@sonal-keshav indeed it is.

**Comment by snwh** [comment]
@btd1337 if there are any missing from those listed in #262 feel free to add them as a comment.

**Comment by btd1337** [comment]
pycharm
rubymine
appcode
datagrip
resharper
resharper-c++
