### ISSUE TITLE
A new symbolic link to java.png

### ISSUE THREAD

**Issue by wangxa** [snwh/paper-icon-theme#468]
In Fedora 25, the OpenJDK's Java-1.8.0 contains two desktop files: `java-1.8.0-openjdk-1.8.0.111-3.b16.fc25.x86_64-policytool.desktop` and `java-1.8.0-openjdk-1.8.0.111-3.b16.fc25.x86_64-jconsole.desktop`. They use the icon named 'java-1.8.0'. 

So you may have to link `java-1.8.0.png` to `java.png`

**Comment by snwh** [comment]
Will do
