### ISSUE TITLE
Icon Request for Netbeans IDE

### ISSUE THREAD

**Issue by okierie** [snwh/paper-icon-theme#469]
### Icon Request
- Application : Netbeans
- Icon=`/usr/share/applications/netbeans-8.2.desktop`
- Original Icon:
![netbeans-6-5](https://cloud.githubusercontent.com/assets/5380347/21000518/f3f27588-bd4d-11e6-966b-abf5743c505c.png)

**Comment by snwh** [comment]
There is already a netbeans icon in Paper.

**Comment by okierie** [comment]
Oh, I'm sorry if it is already in icon pack.
But, my netbeans icon doesn't change. I'm using Ubuntu Gnome 16.04 with `gnome-shell` version `3.18.5` and the netbeans is 8.2. Does the version number affect the icons? or do I have to do some tweaks?

**Comment by snwh** [comment]
It's likely to do with netbeans itself. I suspect it's a hardcoded icons (i.e. the .desktop file points directly to a specific icon instead of referring to it generally). All you need to do is make it read `Icon=netbeans`.
