### ISSUE TITLE
Paper blue folder icon variation... for arc gtk theme?

### ISSUE THREAD

**Issue by fastrizwaan** [snwh/paper-icon-theme#47]
Hi,
arc is a beautiful gtk theme, and paper icons look good with it, but if folders were to be blue then they would look amazing with arc theme.
https://github.com/horst3180/Arc-theme

![screenshot from 2015-09-08 19-59-07](https://cloud.githubusercontent.com/assets/1161682/9737435/4b04127a-5664-11e5-96de-a3bf7f47e37f.png)

I used gimp to colorize the brown folder icons.

![screenshot from 2015-09-08 19-16-45](https://cloud.githubusercontent.com/assets/1161682/9737479/7ee07b42-5664-11e5-88ab-65459ca14e30.png)

Please consider a blue icon variant of paper theme. Thanks.

**Comment by snwh** [comment]
Seeing as I don't develop the Arc theme, I'm not inclined to make Paper match it. 

Also, I don't plan on making any colour variants –I made that mistake with my last theme; once there was one, everyone wanted a variant.
