### ISSUE TITLE
Paper repo issue / Fedora 25

### ISSUE THREAD

**Issue by haeringer** [snwh/paper-icon-theme#470]
The paper fedora repo at https://copr.fedorainfracloud.org/coprs/user501254/Paper/ provides directories for fedora 26 (not available yet), instead of current version 25.

**Comment by feskyde** [comment]
> This is an "unofficial" Copr repo for the Paper project.

Try to communicate with the repository creator, this has nothing to do here

**Comment by haeringer** [comment]
Ok, thanks for the hint. Found the original repo at http://download.opensuse.org/repositories/home:/snwh:/paper/

I'll contact the copr repo owner once the original repo is fedora 25 ready (just 24 yet).

**Comment by snwh** [comment]
I can update the OBS repos

**Comment by snwh** [comment]
Enabling Fedora 25 isn't available on OBS yet.

**Comment by snwh** [comment]
Repositories are now available for Fedora 25.
