### ISSUE TITLE
Directory/file renaming color issue

### ISSUE THREAD

**Issue by thedevsaddam** [snwh/paper-icon-theme#474]
### Icon Request

Please provide the following in your request:

- paper-icon-theme
- Icon=`not icon problem!`

When renaming a directory or file the text field background is white so the text can not be seen.
![screenshot from 2016-12-15 10-48-47](https://cloud.githubusercontent.com/assets/9676798/21212202/7f69e838-c2b4-11e6-8a42-7bbdb27b8115.png)

**Comment by feskyde** [comment]
This has nothing to do here, please post theme issues in the theme [repository](https://github.com/snwh/paper-gtk-theme).

**Comment by snwh** [comment]
What @feskyde said
