### ISSUE TITLE
Update Manager Icon

### ISSUE THREAD

**Issue by beatorizu** [snwh/paper-icon-theme#479]
### Icon Request

Please provide the following in your request:

- Update Manager
- Icon=`mintupdate`
- Insert/attach a copy of the original icon for reference

App's desktop file=`/usr/share/applications/mintupdate.desktop`

![screenshot at 2017-01-05 20-55-39](https://cloud.githubusercontent.com/assets/9607717/21700837/7fad8e36-d389-11e6-846f-49817d538d0d.png)

**Comment by snwh** [comment]
You can seee there's a link in the Paper set for MintUpdate, but that app does not take to being themed.
