### ISSUE TITLE
Mono-Dark Sound Icon

### ISSUE THREAD

**Issue by Ikazine** [snwh/paper-icon-theme#480]
The Sound icon in Linux Mint using the Mono-Dark theme is messed up.

Example of what the original paper icon shows:
![5ef17](https://cloud.githubusercontent.com/assets/23224476/21706928/384be09a-d390-11e6-936e-48f86fb08af3.png)

What the Paper-Mono-Dark icon shows:
![69678](https://cloud.githubusercontent.com/assets/23224476/21706939/4f28800c-d390-11e6-900a-eef75d5ea0b4.png)

It is smaller, and has a transparent box behind it.

**Comment by snwh** [comment]
Cinnamon/Mint uses the `*-symbolic` icons. The Mono icon set is mainly for Unity and XFCE.

**Comment by Ikazine** [comment]
Alright. Didn't know that.
Is there still a possibility for a fix? Few icons on cinnamon blend in with the background on Paper. Having a Paper-Mono-Dark for cinnamon would be appreciated and get rid of these problems. Please. Thank you.

**Comment by snwh** [comment]
Well that's not how it works in Cinnamon. Whatever your Cinnamon theme is dictates what colour the panel icons will me.
