### ISSUE TITLE
The theme considerably slows down Nemo, Mint Cinnamon's file manager

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [snwh/paper-icon-theme#488]
I thought there was a problem with Nemo. But it turned out (directly, at least) to be the paper theme. Even the mono version of the Paper icons slowed Nemo down a lot. Upon switching to one of Mint's default icon themes, things improved considerably. Hence, and with sadness, I feel I'll have to abandon Paper.

Mint 18. 1 x64 CInnamon
EDIT: I should perhaps add that I am using a latop that, whilst it has a SSD and 8GB of RAM, and a 4.8 version of the Linux kernel, does have very weak graphics and a sub-par (core2Duo) processor.

**Comment by enrigf** [comment]
@ACinnamonUserInUK Do you mean Nemo slows down when you hit the arrow keys?. If that is (was) your problem, the only thig you need to do is:

1. Open Nemo
2. Go to `Edit` menu and select `Plugins`
3. Disable `Nemo Emblems` and `ChangeColorFolder` plugins. 

Hope this helps.

**Comment by ACinnamonUserInUK** [comment]
> Do you mean Nemo slows down when you hit the arrow keys?

@enrigf, I am not sure that that was the problem. I have not had the problem for a while. But I do think the problem may have owed to Nemo plug-ins and indeed the problem may have been the particular plugin that you mentioned.

**Comment by snwh** [comment]
Yeah there's no an icon theme impacts performance since it doesn't execute any code.
