### ISSUE TITLE
Tweak tool icon is broken on the desktop

### ISSUE THREAD

**Issue by swarnendubiswas** [snwh/paper-icon-theme#50]
The tweak icon seems broken, but just for the desktop. The icon otherwise appears correctly from the shell overview or from /usr/share/applications. I have checked the .desktop files in ~/Desktop, ~/.local/share/applications/, and /usr/share/applications, and they all are consistent. Any ideas what could be wrong?
![screenshot from 2015-10-15 23-42-58](https://cloud.githubusercontent.com/assets/7343807/10533571/1ae912a0-7399-11e5-875c-8851c0df2f23.png)

**Comment by sagarpanchal** [comment]
@swarnendubiswas Icons are under development!

**Comment by sagarpanchal** [comment]
@swarnendubiswas https://github.com/snwh/paper-icon-theme/issues/39#issuecomment-129886377

**Comment by snwh** [comment]
Fixed in latest.
