### ISSUE TITLE
license of svg source files

### ISSUE THREAD

**Issue by pravi** [snwh/paper-icon-theme#51]
Even though README says its cc-by-sa, the source svg files have this line

<cc:license
           rdf:resource="http://creativecommons.org/licenses/by-nc-sa/3.0/" />

Can you clarify and correct the source files?

**Comment by snwh** [comment]
This is correct. The icon source files are Non-Commercial ShareAlike. The rendered icons themselves are ShareAlike; the main CC-by-SA License applies to everything, except where otherwise specified, such as in the source files.

**Comment by pravi** [comment]
Thanks for the clarification. This means it can't go to debian main :(

**Comment by pravi** [comment]
Can you consider changing it to cc by sa? This would make it Debian Free Software Guidelines compatible.

**Comment by snwh** [comment]
Simply exclude the icon source files. I don't intend the absolute source files to be distributed via packages, they are quite large and would inflate the size of a package.

**Comment by pravi** [comment]
We don't distribute the source in the binary package (that most users get), but we want to build from source in debian. Also we want source in the archive for all the binaries we distribute.

There was an interest from Hamara team to add missing icons if we chose Paper. Another option was to create a new icon theme. If the sources are not freely distributable under dfsg, we may chose the second option.

**Comment by snwh** [comment]
I see. All this license talk is rather moot, since Paper is incomplete anyway. I haven't finalized the icon design or Paper's guidelines which is why it's in an partially-done or stagnant state –there are design problems I haven't solved.

My suggestion to you is that's probably best to pick/create another theme.
