### ISSUE TITLE
Icon request - GNOME Builder

### ISSUE THREAD

**Issue by shailysangwan** [snwh/paper-icon-theme#513]
### Icon Request

- Application Name = GNOME Builder
- Icon = `org.gnome.Builder`
![image](https://cloud.githubusercontent.com/assets/22165016/23391484/585377b0-fd9b-11e6-91c5-1601e98c8ca8.png)

**Comment by tristan957** [comment]
There is already an icon for Builder as far as I know. My icon is definitely a paper icon. Check you /usr/share/applications and if you have an up to date paper theme it will have an icon

**Comment by tristan957** [comment]
![pasted image at 2017_03_19 02_22 pm](https://cloud.githubusercontent.com/assets/11936772/24083982/a61113a4-0caf-11e7-97b3-490488bb500d.png)

**Comment by shailysangwan** [comment]
Yeah, I see it there.
But my Builder installation on Fedora has `Icon=org.gnome.Builder`
I changed it to `Icon=builder` and it showed up.
Should something be done about this?

**Comment by tristan957** [comment]
Mine is org. gnome.Builder and I get the icon

**Comment by shailysangwan** [comment]
okay, should I close the issue?

**Comment by tristan957** [comment]
I would see if other Fedora users are experiencing the same thing first.

**Comment by snwh** [comment]
I just need to make a symlink. There is a `builder` icon but not a `org.gnome.Builder` icon.

**Comment by bil-elmoussaoui** [comment]
Already fixed
