### ISSUE TITLE
Icon Request: Gnome Power Statistics

### ISSUE THREAD

**Issue by vise890** [snwh/paper-icon-theme#523]
### Icon Request

- Application name

Gnome Power Statistics
> Gnome‘s Power Statistics  is provides stats  about your power usage (e.g. what is using it, how much, estimates, etc..)

- Icon=`org.gnome.PowerStats`

- Insert/attach a copy of the original icon for reference

![org gnome powerstats](https://cloud.githubusercontent.com/assets/1628760/23833122/96db530e-0741-11e7-9ada-36626892031c.png)

**Comment by bil-elmoussaoui** [comment]
Already fixed on master
