### ISSUE TITLE
Empty folder contextual menu is huge in elementary OS

### ISSUE THREAD

**Issue by bgcarlisle** [snwh/paper-icon-theme#527]
If I install the paper theme in elementary OS, then make a new folder, navigate to that empty folder and right-click, the contextual menu is way bigger than it's supposed to be.

My guess is because the "This Folder Is Empty" text is big, and maybe it's inheriting the font size from that?

**Comment by dscarfogliero** [comment]
I have the same issue.

![screenshot from 2017-03-27 21 26 45](https://cloud.githubusercontent.com/assets/26728504/24384745/1ec78c4e-1334-11e7-9798-74d6c0fe2639.png)

**Comment by snwh** [comment]
This issue is more relevant to the GTK Theme: https://github.com/snwh/paper-gtk-theme/issues
