### ISSUE TITLE
Icon Request: dbeaver

### ISSUE THREAD

**Issue by AndydeCleyre** [snwh/paper-icon-theme#53]
DBeaver is a relational database management application. Its upstream icon is the head of a beaver.

**Comment by elvisd** [comment]
Icon = dbeaver
Web site = http://dbeaver.jkiss.org/

Attached an example of actual icon
![beaver-head](https://cloud.githubusercontent.com/assets/307127/14675932/9ecedb62-070b-11e6-9939-b82a48686143.png)
