### ISSUE TITLE
Can't install on Ubuntu 17.04

### ISSUE THREAD

**Issue by USBA** [snwh/paper-icon-theme#534]
Please update the PPA.
Thanks.
![screenshot from 2017-03-24 07-56-50](https://cloud.githubusercontent.com/assets/19838220/24278093/8bbb1904-1039-11e7-9abe-7a7a8942b46f.png)

**Comment by richbl** [comment]
@USBA, until the ppa gets updated, you can do a manual install... very easy to do.

**Comment by PapayaMedia** [comment]
Exactly, I prefer to manual install it. I clone it and then create symbolic links to the icon themes folder from my home .icons folder. Then, like once a week, I go to the repo and execute `git pull` to keep it updated.

**Comment by USBA** [comment]
@richbl @PapayaMedia I also prefer manual installation. But I just check the ppa in ubuntu 17.04 daily build and it's not working. That's why I opened an issue. Thanks for replying me guys.

**Comment by snwh** [comment]
Updated PPA
