### ISSUE TITLE
Spotify icon request

### ISSUE THREAD

**Issue by konfiot** [snwh/paper-icon-theme#537]
Hello,
It seems that there aren't any paper icon for spotify, it woulb be nice if it could be added

- Application Name: Spotify
- Icon=`spotify-client`
![Icon Spotify](https://cloud.githubusercontent.com/assets/961690/24330069/3bcbc404-1217-11e7-946d-52148ea4c799.png)

**Comment by snwh** [comment]
[There is actually](https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/spotify.png) . It looks very similar to the actual icon though. ;)

**Comment by konfiot** [comment]
My bad, sorry

**Comment by snwh** [comment]
No worries
