### ISSUE TITLE
Here is list of Icons that I thoght and made that look like Paper icon theme

### ISSUE THREAD

**Issue by adiultra** [snwh/paper-icon-theme#54]
Here is a icon dump that i created for paper icons there are a few apps that you might have missed out. You can use these or make new ones from these.

![ppic](https://cloud.githubusercontent.com/assets/12121575/10994784/79e17cf0-849e-11e5-99ed-a2884aba82e5.png)

Here is the svg file:
https://mega.nz/#!MYZEGBTL

**Comment by akabhirav** [comment]
No, paper icons are kind of like material icons. They don't have borders or backgrounds. Like you did with audacity icon. Also the colors are more comic-like and no gradients.

But these are only my views, @snwh is the guy that decides.

P.S.
Synapse will have a icon not an alphabet.

**Comment by snwh** [comment]
@adiultra thanks for your attempts, but your icons (like @akabhirav more or less said) don't fit in with the design of Paper.

As for the missing icons, you'll have to be patient as it will take some time for me to get to many of them.
