### ISSUE TITLE
Icon Keepass (Symlink missing?)

### ISSUE THREAD

**Issue by root-github** [snwh/paper-icon-theme#541]
In my launcher menu the Paper Icon is displayed as it should but when the app is running it is the simple Keepass logo. The appearance also depends on wether I launch the app from the Firefox Add-On or through the launcher menu.

Paper Icon in launcher menu:
![keepass-](https://cloud.githubusercontent.com/assets/24967351/24538925/3b58def0-1616-11e7-996e-05641f57b932.png)

Keepass logo after launched from launcher menu:
![keepass_](https://cloud.githubusercontent.com/assets/24967351/24538967/6a030c9e-1616-11e7-9d7b-01e7c1544991.png)

Keepass logo after launched from Firefox:
![keepass](https://cloud.githubusercontent.com/assets/24967351/24538976/77e10e6a-1616-11e7-8f61-61072f3c75d8.png)

Is there a symlink missing or did I mess it up when installing the plugin? Any thoughts on this are appreciated.

**Comment by bil-elmoussaoui** [comment]
It's an upstream issue and has nothing to do with keepass. You can find out using xprop WM_CLASS and click on Keepass's window.

**Comment by root-github** [comment]
Thanks mate!
