### ISSUE TITLE
Totally invisible icon for 'Shutter' in the Mono Dark Theme

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [snwh/paper-icon-theme#547]
At least when using certain themes under the Cinnamon DE, the tray icon for the program 'Shutter' is totally invisible. Or rather that is the case when using Paper's Mono Dark theme. I fixed this by switching to the regular Paper theme. Suggestion: replace the Mono Dark theme icon with the Paper one.

- Application name: shutter
- Icon=various .desktop files for the program give only this: `Icon=shutter`

The icon's appearance under the **Mono Dark** theme:
![image](https://cloud.githubusercontent.com/assets/9998846/24858953/5fb62afa-1de6-11e7-9909-46ef9ba7944d.png)

The icon's appearance under the **Mono Dark** theme, _when the icon is under the pointer_:
![image](https://cloud.githubusercontent.com/assets/9998846/24859017/9d1fb5be-1de6-11e7-9466-bba60214886a.png)

The icon's appearance under the normal **Paper** theme:
![image](https://cloud.githubusercontent.com/assets/9998846/24859021/a33e4f1e-1de6-11e7-8668-19e410e33000.png)

**Comment by snwh** [comment]
The Mono-Dark theme is for themes with white/light panels.
