### ISSUE TITLE
No trash icon in PCManFM

### ISSUE THREAD

**Issue by ylecuyer** [snwh/paper-icon-theme#56]
There is no trash icon in PCManFM : 

![trash_not_showing_pcmanfm](https://cloud.githubusercontent.com/assets/1866809/11226875/0969d0a6-8d83-11e5-85b6-59ccf4df0f2a.png)

**Comment by ylecuyer** [comment]
Missing icon name is ```user-trash``` and ```user-trash-full```

**Comment by GrreenZ** [comment]
It's not missing - it's a white square on white background,
at least in Thunar (xfce) you can see it when you select it.

Icon lack of any contrast.

There is also very little difference between an empty trash and full...
