### ISSUE TITLE
Icon Request : JetBrains PhpStorm

### ISSUE THREAD

**Issue by Typhon0** [snwh/paper-icon-theme#567]
### Icon Request

- JetBrains PhpStorm
- Icon=`/opt/phpstorm/bin/phpstorm.png`
- Original icon : 
![phpstorm](https://cloud.githubusercontent.com/assets/10800948/26007715/6931ab54-374a-11e7-896f-96da53c08d14.png)

**Comment by jason-gu** [comment]
In case you need this:

[Desktop Entry]
Version=1.0
Type=Application
Name=PhpStorm
Icon=/path/to/PhpStorm/bin/phpstorm.png
Exec="/path/to/PhpStorm/bin/phpstorm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-phpstorm

**Comment by bil-elmoussaoui** [comment]
Duplicate of https://github.com/snwh/paper-icon-theme/issues/262
