### ISSUE TITLE
Grey folders in latest update

### ISSUE THREAD

**Issue by IzsakiRobi** [snwh/paper-icon-theme#57]
First! Thanks for your superb work.!
I donate you ;)
But latest update the folders color is ugly gray :(
This is bug? Or feature?
Please no colorize to grey....
Thanks!

I use 16.04 daily, gtk-3.18

rob

**Comment by motdef** [comment]
To my eyes the current colour makes regular directories not distinct enough from "special" items like the wastebasket, recent items, storage devices etc

**Comment by IzsakiRobi** [comment]
So is Feature? :|

**Comment by snwh** [comment]
No matter what colour I make the folders this will be a bug; I've had people take issue with the old brown colours saying more or less the same things.

I'm trying out this blue-grey colour scheme to see if I like it.

**Comment by IzsakiRobi** [comment]
Thanks the reply :)
I waiting final choice....
