### ISSUE TITLE
Bad icon map in Archlinux

### ISSUE THREAD

**Issue by Falbala44** [snwh/paper-icon-theme#570]
-Archlinux up to date
-Paper icon theme 545.e456a0d-1

1/ The main application is wrong, showing a gnome logo
![1](https://cloud.githubusercontent.com/assets/28715733/26077119/45b5aa86-39bb-11e7-8bf6-81879b2b8596.png)

2/ In the system menu the MATE icon should be the "Paper Mate" one (as in the "about mate" zone)
![2](https://cloud.githubusercontent.com/assets/28715733/26077118/45b4844e-39bb-11e7-98b6-46f75164ec43.png)

Thanks for this awesome theme

**Comment by snwh** [comment]
I don't control what icon appears in the panel menu or the about panel, sorry.
