### ISSUE TITLE
Few Paper-mono-dark icons lack in Gnome toolbar, which exist in normal pack

### ISSUE THREAD

**Issue by kirylpl** [snwh/paper-icon-theme#571]
There is a lack of Wifi and Battery icons in Paper mono dark, **which exist** in Paper pack.

Please check shots below:
![screenshot from 2017-05-17 08-32-03](https://cloud.githubusercontent.com/assets/3589618/26139748/765bf1c4-3adb-11e7-994e-4319c23d1936.png)
![screenshot from 2017-05-17 08-31-49](https://cloud.githubusercontent.com/assets/3589618/26139749/768c0904-3adb-11e7-8ccf-c14e3780c0a4.png)

**Comment by snwh** [comment]
Paper-Mono-Dark isn't meant for GNOME, it's for XFCE and such.
