### ISSUE TITLE
Link request: Transmission-remote-gtk, Yumex-dnf

### ISSUE THREAD

**Issue by lauhayden** [snwh/paper-icon-theme#574]
### Link Request

I might put together a pull request for this when I get around to it, but here are two symbolic links needed:
```
XXXxXXX/apps/transmission-remote-gtk.png -> transmission.png
XXXxXXX/apps/yumex-dnf.png -> system-software-install.png
```

**Comment by snwh** [comment]
These symlinks already exist :man_shrugging:
