### ISSUE TITLE
Size of Icons

### ISSUE THREAD

**Issue by The-Log** [snwh/paper-icon-theme#58]
If you change the size to be smaller, the icons being to look choppy. Here is how it looks when I change the size to 36 in the background settings.  Especially Chrome and Settings.
![example](https://cloud.githubusercontent.com/assets/7073919/11327240/d21bd5f8-914d-11e5-8101-f31bb92ec914.png)

**Comment by snwh** [comment]
Well of course they will, I don't provide a 36x36 icon size. Paper's icons aren't vector icons, I've designed them exactly for the standardized sizes for the desktop.  The issue here is that Unity does this silly smooth-resizing that will crunch down icons from the nearest icon size to fit.
