### ISSUE TITLE
Folder Color Support

### ISSUE THREAD

**Issue by alex285** [snwh/paper-icon-theme#586]
can we have foldercolor [1] support, so we can highlight some folders? it is the only reason i dont use Paper icon set, although i love it!

[1] http://foldercolor.tuxfamily.org/

image shows what this extension does in La Capitaine icon theme that supports it
![flat-plat-lacapitaine](https://user-images.githubusercontent.com/11244308/27091849-0a74a1a0-506a-11e7-9953-ac1fcd7758ed.png)

**Comment by snwh** [comment]
Not possible since my understanding of folder-colors is that it replaces an icon's colour in an SVG icon asset directly (which I frown upon) and Paper's icons are PNG (for quality reasons).

Coloured folder icons are shipped in Paper (e.g.[folder-red](https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/places/folder-red.png)), whether or not folder-colors can do anything with that I do not know.

**Comment by alex285** [comment]
@snwh  this is how it works
http://bazaar.launchpad.net/~costales/folder-color/trunk/view/head:/README

i will try to use it in Paper and see

**Comment by snwh** [comment]
@alex285 alright, I did some investigating. An pushed a possible fix to master if you want to test it.

**Comment by snwh** [comment]
It is only for normal folders, I'm not gonna make a coloured set of all the special home directory folders (at this time).

**Comment by alex285** [comment]
@snwh not working here, the "colors menu" doesnt pop up, does it work for you?

**Comment by bil-elmoussaoui** [comment]
Hey, The Folder color extension won't work as the icons extensions are hardcoded 
https://bazaar.launchpad.net/~costales/folder-color/trunk/view/head:/nautilus-extension/folder-color.py
just search for ".svg". I don't really understand why those extensions are needed anyway, but this should be reported upstream

**Comment by snwh** [comment]
Yeah I'm finding the same. This extension is rather crude, hardcoding extensions, asking for non-standard icons names. Closing as it's not "Paper should support Folder Colors", "Folder Colors should support Paper."

**Comment by bil-elmoussaoui** [comment]
@alex285 Already  porvided an easier way to do that 
![screenshot from 2017-06-13 18-43-58](https://user-images.githubusercontent.com/7660997/27093855-7a753eb2-5068-11e7-83e7-9ad06178466a.png)
![screenshot from 2017-06-13 18-44-14](https://user-images.githubusercontent.com/7660997/27093856-7a7846e8-5068-11e7-8f44-d4b25a94547c.png)

**Comment by snwh** [comment]
I've already filed a bug upstream on Folder Colors

**Comment by alex285** [comment]
@bil-elmoussaoui  oops i missed that! super! i'll try in a bit!
here for anyone else!
https://github.com/bil-elmoussaoui/nautilus-folder-icons

**Comment by snwh** [comment]
And suggested the dev account for icons of the name `folder-[color]` since those ship in many themes already to support KDE/Dolphin.

**Comment by costales** [comment]
Hi,
In version 0.0.80+ Paper should work by default :) Remember that you'll need to update Folder Color from the PPA ( +info here: foldercolor.tuxfamily.org )
Best regards.
