### ISSUE TITLE
Icons not scaled in window spread

### ISSUE THREAD

**Issue by Mowalle** [snwh/paper-icon-theme#59]
In default Ubuntu, if you install the `unity-tweak-tool`and enable to show icons during the window spread (`Super`+ `W`), it seems like the paper icons are not scaled to fit in the lower right corner,

How it should look (notice the small application icons in the lower right of the windows):

![Screenshot 1](http://i.imgur.com/a72WBBo.png)

How it currently looks with the paper theme:

![Screenshot 2](http://i.imgur.com/7bYy0eb.png)

Also, some of the icons turn white after while for some reason:

![Screenshot 3](http://i.imgur.com/1v3QB4l.png)

**Comment by snwh** [comment]
Well, I have no idea what's going on here. It's likely a bug in Unity and not in my theme. Do me a favour and try it with the GNOME icon theme and tell me what the result is.

**Comment by Mowalle** [comment]
Okay, so I tested this with several different icon themes again:

**Gnome**
![Gnome](https://i.imgur.com/tJ4jxan.png)

**Ubuntu-mono-dark (default in Ubuntu)**
![Ubuntu-mono-dark](http://i.imgur.com/7pumPI3.png)

**Ultra-flat**
![Ultra-flat](http://i.imgur.com/g5ZYt0D.png)

**Paper**
![Papr](http://i.imgur.com/7feIXpl.png)

So what I get from this is that this feature does not use the theme's standard application icon. For example, even though Sublime and Libre Office Writer are themed correctly in the dock, the window spread uses different icons. Sometimes they are missing entirely. This feature seems to have several bugs.

**Comment by snwh** [comment]
The Unity window overview uses a 64x64 icon, and when one isn't available it appears to use the next largest icon provided by the system, see Sublime Text and TEX. Since the next largest icon in paper is 512x512 pixels, that is why they're so huge.

I recommend filing this a a bug against Unity https://bugs.launchpad.net/unity
