### ISSUE TITLE
Remove folder_color_* icons

### ISSUE THREAD

**Issue by costales** [snwh/paper-icon-theme#594]
Hi,

Folder Color will work with just folder-<color> icons, then, if you want, you can remove from the repository the folder_color_* icons.

Best regards!

**Comment by snwh** [comment]
It's a handful of bytes and folks will probably still have older versions of folder colours. So no biggie.

**Comment by costales** [comment]
They will not be useful anyway, because they are .PNG.
Previous folder color extension was looking only for .SVG.
And new version doesn't needs them either.

**Comment by snwh** [comment]
This is also true. 😂
