### ISSUE TITLE
Need exactly 7 icons for software center and "Files" to appear

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-icon-theme#6]
I'm running Ubuntu GNOME. this is not a big issue but i'm only pointing it out

**Comment by snwh** [comment]
What do you mean?

**Comment by kimamb** [comment]
The dock thingy on the left in GNOME 3

**Comment by snwh** [comment]
You mean there are icons not included in the theme? Perhaps being more specific would help me out, otherwise this isn't a bug/issue that I can do anything about. ;)

**Comment by kimamb** [comment]
Look at the screenshots, the icons disappear when adding/removing icons, 7
is the magic number here.

2015-02-04 20:46 GMT+01:00 Sam Hewitt <notifications@github.com>:

**Comment by kimamb** [comment]
the same thing happens in unity if i shrink the taskbar

**Comment by snwh** [comment]
It's simply because some of the icon size variations are incomplete, hence the squares.

**Comment by kimamb** [comment]
OK, thanks for the quick response[?]. I'l just wait then.

2015-02-04 21:03 GMT+01:00 Sam Hewitt <notifications@github.com>:

**Comment by snwh** [comment]
That was one the big disclaimers I had on the web page. ;)
