### ISSUE TITLE
redshift icon

### ISSUE THREAD

**Issue by towo** [snwh/paper-icon-theme#60]
An icon for the great [Redshift](http://jonls.dk/redshift/) would be greatly appreciated.

I'd easily settle for a temporary monochrome icon for the indicator, though.

**Comment by omichalek** [comment]
yes please, eg. an icon of a bulb would be great!

**Comment by omichalek** [comment]
thank you for making it! The icon feels quite railway themed to me :)

**Comment by snwh** [comment]
@omichalek railway?

**Comment by omichalek** [comment]
Looks little bit like a face of train
http://condrenrails.com/Frisco/West-Shops/SLSF-1018=4-6-2=1-700.jpg

And it reminded me also of this hand sign that Czech railway crew use in
stations (possibly not anymore)
http://1gr.cz/fotky/idnes/14/051/cl6/KHR52efa4_vypravci.jpg
