### ISSUE TITLE
Export to svg?

### ISSUE THREAD

**Issue by khurshid-alam** [snwh/paper-icon-theme#613]
Hi,
Is it possible to modify `src/render_bitmaps.py` so that it can output svgs instead of pngs? Can you point me to the right direction.

Thanks.

**Comment by khurshid-alam** [comment]
@snwh ?

**Comment by snwh** [comment]
It’s not. Inkscape doesn’t export to SVG from the command line.

**Comment by khurshid-alam** [comment]
@snwh I know that. But I am asking if there is another way to export svgs. Even a pipe command will do like `cat svg-stream > filename.svg`. But I don't know the svg-stream since they are stacked together.

**Comment by snwh** [comment]
@khurshid-alam there's no simple method I'm aware of, it can be done but you'd have heavily modify the SVG to be able to be read by a given script.
