### ISSUE TITLE
Please add more icon packs for different type of files.

### ISSUE THREAD

**Issue by sanjaypra555** [snwh/paper-icon-theme#614]
# **Icon Request**

**Paper Icon Pack**
![paper](https://user-images.githubusercontent.com/18235954/30514191-e8faa01a-9b2d-11e7-9038-333e7fa3251f.png)

**Papirus Icon Pack**
![epapirus](https://user-images.githubusercontent.com/18235954/30514197-f0c8a45e-9b2d-11e7-905f-26436afb8ac1.png)

Please add more icon pack for different type of files like database file. In papirus icon pack there are many icon for different type of files.Can you please add more icon packs like papirus ?

**Comment by snwh** [comment]
I could but it seems Papirus has you covered and they copied (literally) the design of my icon set.

**Comment by Secret-chest** [comment]
> I could but it seems Papirus has you covered and they copied (literally) the design of my icon set.

@snwh Just so you now, Papirus is much worse.
