### ISSUE TITLE
regarding Copr repo for fedora

### ISSUE THREAD

**Issue by user501254** [snwh/paper-icon-theme#62]
I recently made a [Copr repo](https://copr.fedoraproject.org/coprs/user501254/Paper) for Fedora and CentOS using the `paper-icon-theme.spec` file that was added to the project a few days ago.

It would be nice if you could just have a look at it. 
Also if you intend to push out your own repos for these distributions anytime soon, please let me know so that I can delete mine.

The recent updates are really nice, thanks.

**Comment by snwh** [comment]
I was doing the same, but my builds were failing. ;) https://copr.fedoraproject.org/coprs/snwh/paper-icon-theme/

**Comment by user501254** [comment]
I tried on a local machine first which failed at the first attempt. I had to rename the tarball in order to get it working.
see: https://github.com/snwh/paper-icon-theme/pull/63

**Comment by user501254** [comment]
@snwh any updates on the issue?

**Comment by snwh** [comment]
I'm not using src.rpms. Ideally I want it as automated as possible, I don't want to manually build packages all the time –why I'm trying to get it working with git.

**Comment by user501254** [comment]
That is possible with Copr but requires some additional work, will try building using my Git fork later today. You can take it from there on.

**Comment by user501254** [comment]
Using [tito](https://github.com/dgoodwin/tito) and [copr-cli](https://apps.fedoraproject.org/packages/copr-cli) I was somewhat able to automate the process. The process still creates the the src.rpm file locally but it is automatically uploaded to Copr.

**Comment by user501254** [comment]
I came up with this: https://github.com/user501254/packaging/tree/master/paper
Works fine on most occasions.
