### ISSUE TITLE
[Question] Cinnamon thumbnail images with your Paper Icon Theme

### ISSUE THREAD

**Issue by tista500** [snwh/paper-icon-theme#627]
Hi, snwh.

I'm an author of Adapta-gtk-theme.
Then I have a question about a COPYING: https://github.com/snwh/paper-icon-theme#copying-or-reusing
Now I'm thinking to capture actual desktop thumbnails with your Paper icon theme to bundle those thumbnails in our Adapta-gtk-theme like this:
![screenshot from 2017-11-14 08-48-23](https://user-images.githubusercontent.com/6073622/32757276-15c10068-c922-11e7-82c6-71658771315f.png)

So is it enough by adding your credit to our README.md like this? :
```diff
diff --git a/README.md b/README.md
index cfe6bb98..f3f9f641 100644
--- a/README.md
+++ b/README.md
@@ -344,6 +344,9 @@ Public License
  > **Note:**
  >
  > SVG files are licensed under CC BY-SA 4.0
+ > And an icon-theme in Cinnamon thumbnails is :
+ > [**Paper Icons**](http://snwh.org/paper/icons) by Sam Hewitt is licensed under CC-SA-4.0
+
 ```

I look forward to hearing from you... :)
Best Regards.

**Comment by snwh** [comment]
Screenshots are fair use, you needn't credit me for those. It's only if you take and reuse assets directly, that crediting is necessary. :)

**Comment by tista500** [comment]
Thanks. ;)
