### ISSUE TITLE
[Feature Request] Add the Papirus icon set as fallback

### ISSUE THREAD

**Issue by georgelemental** [snwh/paper-icon-theme#655]
The [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) looks quite similar to Paper (as it literally copied the theme). Paper looks better (at least in my opinion), but Papirus has better coverage. Adding Papirus as a fallback icon theme on the `Inherits` line in the [index.theme file](https://github.com/snwh/paper-icon-theme/blob/master/Paper/index.theme) would get the best of both worlds (Paper's more beautiful icons and Papirus' larger icon set).

**Comment by snwh** [comment]
Absolutely not.
