### ISSUE TITLE
eclipse icon request

### ISSUE THREAD

**Issue by elvisd** [snwh/paper-icon-theme#66]
Icon request for eclipse IDE

**Comment by elvisd** [comment]
Inserted in official request form too.

**Comment by snwh** [comment]
There's an eclipse icon in there. https://github.com/snwh/paper-icon-theme/blob/master/Paper/512x512/apps/eclipse.png

**Comment by snwh** [comment]
It's possible that eclipse's ```.desktop``` file refers to a hardcoded icon.

**Comment by elvisd** [comment]
Ok, works!
