### ISSUE TITLE
Poweroff Button Icon missing on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by AndrewDi** [snwh/paper-icon-theme#667]
### Icon Request

Poweroff Button Icon missing on Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/7589147/40769331-49bd54ca-64ea-11e8-9a2b-891c5dd50011.png)

**Comment by bwat47** [comment]
in tweak tool select 'paper' as the icon theme instead of 'paper mono dark' and that will fix it

**Comment by AndrewDi** [comment]
Thanks，that works for me
