### ISSUE TITLE
Cannot build from ppa

### ISSUE THREAD

**Issue by phxhuy** [snwh/paper-icon-theme#674]
Hi, I am using Linux Ubuntu 16.04. I tried to install from PPA using the following command:
sudo add-apt-repository -u ppa:snwh/ppa
sudo apt-get update
sudo apt-get install paper-icon-theme

But it was unsuccessful. I had the following error:

sudo apt-get install paper-icon-theme paper-gtk-theme
Reading package lists... Done
Building dependency tree       
Reading state information... Done
paper-icon-theme is already the newest version (1.5.716-201806100126~daily~ubuntu16.04.1).
paper-gtk-theme is already the newest version (2.1+r265~daily~ubuntu16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up paper-icon-theme (1.5.716-201806100126~daily~ubuntu16.04.1) ...
gtk-update-icon-cache: No theme index file.
WARNING: icon cache generation failed
update-alternatives: error: alternative path /usr/share/icons/Paper/cursor.theme doesn't exist
dpkg: error processing package paper-icon-theme (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 paper-icon-theme
E: Sub-process /usr/bin/dpkg returned an error code (1)

I tried to build from the source, and successfully built the theme in "paper-gtk-theme", but not with "paper-icon-theme" with "meson "build" --prefix=/usr", as the meson build has an error:

[Errno 2] No such file or directory

**Comment by jason-gu** [comment]
Looks like the latest build for amd64 in the new PPA failed.

![ppa_err](https://user-images.githubusercontent.com/2045134/41327470-76e36722-6e78-11e8-866e-af59425154c0.png)

**Comment by phxhuy** [comment]
Thanks! I think it is the reason. This is an adorable theme tho

**Comment by jorge-cbqa** [comment]
Any updates on this issue?

**Comment by snwh** [comment]
working on it

**Comment by snwh** [comment]
or trying to, I have no clue what it's doing.

**Comment by cgrs** [comment]
@phxhuy which meson version do you have?

**Comment by snwh** [comment]
Fixed :tada:
