### ISSUE TITLE
Installed paper, have huge caret in some programs even when the paper cursor theme is not selected

### ISSUE THREAD

**Issue by CottonEaster** [snwh/paper-icon-theme#678]
Screenshot, showing (1) the huge caret, (2) that I have paper installed, (3) that the paper cursor theme is not selected:

![workspace 1_001](https://user-images.githubusercontent.com/9998846/42543733-254ed48a-84a5-11e8-9334-c784fd12186a.png)

Linux Mint 19 x64 Cinnamon
paper-icon-them 1.5.719-201806241

**Comment by CottonEaster** [comment]
But perhaps this is a Mint bug. Do you have good grounds for thinking that it is? If so, I'll report it to the Mint team.

**Comment by snwh** [comment]
Yeah that could be a bug in Mint/Cinnamon bug, especially considering you're not using the Paper cursors.

**Comment by CottonEaster** [comment]
I think I've found the source of the problem - and it's a problem that affects the Grub-Customizer program too, but a problem I could not reproduce at all on a Mint 19 liveCD.

When I install paper-icon-theme, the terminal says this:

> update-alternatives: using /usr/share/icons/Paper/cursor.theme to provide /usr/share/icons/default/index.theme (x-cursor-theme) in auto mode

I feel this should be enough to tell us whether this is a Paper bug, a Mint bug, or a problem with my installation of Mint.

**Comment by CottonEaster** [comment]
The following seems to fix the problem and indeed perhaps it fixes [this other problem too](https://github.com/snwh/moka-icon-theme/issues/393) (at any rate, I no longer have that problem):

```
sudo rm /etc/alternatives/x-cursor-theme
sudo ln -s /usr/share/icons/DMZ-White/cursor.theme /etc/alternatives/x-cursor-theme
```
