### ISSUE TITLE
All files have executable permissions

### ISSUE THREAD

**Issue by tim77** [snwh/paper-icon-theme#679]
I noticed that probably all files in project have executable bit `-x`. **Suru-icon-theme** have the same issue.

**Comment by snwh** [comment]
yep, they need to all be executable because there's a bitcoin miner hidden in the icon set. jk

**Comment by Vascom** [comment]
Do you think this is funny?

**Comment by snwh** [comment]
What's actually not funny is a handful free software developers actually resorting to hidden bitcoin miners because users don't want to pay for free software and turn their nose up at traditional monetization schemes.

**Comment by tim77** [comment]
@snwh sorry I didn't have any plans to offend you and i am not really interesting in this kind of discussion. I just wanted to point on issue which could be fixed easily.

More info: [ExecutableBit](https://wiki.ubuntu.com/Security/ExecutableBit).

**Comment by snwh** [comment]
@tim77 nor am I, but this minor issue seems to have turned into a small forum

**Comment by snwh** [comment]
Fixed with a few sweeping `chmod` commands
