### ISSUE TITLE
Evolution trashcan doesn't fit with the rest

### ISSUE THREAD

**Issue by evilhamsterman** [snwh/paper-icon-theme#68]
The trashcan in Evolution doesn't fit with the rest of the icons around it. It seems a bit big and the grey vs black is a bit off putting. 
![evolution delete](https://cloud.githubusercontent.com/assets/59560/11510681/c3bcc620-9819-11e5-883e-66fa5da46e1b.png)

**Comment by snwh** [comment]
Here Evolution is using a location icon instead of an action icon, which in Paper, are of different styles therefore they look out of place when used together.

**Comment by evilhamsterman** [comment]
I though it might be something like that since I have seen similar issue with different icon sets. Perhaps it would be better to file a bug with Evolution to get them to fix the icon. Though I don't know if they ever will

**Comment by snwh** [comment]
Evolution is getting overhauled anyway and will be moving to the use of symbolic icons –like most of GNOME's apps.
