### ISSUE TITLE
theme has no size field warning

### ISSUE THREAD

**Issue by user501254** [snwh/paper-icon-theme#69]
[ashesh@MISTRI ~] $ nautilus
    Initializing nautilus-open-terminal extension
    
    (nautilus:15962): Gtk-WARNING **: Theme directory 8x8/emblems of theme Paper has no size field
    
    
    (nautilus:15962): Gtk-WARNING **: Theme directory 8x8@2x/emblems of theme Paper has no size field
    
    
    (nautilus:15962): Gtk-WARNING **: Theme directory 16x16@2x/panel of theme Paper has no size field
    
    
    (nautilus:15962): Gtk-WARNING **: Theme directory 24x24@2x/animations of theme Paper has no size field
    
    
    (nautilus:15962): Gtk-WARNING **: Theme directory 24x24@2x/panel of theme Paper has no size field
    
    ^C

**Comment by snwh** [comment]
Fixed in  latest
