### ISSUE TITLE
Material Design Icons

### ISSUE THREAD

**Issue by ackushiw** [snwh/paper-icon-theme#7]
Hey Sam,

Awesome project! Have you checked out this website http://materialdesignicons.com/
Could be a good resource/platform for you to use available icons or even add new ones. 

Thanks!

**Comment by snwh** [comment]
I'm of the habit of creating original icons. I've no intention of using any of Google's or other third party icons.

**Comment by snwh** [comment]
These icons are simply inspired by Material design, but not a direct continuation or addition to.
