### ISSUE TITLE
Elementary settings

### ISSUE THREAD

**Issue by bil-elmoussaoui** [snwh/paper-icon-theme#70]
Elementary settings has still some missing icons
![capture d ecran de 2015-12-02 20 10 30](https://cloud.githubusercontent.com/assets/7660997/11541111/c21a924e-9930-11e5-8e7c-f1f07b899021.png)

**Comment by snwh** [comment]
I suspect you have a local installation of Paper, one of which is overriding another version. I suggest finding & removing all and reinstalling.

**Comment by bil-elmoussaoui** [comment]
Removed the local installation, and installed the latest github version. I still have an issue with Sound & About icons 
![capture d ecran de 2015-12-02 21 01 28](https://cloud.githubusercontent.com/assets/7660997/11542502/f3512f88-9937-11e5-8a0e-713e314295be.png)

**Comment by snwh** [comment]
Oui, je sais.  Il y a des icônes qui ne sont pas complètes ou inclus. Comme ceux.

**Comment by snwh** [comment]
mais la "About" plug utilise une icône d'actione (qui est un style différent dans Paper) au lieu d'une icône de la catégorie. c'est une bug en Switchboard

**Comment by bil-elmoussaoui** [comment]
Merci pour les informations. J'ai prévenu les devs de Switchboard de cela!

**Comment by snwh** [comment]
comme un dev ElementaryOS, j'ai déjà ;)
