### ISSUE TITLE
Paper theme disappeared

### ISSUE THREAD

**Issue by radjuga** [snwh/paper-icon-theme#72]
Good day,

I use Paper themes (GTK & icons, installed via PPA) with Mint 17.2 Cinnamon edition for some time and was OK till latest update (couple days ago).
Now icons theme (only) disappeared from Control Centre themes chooser.
Even after installation as new via PPA or via master package nothing happens.
Paper is in /usr/share/icons/ with no additional folders inside or something like this.
Maybe some way to sort it out?

(just installed Moka via PPA and it's OK, the only issue with Paper)

Thank you.

**Comment by radjuga** [comment]
One more thing so far: mouse cursors theme Paper is OK

**Comment by snwh** [comment]
This is the same issue as #71 try updating your system again
