### ISSUE TITLE
Missing Application Menu Icon

### ISSUE THREAD

**Issue by LoomiDigital** [snwh/paper-icon-theme#732]
I've just installed this on latest kali but the 3x3 white squares icon to expand app menu is missing.

**Comment by AlbertAlonso** [comment]
> -  A screenshot of your issue or an image of the original icon you are requesting to be themed
> - The file name for the missing icon or the requested icon, for example gimp.png or system-shutdown.svg
> - A short description of the application or software that you are requesting an icon for.
> 
> **Note**: some software ships hardcoded icons, meaning when you install icons are not placed in the system-wide directory /usr/share/icons which makes them unthemeable.

This are the requirements for requesting an icon in the README file. I think you will have a better chance if you put them in your request.

Good luck.
