### ISSUE TITLE
Gnome 3.36 icon changes

### ISSUE THREAD

**Issue by isjerryxiao** [snwh/paper-icon-theme#735]
Gnome 3.36 has quite a few icon names changed. All the icons in the actions category of Adwaita are **symbolic icons** now.  
Paper displays these icons like this.  
![image](https://user-images.githubusercontent.com/14978021/76197015-50142c00-6226-11ea-92e5-85121db2e6aa.png)(it's actually left arrows)

**Comment by xTeixeira** [comment]
#731 fixes this

**Comment by isjerryxiao** [comment]
@xTeixeira Thanks
