### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by txtsd** [snwh/paper-icon-theme#736]
There haven't been any commits or merges since May 2019. There are some urgent issues and PRs that are pending with no correspondence from @snwh.

**Comment by snwh** [comment]
It's dead insofar as my job takes up my time and my interest in being a theme maintainer in my free time is low these days, so yeah there is very little activity on this project. But I'll take a look at these supposed urgent issues.

**Comment by txtsd** [comment]
Mainly #730 and #731

**Comment by decmade** [comment]
Whatever just got pushed in broke it.

**Comment by pratikborsadiya** [comment]
It's broke for me too after latest update in Ubuntu 18.04.

**Comment by dvorapa** [comment]
Reported in #737

**Comment by txtsd** [comment]
@snwh Thanks for pushing the necessary changes. The broken icons work fine for me again.

@decmade @pratikborsadiya Not sure why you guys hijacked this issue to post about breaking changes. Make a new issue.

**Comment by decmade** [comment]
Sorry.. seemed relevant to the topic.
