### ISSUE TITLE
Huge battery indicator icon

### ISSUE THREAD

**Issue by sAleksovski** [snwh/paper-icon-theme#74]
The battery indicator icon is larger than normal while charging and the battery level is below 10%.

Battery icon at 7%
![Battery icon](https://cloud.githubusercontent.com/assets/7473800/11575018/42400e02-9a0f-11e5-8b06-f601b64b15fb.png)

Battery icon at 27%
![Battery icon](https://cloud.githubusercontent.com/assets/7473800/11575024/4dab90f4-9a0f-11e5-974b-339e41bd5258.png)

**Comment by snwh** [comment]
Is this still an issue?

**Comment by sAleksovski** [comment]
Yes
![image](http://i.imgur.com/QPQwigh.png)

**Comment by snwh** [comment]
Weird.

**Comment by norsasono** [comment]
It's mine, after the update.
![battery](https://cloud.githubusercontent.com/assets/11081536/15608997/9288ccba-2447-11e6-8deb-0e810de0ae66.png)

**Comment by snwh** [comment]
The power indicator (for unknown reasons) is the only one to use the `*-symbolic` battery icons which are 16x16 pixels so they are being stretched and are appearing grey since they are that colour by default in Paper.

**Comment by snwh** [comment]
Related bugs closed.
