### ISSUE TITLE
Add PPA Support for Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by leoherzog** [snwh/paper-icon-theme#744]
Packages for [the snwh PPA on Launchpad](https://launchpad.net/~snwh/+archive/ubuntu/ppa) only has packages up to 19.04 Disco Dingo. Please add support for packages for the `focal` release, Ubuntu 20.04. Love the projects!

**Comment by ScarletSpidey** [comment]
Really missing these icons since i installed ubuntu 20.04

**Comment by koenhoeijmakers** [comment]
For the time being you can build them with meson instead.

**Comment by leoherzog** [comment]
Or you can change `focal` to `disco` in the `sources.list` file for now

**Comment by felixpk** [comment]
Or you can download the .deb

**Comment by GalGreenfield** [comment]
> Or you can change `focal` to `disco` in the `sources.list` file for now

What's that file? I'm new to Linux.

**Comment by GalGreenfield** [comment]
I'm not even seeing anything related to Paper in `sources.list` (at `/etc/apt/sources.list`). How can I add the package's repo there?

**Comment by leoherzog** [comment]
Hi @GalGreenfield. If you're on an Ubuntu-based distribution, you can use the `add-apt-repository` command described on @snwh['s PPA](https://launchpad.net/~snwh/+archive/ubuntu/ppa) in the "Adding this PPA to your system" section. Once you've done that, you'll have to temporarily change the contents to the `snwh` list file in `/etc/apt/sources.list.d/` to replace your distro's codename with `disco`. The contents of the file would then look something like:
```
deb http://ppa.launchpad.net/snwh/ppa/ubuntu disco main 
deb-src http://ppa.launchpad.net/snwh/ppa/ubuntu disco main 
```
because that's the most recent distro that he currently supports.

**Comment by bartek-szymanski** [comment]
> Hi @GalGreenfield. If you're on an Ubuntu-based distribution, you can use the `add-apt-repository` command described on @snwh['s PPA](https://launchpad.net/~snwh/+archive/ubuntu/ppa) in the "Adding this PPA to your system" section. Once you've done that, you'll have to temporarily change the contents to the `snwh` list file in `/etc/apt/sources.list.d/` to replace your distro's codename with `disco`. The contents of the file would then look something like:
> 
> ```
> deb http://ppa.launchpad.net/snwh/ppa/ubuntu disco main 
> deb-src http://ppa.launchpad.net/snwh/ppa/ubuntu disco main 
> ```
> 
> because that's the most recent distro that he currently supports.

I can just add for clarity

Go to directory 
`/etc/apt/sources.list.d/`

and make a change in the file 
`snwh-ubuntu-ppa-focal.list`

**Comment by StephenBeirlaen** [comment]
The packages are now available for ubuntu20.10.1 and ubuntu20.04.1 since 2020-07-19
https://launchpad.net/~snwh/+archive/ubuntu/ppa
