### ISSUE TITLE
Transmission panel icon

### ISSUE THREAD

**Issue by sAleksovski** [snwh/paper-icon-theme#75]
Could you change the transmission panel icon, and make it more .. gray?
It really looks weird being the only colored icon in the panel.

![Transmission](https://cloud.githubusercontent.com/assets/7473800/11575055/745517d4-9a0f-11e5-8b7d-da6c6ebc39b2.png)

**Comment by snwh** [comment]
If I did that, then the Transmission icon at this size elsewhere in the system would be monochrome as well.

**Comment by sAleksovski** [comment]
I was using [this](http://traumad91.deviantart.com/art/Transmission-Indicator-Icon-476377115) for a while. It changes only the 24, 22 and 16 icon sizes. I didn't notice the monochrome icon anywhere else in the system.

**Comment by ajthemacboy** [comment]
Sorry for being offtopic, but what Desktop Environment are you using? GNOME? What shell theme?

**Comment by sAleksovski** [comment]
elementary OS 0.3.2 Freya

**Comment by snwh** [comment]
Does transmission have its own panel icon?

**Comment by snwh** [comment]
There is a panel icon for Transmission included in Paper

**Comment by sAleksovski** [comment]
It looks OK now.

![image](https://cloud.githubusercontent.com/assets/7473800/14798451/f285ac38-0b37-11e6-85b6-e2b93576e5b2.png)
