### ISSUE TITLE
Windows Version?

### ISSUE THREAD

**Issue by xCancazedd** [snwh/paper-icon-theme#756]
### 
Hi, I was wondering if any of you lovely developers could make a windows version for the paper cursors? I currently have a windows machine, which I don't even know how to install linux on. They look really cool and a windows version would be amazing. If you guys can't it's totally alright. Thanks! :)

**Comment by touzel** [comment]
+1, I found the cursor pack while demo-ing pop!_os and absolutely loved it!
It would be amazing if there was a downloadable .inf installation file for windows as it's my daily driver.

**Comment by xCancazedd** [comment]
> +1, I found the cursor pack while demo-ing pop!_os and absolutely loved it!
> It would be amazing if there was a downloadable .inf installation file for windows as it's my daily driver.

Yesssss!!! This is exactly what I meant!!

**Comment by xCancazedd** [comment]
Well, I'm going to close this issue, as I've found what looks likes the closest version to the paper cursors for windows: https://www.deviantart.com/nighted/art/DMZ-Cursors-58429447, if they ever make a Windows Version feel free to open  an issue and tag me. Thanks much.
