### ISSUE TITLE
Large and small address-book icon differ

### ISSUE THREAD

**Issue by user501254** [snwh/paper-icon-theme#77]
![screenshot from 2015-12-07 11-09-52](https://cloud.githubusercontent.com/assets/6129517/11619912/1c1da6b4-9cd3-11e5-85be-30a8c86d0e94.png)

Not sure if it's intentional.

**Comment by snwh** [comment]
This is not a paper-gtk-theme issue.

**Comment by snwh** [comment]
Simple: they're unfinished.

**Comment by snwh** [comment]
Fixed in 1ccbda3
