### ISSUE TITLE
Dynamic window colors

### ISSUE THREAD

**Issue by ajthemacboy** [snwh/paper-icon-theme#78]
I had the idea today for automatic window coloring based on the prominent icon color.

I have no idea how feasible this is with only the tools that come with Gnome, but this would make things a lot easier and more dynamic.

For example, Skype currently has a grey window border when using the Paper GTK theme. It's easy to get the prominent color from the Skype icon, blue, which should also be the color of the window. 

The Gnome calculator's icon is highlighted with green, which is the same color as the window border. Archive manager is kindof an exception; its highlight color is blue but the window is green.

If this isn't possible, please disregard :)

**Comment by snwh** [comment]
This sort of thing would be handled by a window manager and not by a GTK theme, so it's not something I would do.
