### ISSUE TITLE
[Chromixium, likely other OSes] Application menu icons missing

### ISSUE THREAD

**Issue by spurdo-sparde** [snwh/paper-icon-theme#80]
![screenshot from 2015-12-13 19 07 14](https://cloud.githubusercontent.com/assets/12941327/11770471/d4d81506-a1cc-11e5-9641-93008c094c67.png)

**Comment by snwh** [comment]
Are you using a fork of Paper? The symbolic icons being used in the background application are not Paper's.

**Comment by nayingjie** [comment]
@snwh If you mean the docked icons (Gmail, Drive, Chromium), these are provided on Chromixium by default. I will redownload this repo and try again, though.

**Comment by snwh** [comment]
No, those in the file manager.

**Comment by nayingjie** [comment]
These must be preset.
