### ISSUE TITLE
Terminal icon too dark(?)

### ISSUE THREAD

**Issue by user501254** [snwh/paper-icon-theme#82]
I am not sure if there can be a better color alternative than the current one. 
On dark themes, the icon is a bit difficult to differentiate.
Can you please give it a thought?

**Comment by fastrizwaan** [comment]
On gnome shell and budgie desktop, the terminal icon is almost invisible. Please see this, just beside "Menu", "gnome-terminal is running and it is very difficult to distinguish.
![screenshot from 2016-01-01 07-53-58](https://cloud.githubusercontent.com/assets/1161682/12069539/003467d8-b05d-11e5-91e0-f27e4b943ad3.png)

**Comment by robotmaxtron** [comment]
:+1:

**Comment by user501254** [comment]
The new icon goes well with a lot many themes now.
However I feel it's still somewhat indistinguishable under the popular [Arc Theme](https://github.com/horst3180/arc-theme). I guess a dual colored (light-dark), bordered icon would serve best.

![screenshot from 2016-05-13 09-58-37](https://cloud.githubusercontent.com/assets/6129517/15238022/50645af4-18f1-11e6-9b6c-4eb43304bc76.png)

Sorry if I am picking on this too much. :sweat_smile:

**Comment by snwh** [comment]
@user501254 but then it won't would with light themes. :P

**Comment by user501254** [comment]
Oh yeah, that could happen.
If light borders around the existing one won't work, I wonder if it would stand out with a larger inset prompt ($_).

**Comment by maxkoryukov** [comment]
+1 , the same trouble;)

**Comment by user501254** [comment]
@snwh
I request for reopening this issue. :-)

**Comment by snwh** [comment]
@user501254 it was too dark and now it's not, so the original issue is closed. ;)
