### ISSUE TITLE
Grey squares instead of Bluetooth and battery icons on Elementary OS Freya beta 2  

### ISSUE THREAD

**Issue by Dmitry-Kiselev** [snwh/paper-icon-theme#9]
After applying paper icons with paper theme, icons of Bluetooth and battery became a grey squares. With Elementary theme it happens only for Bluetooth icon.
![screenshot from 2015-03-07 12 01 34](https://cloud.githubusercontent.com/assets/10479035/6540995/51cf9922-c4c3-11e4-9e10-ac0cf884b7ca.png)
![screenshot from 2015-03-07 12 11 36](https://cloud.githubusercontent.com/assets/10479035/6540996/51d09f7a-c4c3-11e4-9c55-f9f1222ae058.png)

**Comment by aleksandar-todorovic** [comment]
I can confirm this issue for the battery indicator.

**Comment by Dmitry-Kiselev** [comment]
Thank you! The problem is solved.

**Comment by Jucgshu** [comment]
Hey guys,

I know this thread is (really) old, but I got the exact same issue after git pulled this weekend.

Please tell me if you want me to open a new one (the symptoms are exactly the same : both the bluetooth & battery icons turned out to become grey square).
