### ISSUE TITLE
Huge icon cache file - for no apparent reason

### ISSUE THREAD

**Issue by steelbox** [snwh/paper-icon-theme#92]
Hi, I have just noticed a huge cache file for icons.
```
/usr/share/icons/Paper $ ls -Alh | grep cache
-rw-r--r--  1 root root 1.2G Feb 13 12:49 icon-theme.cache
```

I have been using your theme for a little over a week, my icons are not used with your theme (I use another theme package for the icons). Is this file normal for your package, when not using icons?

**Comment by snwh** [comment]
That's generated by the system, you are free to delete it.

**Comment by steelbox** [comment]
Okay, thank you I have deleted it.
