### ISSUE TITLE
Project still on track?

### ISSUE THREAD

**Issue by thomasstevenson** [snwh/paper-icon-theme#93]
There haven't been any updates or commits in 3 months. Is the icon theme going to be updated and reach a stable release?

I'm a huge fan of the theme and it would be a huge letdown to see it become abandoned.

**Comment by snwh** [comment]
Sorry, it's not abandoned. It's just a lot of work to develop an icon theme so it gets picked at sporadically.

**Comment by thomasstevenson** [comment]
Thanks for the quick reply! Sorry for being a bit of a pain, but is there an ETA for a stable 1.0 version of the icon theme?

**Comment by snwh** [comment]
@thomasstevenson fwiw the version is 1.1. The "Beta" label is just so I can continue to release an "incomplete" theme.

**Comment by snwh** [comment]
For instance, it took me a couple years to "complete" Moka. I essentially have to be motivated to work on Paper –usually that happens when interest in the theme goes up and/or I get some positive feedback or an increased level of bug reports/email.
