### ISSUE TITLE
Odd shapes / sizes with window spread...

### ISSUE THREAD

**Issue by XLCM** [snwh/paper-icon-theme#94]
I've noticed that, when I use hotcorners to do window spread in Ubuntu 14.04, the windows that pop up show each application and it's icon in strange sizes.  Screenshot attached. 

Any ideas about how to fix this?

PC
![screenshot from 2016-03-22 22 57 18](https://cloud.githubusercontent.com/assets/7649046/13975341/029a99c4-f082-11e5-8f18-16b978d3300c.png)

**Comment by snwh** [comment]
Woah.

**Comment by snwh** [comment]
No clue what's going on here, aside from Unity spread using the huge 512x512 paper icons.

**Comment by user501254** [comment]
Same issue on Ubuntu 16.04 LTS release.

**Comment by snwh** [comment]
I have a theory, does a similar thing happen with Adwaita/GNOME icons?

**Comment by user501254** [comment]
When using Gnome icons:
![screenshot from 2016-04-29 01-11-21](https://cloud.githubusercontent.com/assets/6129517/14899006/a9dae166-0da7-11e6-9245-130948156403.png)

When using Paper icons:
![screenshot from 2016-04-29 01-11-05](https://cloud.githubusercontent.com/assets/6129517/14899034/c9d8c24e-0da7-11e6-9639-edef22834869.png)

**Comment by snwh** [comment]
Also strange that the LibreOffice icon for both is not as large. I suspect this is a bug in the window spread itself.
