### ISSUE TITLE
Icon for R

### ISSUE THREAD

**Issue by JLCCI** [snwh/paper-icon-theme#97]
Thanks for amazing work with the theme and icon set!

Would be great if you could add an icon for R as the stock is sticking out:
http://opensourcemac.com/wp-content/uploads/2009/12/R.png

Software description, very popular in academia and industry:
https://en.wikipedia.org/wiki/R_%28programming_language%29

Keep up the good work, your effort is much appreciated.

**Comment by snwh** [comment]
So `r.png`?

**Comment by JLCCI** [comment]
Yes.

If it would not be a problem it would also be great if you could add the shortcut to python 3.5 (you already have all the major versions except the newest one).

Again, thanks for making Linux look great. Looking forward to updates for the Paper theme.

**Comment by enrigf** [comment]
@snwh This R icon name needs to be changed, here is the `cat /usr/share/applications/R.desktop` output:


```[Desktop Entry]
Version=1.0
Type=Application
Name=R
Comment=R software environment for statistical computing and graphics
Exec=R
Icon=rlogo_icon
Terminal=true
StartupNotify=false
Categories=Graphics;Science;Math
```

**It should say:**
`Icon=r`
Or change all the `r.png` files in `Paper` folder to `rlogo_icon.png`
And, nice icon design, I love it.
