### ISSUE TITLE
Window top bars not theming

### ISSUE THREAD

**Issue by rvolden** [snwh/paper-icon-theme#98]
Something I can't figure out is why apps that are supposed to have colored top bars appear to be off-white when active, but properly colored when in the background. This happened after a fresh install of Fedora 23 (4.4.6-300.fc23.x86_64). Any fix would be greatly appreciated!

**Comment by snwh** [comment]
I think you meant to file a bug agaisnt the GTK Theme: https://github.com/snwh/paper-gtk-theme/issues
