### ISSUE TITLE
GNOME 3.20 support

### ISSUE THREAD

**Issue by tpmajer** [snwh/paper-icon-theme#99]
There are few missing icons in GNOME 3.20, for example polari, cheese, gnome-maps, gnome-calendar, gnome-software, gnome-clocks.

**Comment by snwh** [comment]
These did have icon support. I suspect these are sandboxed apps, I'm going to have to look into how that affects my icon themes.

**Comment by bil-elmoussaoui** [comment]
@snwh All the applications on Gnome 3.20 don't use t

**Comment by snwh** [comment]
@bil-elmoussaoui figured.

**Comment by elvisd** [comment]
Books is missing too.
Icon name = org.gnome.Books
